# https://dwarfstd.org

const
  DW_ATE_address* = 0x1.cuint
  DW_ATE_boolean* = 0x2.cuint
  DW_ATE_complex_float* = 0x3.cuint
  DW_ATE_float* = 0x4.cuint
  DW_ATE_signed* = 0x5.cuint
  DW_ATE_signed_char* = 0x6.cuint
  DW_ATE_unsigned* = 0x7.cuint
  DW_ATE_unsigned_char* = 0x8.cuint
  DW_ATE_imaginary_float* = 0x09.cuint
  DW_ATE_packed_decimal* = 0x0a.cuint
  DW_ATE_numeric_string* = 0x0b.cuint
  DW_ATE_edited* = 0x0c.cuint
  DW_ATE_signed_fixed* = 0x0d.cuint
  DW_ATE_unsigned_fixed* = 0x0e.cuint
  DW_ATE_decimal_float* = 0x0f.cuint
  DW_ATE_UTF* = 0x10.cuint
  DW_ATE_lo_user* = 0x80.cuint
  DW_ATE_hi_user* = 0xFF.cuint

const
  DIFlagZero* = 0
  DIFlagPrivate* = 1
  DIFlagProtected* = 2
  DIFlagPublic* = 3
  DIFlagFwdDecl* = 1 shl 2
  DIFlagAppleBlock* = 1 shl 3
  DIFlagReservedBit4* = 1 shl 4
  DIFlagVirtual* = 1 shl 5
  DIFlagArtificial* = 1 shl 6
  DIFlagExplicit* = 1 shl 7
  DIFlagPrototyped* = 1 shl 8
  DIFlagObjcClassComplete* = 1 shl 9
  DIFlagObjectPointer* = 1 shl 10
  DIFlagVector* = 1 shl 11
  DIFlagStaticMember* = 1 shl 12
  DIFlagLValueReference* = 1 shl 13
  DIFlagRValueReference* = 1 shl 14
  DIFlagReserved* = 1 shl 15
  DIFlagSingleInheritance* = 1 shl 16
  DIFlagMultipleInheritance* = 2 shl 16
  DIFlagVirtualInheritance* = 3 shl 16
  DIFlagIntroducedVirtual* = 1 shl 18
  DIFlagBitField* = 1 shl 19
  DIFlagNoReturn* = 1 shl 20
  DIFlagTypePassByValue* = 1 shl 22
  DIFlagTypePassByReference* = 1 shl 23
  DIFlagEnumClass* = 1 shl 24
  DIFlagFixedEnum* = DIFlagEnumClass
  DIFlagThunk* = 1 shl 25
  DIFlagNonTrivial* = 1 shl 26
  DIFlagBigEndian* = 1 shl 27
  DIFlagLittleEndian* = 1 shl 28
  DIFlagIndirectVirtualBase* = (1 shl 2) or (1 shl 5)
  DIFlagAccessibility* = DIFlagPrivate or DIFlagProtected or DIFlagPublic
  DIFlagPtrToMemberRep* = DIFlagSingleInheritance or DIFlagMultipleInheritance or DIFlagVirtualInheritance

const
  DW_TAG_array_type* = 0x01
  DW_TAG_class_type* = 0x02
  DW_TAG_entry_point* = 0x03
  DW_TAG_enumeration_type* = 0x04
  DW_TAG_formal_parameter* = 0x05
  DW_TAG_imported_declaration* = 0x08
  DW_TAG_label* = 0x0a
  DW_TAG_lexical_block* = 0x0b
  DW_TAG_member* = 0x0d
  DW_TAG_pointer_type* = 0x0f
  DW_TAG_reference_type* = 0x10
  DW_TAG_compile_unit* = 0x11
  DW_TAG_string_type* = 0x12
  DW_TAG_structure_type* = 0x13
  DW_TAG_subroutine_type* = 0x15
  DW_TAG_typedef* = 0x16
  DW_TAG_namelist* = 0x2b 
  DW_TAG_namelist_item* = 0x2c 
  DW_TAG_packed_type* = 0x2d 
  DW_TAG_subprogram* = 0x2e 
  DW_TAG_template_type_parameter* = 0x2f 
  DW_TAG_template_value_parameter* = 0x30 
  DW_TAG_thrown_type* = 0x31 
  DW_TAG_try_block* = 0x32 
  DW_TAG_variant_part* = 0x33 
  DW_TAG_variable* = 0x34 
  DW_TAG_volatile_type* = 0x35 
  DW_TAG_dwarf_procedure* = 0x36 
  DW_TAG_restrict_type* = 0x37 
  DW_TAG_interface_type* = 0x38 
  DW_TAG_namespace* = 0x39 
  DW_TAG_imported_module* = 0x3a 
  DW_TAG_unspecified_type* = 0x3b 
  DW_TAG_partial_unit* = 0x3c 
  DW_TAG_imported_unit* = 0x3d 
  DW_TAG_condition* = 0x3f 
  DW_TAG_shared_type* = 0x40 
  DW_TAG_type_unit* = 0x41 
  DW_TAG_rvalue_reference_type* = 0x42 
  DW_TAG_template_alias* = 0x43 
  DW_TAG_lo_user* = 0x4080 
  DW_TAG_hi_user* = 0xffff
  DW_TAG_union_type* = 0x17 
  DW_TAG_unspecified_parameters* = 0x18 
  DW_TAG_variant* = 0x19 
  DW_TAG_common_block* = 0x1a 
  DW_TAG_common_inclusion* = 0x1b 
  DW_TAG_inheritance* = 0x1c 
  DW_TAG_inlined_subroutine* = 0x1d 
  DW_TAG_module* = 0x1e 
  DW_TAG_ptr_to_member_type* = 0x1f 
  DW_TAG_set_type* = 0x20 
  DW_TAG_subrange_type* = 0x21 
  DW_TAG_with_stmt* = 0x22 
  DW_TAG_access_declaration* = 0x23 
  DW_TAG_base_type* = 0x24 
  DW_TAG_catch_block* = 0x25 
  DW_TAG_const_type* = 0x26 
  DW_TAG_constant* = 0x27 
  DW_TAG_enumerator* = 0x28 
  DW_TAG_file_type* = 0x29 
  DW_TAG_frien* = 0x2a

