type
  MemoryBufferRef* = ptr OpaqueMemoryBuffer
  ContextRef* = ptr OpaqueContext
  ModuleRef* = ptr OpaqueModule
  TypeRef* = ptr OpaqueType
  ValueRef* = ptr OpaqueValue
  BasicBlockRef* = ptr OpaqueBasicBlock
  MetadataRef* = ptr OpaqueMetadata
  NamedMDNodeRef* = ptr OpaqueNamedMDNode
  ValueMetadataEntry* = opaqueValueMetadataEntry
  BuilderRef* = ptr OpaqueBuilder
  DIBuilderRef* = ptr OpaqueDIBuilder
  ModuleProviderRef* = ptr OpaqueModuleProvider
  PassManagerRef* = ptr OpaquePassManager
  PassRegistryRef* = ptr OpaquePassRegistry
  UseRef* = ptr OpaqueUse
  AttributeRef* = ptr OpaqueAttributeRef
  DiagnosticInfoRef* = ptr OpaqueDiagnosticInfo
  ComdatRef* = ptr comdat
  ModuleFlagEntry* = opaqueModuleFlagEntry
  JITEventListenerRef* = ptr OpaqueJITEventListener
  BinaryRef* = ptr OpaqueBinary
