/* Generated by Nim Compiler v1.6.6 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\Users\林仁傑\source\mingw64\bin\gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN   -IC:\Users\林仁傑\source\nim-1.6.6\lib -IC:\Users\林仁傑\source\Runner\cc -o C:\Users\林仁傑\source\Runner\cc\foo\@mast.nim.c.o C:\Users\林仁傑\source\Runner\cc\foo\@mast.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  typedef struct tyObject_StmtcolonObjectType___D3ZZSzbHHz9aqVhgDX6uEAA tyObject_StmtcolonObjectType___D3ZZSzbHHz9aqVhgDX6uEAA;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_CTypecolonObjectType___y9c8kbbfIvBCGqKHvKcIVGw tyObject_CTypecolonObjectType___y9c8kbbfIvBCGqKHvKcIVGw;
typedef struct tySequence__xkcxUtflRxy5Nb0qaCHLZQ tySequence__xkcxUtflRxy5Nb0qaCHLZQ;
typedef struct tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ;
typedef struct tySequence__sCWjRzukJ9amxY1VYtECwiw tySequence__sCWjRzukJ9amxY1VYtECwiw;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tySequence__5Ea4hthuw6lQuV4Ge38uDA tySequence__5Ea4hthuw6lQuV4Ge38uDA;
typedef struct tyTuple__QM04Qszh7tudE7LWUtmhXQ tyTuple__QM04Qszh7tudE7LWUtmhXQ;
typedef NU8 tyEnum_StmtKind__wYBYg9bKbICo3tyQx0kTk1w;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_StmtcolonObjectType___D3ZZSzbHHz9aqVhgDX6uEAA {
tyEnum_StmtKind__wYBYg9bKbICo3tyQx0kTk1w k;
union{
struct {NimStringDesc* funcname;
tyObject_CTypecolonObjectType___y9c8kbbfIvBCGqKHvKcIVGw* functy;
tyObject_StmtcolonObjectType___D3ZZSzbHHz9aqVhgDX6uEAA* funcbody;
} _k_1;
struct {NimStringDesc* asms;
} _k_2;
struct {tySequence__xkcxUtflRxy5Nb0qaCHLZQ* stmts;
} _k_3;
struct {tyObject_StmtcolonObjectType___D3ZZSzbHHz9aqVhgDX6uEAA* default_stmt;
} _k_4;
struct {tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ* case_expr;
tyObject_StmtcolonObjectType___D3ZZSzbHHz9aqVhgDX6uEAA* case_stmt;
} _k_5;
struct {tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ* exprbody;
} _k_7;
struct {NimStringDesc* location;
} _k_8;
struct {NimStringDesc* label;
tyObject_StmtcolonObjectType___D3ZZSzbHHz9aqVhgDX6uEAA* labledstmt;
} _k_9;
struct {tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ* iftest;
tyObject_StmtcolonObjectType___D3ZZSzbHHz9aqVhgDX6uEAA* ifbody;
tyObject_StmtcolonObjectType___D3ZZSzbHHz9aqVhgDX6uEAA* elsebody;
} _k_10;
struct {tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ* test;
tyObject_StmtcolonObjectType___D3ZZSzbHHz9aqVhgDX6uEAA* body;
} _k_11;
struct {tyObject_StmtcolonObjectType___D3ZZSzbHHz9aqVhgDX6uEAA* forinit;
tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ* forcond;
tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ* forincl;
tyObject_StmtcolonObjectType___D3ZZSzbHHz9aqVhgDX6uEAA* forbody;
} _k_12;
struct {NimStringDesc* var1name;
tyObject_CTypecolonObjectType___y9c8kbbfIvBCGqKHvKcIVGw* var1type;
} _k_13;
struct {tySequence__sCWjRzukJ9amxY1VYtECwiw* vars;
} _k_14;
struct {tyObject_CTypecolonObjectType___y9c8kbbfIvBCGqKHvKcIVGw* decl;
} _k_15;
};
};
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
NI align;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NU8 tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ;
typedef NU8 tyEnum_BinOP__fynptmmwPBA9aKeAoNUe1qA;
typedef NU8 tyEnum_UnaryOP__UBzoLjzsBr0iHTGRBtQ54w;
typedef NU8 tyEnum_PostfixOP__jgPOCDkMnYUH9ajYVCnMILw;
typedef NU8 tyEnum_CastOp__9crSbEPW1bL178akY7zCPGA;
struct tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ {
tyObject_CTypecolonObjectType___y9c8kbbfIvBCGqKHvKcIVGw* ty;
tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ k;
union{
struct {tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ* voidexpr;
} _k_1;
struct {tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ* lhs;
tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ* rhs;
tyEnum_BinOP__fynptmmwPBA9aKeAoNUe1qA bop;
} _k_2;
struct {tyEnum_UnaryOP__UBzoLjzsBr0iHTGRBtQ54w uop;
tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ* uoperand;
} _k_3;
struct {tyEnum_PostfixOP__jgPOCDkMnYUH9ajYVCnMILw pop;
tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ* poperand;
} _k_4;
struct {NI ival;
} _k_5;
struct {NF fval;
} _k_6;
struct {NimStringDesc* str;
} _k_7;
struct {NimStringDesc* sval;
} _k_8;
struct {tySequence__5Ea4hthuw6lQuV4Ge38uDA* arr;
} _k_9;
struct {tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ* cond;
tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ* cleft;
tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ* cright;
} _k_10;
struct {tyEnum_CastOp__9crSbEPW1bL178akY7zCPGA castop;
tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ* castval;
} _k_11;
struct {tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ* callfunc;
tySequence__5Ea4hthuw6lQuV4Ge38uDA* callargs;
} _k_12;
struct {tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ* left;
tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ* right;
} _k_13;
struct {tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ* obj;
NI idx;
} _k_14;
struct {void* p;
} _k_15;
};
};
struct tyTuple__QM04Qszh7tudE7LWUtmhXQ {
NimStringDesc* Field0;
tyObject_CTypecolonObjectType___y9c8kbbfIvBCGqKHvKcIVGw* Field1;
tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ* Field2;
};
struct tySequence__xkcxUtflRxy5Nb0qaCHLZQ {
  TGenericSeq Sup;
  tyObject_StmtcolonObjectType___D3ZZSzbHHz9aqVhgDX6uEAA* data[SEQ_DECL_SIZE];
};
struct tySequence__5Ea4hthuw6lQuV4Ge38uDA {
  TGenericSeq Sup;
  tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ* data[SEQ_DECL_SIZE];
};
struct tySequence__sCWjRzukJ9amxY1VYtECwiw {
  TGenericSeq Sup;
  tyTuple__QM04Qszh7tudE7LWUtmhXQ data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tySequence__xkcxUtflRxy5Nb0qaCHLZQ)(void* p, NI op);
static N_NIMCALL(void, Marker_tySequence__5Ea4hthuw6lQuV4Ge38uDA)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef__A0r19bnoIYBiAGuW7tYi0BA)(void* p, NI op);
static N_NIMCALL(void, Marker_tySequence__sCWjRzukJ9amxY1VYtECwiw)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef__5KgliZANPtggDh8VWtfw3Q)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem__system_1727)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar___ast_113)(tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ* e);
N_LIB_PRIVATE N_NOINLINE(void, raiseFieldError2)(NimStringDesc* f, NimStringDesc* discVal);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, reprDiscriminant)(NI e, TNimType* typ);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar___systemZdollars_3)(NI x);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, reprStr)(NimStringDesc* s);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar___operators_88)(tyEnum_BinOP__fynptmmwPBA9aKeAoNUe1qA o);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, reprEnum)(NI e, TNimType* typ);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar___operators_85)(tyEnum_UnaryOP__UBzoLjzsBr0iHTGRBtQ54w o);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar___system_3154)(NF x);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar___types_88)(tyObject_CTypecolonObjectType___y9c8kbbfIvBCGqKHvKcIVGw* a, NI level);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, joinShow__ast_229)(tySequence__5Ea4hthuw6lQuV4Ge38uDA* a, NimStringDesc* c);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
static N_INLINE(tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ*, X5BX5D___ast_246)(tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ** s, NI sLen_0, NI i);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_2999)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar___ast_282)(tySequence__5Ea4hthuw6lQuV4Ge38uDA* x);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isConstant__ast_339)(tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ* e);
N_LIB_PRIVATE TNimType NTIstmt58objecttype__D3ZZSzbHHz9aqVhgDX6uEAA_;
N_LIB_PRIVATE TNimType NTIstmtkind__wYBYg9bKbICo3tyQx0kTk1w_;
TNimNode* NimDT___D3ZZSzbHHz9aqVhgDX6uEAA_k[21];
extern TNimType NTIstring__77mFvmsOLKik79ci2hXkHEg_;
extern TNimType NTIctype__9cf0EuNkYZeO83WITZYEetQ_;
N_LIB_PRIVATE TNimType NTIstmtlist__xkcxUtflRxy5Nb0qaCHLZQ_;
N_LIB_PRIVATE TNimType NTIexpr58objecttype__eqRwdyQ9bUMO9bghkVuWSD9cQ_;
N_LIB_PRIVATE TNimType NTIexprkind__kR6KxRhax5CY59atptiseeQ_;
TNimNode* NimDT___eqRwdyQ9bUMO9bghkVuWSD9cQ_k[21];
extern TNimType NTIbinop__fynptmmwPBA9aKeAoNUe1qA_;
extern TNimType NTIunaryop__UBzoLjzsBr0iHTGRBtQ54w_;
extern TNimType NTIpostfixop__jgPOCDkMnYUH9ajYVCnMILw_;
extern TNimType NTIint__rR5Bzr1D5krxoo1NcNyeMA_;
extern TNimType NTIfloat__w9bl9a1ul9ctRJWiMl9cNnIMvg_;
N_LIB_PRIVATE TNimType NTIseqLexprT__5Ea4hthuw6lQuV4Ge38uDA_;
extern TNimType NTIcastop__9crSbEPW1bL178akY7zCPGA_;
extern TNimType NTIpointer__vr5DoT1jILTGdRlYv1OYpw_;
N_LIB_PRIVATE TNimType NTIexpr__A0r19bnoIYBiAGuW7tYi0BA_;
N_LIB_PRIVATE TNimType NTILstring_ctype_exprT__QM04Qszh7tudE7LWUtmhXQ_;
N_LIB_PRIVATE TNimType NTIseqLLstring_ctype_exprTT__sCWjRzukJ9amxY1VYtECwiw_;
N_LIB_PRIVATE TNimType NTIstmt__5KgliZANPtggDh8VWtfw3Q_;
STRING_LITERAL(TM__egaGbf9cvcvVfE5PvoKJgvA_25, "<nil>", 5);
STRING_LITERAL(TM__egaGbf9cvcvVfE5PvoKJgvA_26, "<undefined-value>", 17);
STRING_LITERAL(TM__egaGbf9cvcvVfE5PvoKJgvA_27, "(void)", 6);
STRING_LITERAL(TM__egaGbf9cvcvVfE5PvoKJgvA_28, "field \'voidexpr\' is not accessible for type \'Expr\' using \'k = ", 62);
STRING_LITERAL(TM__egaGbf9cvcvVfE5PvoKJgvA_29, "&(", 2);
STRING_LITERAL(TM__egaGbf9cvcvVfE5PvoKJgvA_30, ")", 1);
STRING_LITERAL(TM__egaGbf9cvcvVfE5PvoKJgvA_31, "<zero>", 6);
STRING_LITERAL(TM__egaGbf9cvcvVfE5PvoKJgvA_32, "<struct-constant>", 17);
STRING_LITERAL(TM__egaGbf9cvcvVfE5PvoKJgvA_33, "field \'obj\' is not accessible for type \'Expr\' using \'k = ", 57);
STRING_LITERAL(TM__egaGbf9cvcvVfE5PvoKJgvA_34, "field \'idx\' is not accessible for type \'Expr\' using \'k = ", 57);
STRING_LITERAL(TM__egaGbf9cvcvVfE5PvoKJgvA_35, "->", 2);
STRING_LITERAL(TM__egaGbf9cvcvVfE5PvoKJgvA_36, "field \'str\' is not accessible for type \'Expr\' using \'k = ", 57);
STRING_LITERAL(TM__egaGbf9cvcvVfE5PvoKJgvA_37, "field \'lhs\' is not accessible for type \'Expr\' using \'k = ", 57);
STRING_LITERAL(TM__egaGbf9cvcvVfE5PvoKJgvA_38, "field \'bop\' is not accessible for type \'Expr\' using \'k = ", 57);
STRING_LITERAL(TM__egaGbf9cvcvVfE5PvoKJgvA_39, "field \'rhs\' is not accessible for type \'Expr\' using \'k = ", 57);
STRING_LITERAL(TM__egaGbf9cvcvVfE5PvoKJgvA_40, "field \'poperand\' is not accessible for type \'Expr\' using \'k = ", 62);
STRING_LITERAL(TM__egaGbf9cvcvVfE5PvoKJgvA_41, "field \'pop\' is not accessible for type \'Expr\' using \'k = ", 57);
STRING_LITERAL(TM__egaGbf9cvcvVfE5PvoKJgvA_42, "field \'uop\' is not accessible for type \'Expr\' using \'k = ", 57);
STRING_LITERAL(TM__egaGbf9cvcvVfE5PvoKJgvA_43, "field \'uoperand\' is not accessible for type \'Expr\' using \'k = ", 62);
STRING_LITERAL(TM__egaGbf9cvcvVfE5PvoKJgvA_44, "field \'ival\' is not accessible for type \'Expr\' using \'k = ", 58);
STRING_LITERAL(TM__egaGbf9cvcvVfE5PvoKJgvA_45, "field \'fval\' is not accessible for type \'Expr\' using \'k = ", 58);
STRING_LITERAL(TM__egaGbf9cvcvVfE5PvoKJgvA_46, "field \'sval\' is not accessible for type \'Expr\' using \'k = ", 58);
STRING_LITERAL(TM__egaGbf9cvcvVfE5PvoKJgvA_47, "field \'cond\' is not accessible for type \'Expr\' using \'k = ", 58);
STRING_LITERAL(TM__egaGbf9cvcvVfE5PvoKJgvA_48, "field \'cleft\' is not accessible for type \'Expr\' using \'k = ", 59);
STRING_LITERAL(TM__egaGbf9cvcvVfE5PvoKJgvA_49, "field \'cright\' is not accessible for type \'Expr\' using \'k = ", 60);
STRING_LITERAL(TM__egaGbf9cvcvVfE5PvoKJgvA_50, "field \'castval\' is not accessible for type \'Expr\' using \'k = ", 61);
STRING_LITERAL(TM__egaGbf9cvcvVfE5PvoKJgvA_51, "field \'left\' is not accessible for type \'Expr\' using \'k = ", 58);
STRING_LITERAL(TM__egaGbf9cvcvVfE5PvoKJgvA_52, "field \'right\' is not accessible for type \'Expr\' using \'k = ", 59);
STRING_LITERAL(TM__egaGbf9cvcvVfE5PvoKJgvA_53, "field \'callfunc\' is not accessible for type \'Expr\' using \'k = ", 62);
STRING_LITERAL(TM__egaGbf9cvcvVfE5PvoKJgvA_57, "field \'callargs\' is not accessible for type \'Expr\' using \'k = ", 62);
STRING_LITERAL(TM__egaGbf9cvcvVfE5PvoKJgvA_58, ", ", 2);
STRING_LITERAL(TM__egaGbf9cvcvVfE5PvoKJgvA_59, "{", 1);
STRING_LITERAL(TM__egaGbf9cvcvVfE5PvoKJgvA_60, "field \'arr\' is not accessible for type \'Expr\' using \'k = ", 57);
STRING_LITERAL(TM__egaGbf9cvcvVfE5PvoKJgvA_61, "}", 1);
STRING_LITERAL(TM__egaGbf9cvcvVfE5PvoKJgvA_62, "<backend>", 9);
extern TFrame* framePtr__system_2566;
extern TFrame* framePtr__system_2566;
extern TFrame* framePtr__system_2566;
extern TFrame* framePtr__system_2566;
extern TFrame* framePtr__system_2566;
extern TFrame* framePtr__system_2566;
static N_NIMCALL(void, Marker_tySequence__xkcxUtflRxy5Nb0qaCHLZQ)(void* p, NI op) {
	tySequence__xkcxUtflRxy5Nb0qaCHLZQ* a;
	NI T1_;
	a = (tySequence__xkcxUtflRxy5Nb0qaCHLZQ*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < (a ? a->Sup.len : 0); T1_++) {
	nimGCvisit((void*)a->data[T1_], op);
	}
}
static N_NIMCALL(void, Marker_tySequence__5Ea4hthuw6lQuV4Ge38uDA)(void* p, NI op) {
	tySequence__5Ea4hthuw6lQuV4Ge38uDA* a;
	NI T1_;
	a = (tySequence__5Ea4hthuw6lQuV4Ge38uDA*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < (a ? a->Sup.len : 0); T1_++) {
	nimGCvisit((void*)a->data[T1_], op);
	}
}
static N_NIMCALL(void, Marker_tyRef__A0r19bnoIYBiAGuW7tYi0BA)(void* p, NI op) {
	tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ* a;
	a = (tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ*)p;
	nimGCvisit((void*)(*a).ty, op);
	switch ((*a).k) {
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 5):
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 19):
	nimGCvisit((void*)(*a)._k_1.voidexpr, op);
	break;
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 0):
	nimGCvisit((void*)(*a)._k_2.lhs, op);
	nimGCvisit((void*)(*a)._k_2.rhs, op);
	break;
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 1):
	nimGCvisit((void*)(*a)._k_3.uoperand, op);
	break;
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 2):
	nimGCvisit((void*)(*a)._k_4.poperand, op);
	break;
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 3):
	break;
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 4):
	break;
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 15):
	nimGCvisit((void*)(*a)._k_7.str, op);
	break;
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 6):
	nimGCvisit((void*)(*a)._k_8.sval, op);
	break;
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 12):
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 13):
	nimGCvisit((void*)(*a)._k_9.arr, op);
	break;
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 7):
	nimGCvisit((void*)(*a)._k_10.cond, op);
	nimGCvisit((void*)(*a)._k_10.cleft, op);
	nimGCvisit((void*)(*a)._k_10.cright, op);
	break;
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 8):
	nimGCvisit((void*)(*a)._k_11.castval, op);
	break;
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 9):
	nimGCvisit((void*)(*a)._k_12.callfunc, op);
	nimGCvisit((void*)(*a)._k_12.callargs, op);
	break;
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 10):
	nimGCvisit((void*)(*a)._k_13.left, op);
	nimGCvisit((void*)(*a)._k_13.right, op);
	break;
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 17):
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 18):
	nimGCvisit((void*)(*a)._k_14.obj, op);
	break;
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 14):
	break;
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 11):
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 16):
	break;
	} 
}
static N_NIMCALL(void, Marker_tySequence__sCWjRzukJ9amxY1VYtECwiw)(void* p, NI op) {
	tySequence__sCWjRzukJ9amxY1VYtECwiw* a;
	NI T1_;
	a = (tySequence__sCWjRzukJ9amxY1VYtECwiw*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < (a ? a->Sup.len : 0); T1_++) {
	nimGCvisit((void*)a->data[T1_].Field0, op);
	nimGCvisit((void*)a->data[T1_].Field1, op);
	nimGCvisit((void*)a->data[T1_].Field2, op);
	}
}
static N_NIMCALL(void, Marker_tyRef__5KgliZANPtggDh8VWtfw3Q)(void* p, NI op) {
	tyObject_StmtcolonObjectType___D3ZZSzbHHz9aqVhgDX6uEAA* a;
	a = (tyObject_StmtcolonObjectType___D3ZZSzbHHz9aqVhgDX6uEAA*)p;
	switch ((*a).k) {
	case ((tyEnum_StmtKind__wYBYg9bKbICo3tyQx0kTk1w) 18):
	nimGCvisit((void*)(*a)._k_1.funcname, op);
	nimGCvisit((void*)(*a)._k_1.functy, op);
	nimGCvisit((void*)(*a)._k_1.funcbody, op);
	break;
	case ((tyEnum_StmtKind__wYBYg9bKbICo3tyQx0kTk1w) 14):
	nimGCvisit((void*)(*a)._k_2.asms, op);
	break;
	case ((tyEnum_StmtKind__wYBYg9bKbICo3tyQx0kTk1w) 1):
	nimGCvisit((void*)(*a)._k_3.stmts, op);
	break;
	case ((tyEnum_StmtKind__wYBYg9bKbICo3tyQx0kTk1w) 16):
	nimGCvisit((void*)(*a)._k_4.default_stmt, op);
	break;
	case ((tyEnum_StmtKind__wYBYg9bKbICo3tyQx0kTk1w) 17):
	nimGCvisit((void*)(*a)._k_5.case_expr, op);
	nimGCvisit((void*)(*a)._k_5.case_stmt, op);
	break;
	case ((tyEnum_StmtKind__wYBYg9bKbICo3tyQx0kTk1w) 4):
	case ((tyEnum_StmtKind__wYBYg9bKbICo3tyQx0kTk1w) 3):
	case ((tyEnum_StmtKind__wYBYg9bKbICo3tyQx0kTk1w) 0):
	break;
	case ((tyEnum_StmtKind__wYBYg9bKbICo3tyQx0kTk1w) 6):
	case ((tyEnum_StmtKind__wYBYg9bKbICo3tyQx0kTk1w) 5):
	nimGCvisit((void*)(*a)._k_7.exprbody, op);
	break;
	case ((tyEnum_StmtKind__wYBYg9bKbICo3tyQx0kTk1w) 2):
	nimGCvisit((void*)(*a)._k_8.location, op);
	break;
	case ((tyEnum_StmtKind__wYBYg9bKbICo3tyQx0kTk1w) 7):
	nimGCvisit((void*)(*a)._k_9.label, op);
	nimGCvisit((void*)(*a)._k_9.labledstmt, op);
	break;
	case ((tyEnum_StmtKind__wYBYg9bKbICo3tyQx0kTk1w) 8):
	nimGCvisit((void*)(*a)._k_10.iftest, op);
	nimGCvisit((void*)(*a)._k_10.ifbody, op);
	nimGCvisit((void*)(*a)._k_10.elsebody, op);
	break;
	case ((tyEnum_StmtKind__wYBYg9bKbICo3tyQx0kTk1w) 9):
	case ((tyEnum_StmtKind__wYBYg9bKbICo3tyQx0kTk1w) 10):
	case ((tyEnum_StmtKind__wYBYg9bKbICo3tyQx0kTk1w) 12):
	nimGCvisit((void*)(*a)._k_11.test, op);
	nimGCvisit((void*)(*a)._k_11.body, op);
	break;
	case ((tyEnum_StmtKind__wYBYg9bKbICo3tyQx0kTk1w) 11):
	nimGCvisit((void*)(*a)._k_12.forinit, op);
	nimGCvisit((void*)(*a)._k_12.forcond, op);
	nimGCvisit((void*)(*a)._k_12.forincl, op);
	nimGCvisit((void*)(*a)._k_12.forbody, op);
	break;
	case ((tyEnum_StmtKind__wYBYg9bKbICo3tyQx0kTk1w) 19):
	nimGCvisit((void*)(*a)._k_13.var1name, op);
	nimGCvisit((void*)(*a)._k_13.var1type, op);
	break;
	case ((tyEnum_StmtKind__wYBYg9bKbICo3tyQx0kTk1w) 15):
	nimGCvisit((void*)(*a)._k_14.vars, op);
	break;
	case ((tyEnum_StmtKind__wYBYg9bKbICo3tyQx0kTk1w) 13):
	nimGCvisit((void*)(*a)._k_15.decl, op);
	break;
	} 
}
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}
static N_INLINE(void, copyMem__system_1727)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	{
		if (!!((src == ((NimStringDesc*) NIM_NIL)))) goto LA3_;
		copyMem__system_1727(((void*) ((&(*dest).data[(*dest).Sup.len]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
		(*dest).Sup.len += (*src).Sup.len;
	}
	LA3_: ;
}
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[(*dest).Sup.len] = c;
	(*dest).data[(NI)((*dest).Sup.len + ((NI) 1))] = 0;
	(*dest).Sup.len += ((NI) 1);
}
static N_INLINE(void, nimFrame)(TFrame* s) {
	{
		if (!(framePtr__system_2566 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s).calldepth = ((NI16) 0);
	}
	goto LA1_;
	LA3_: ;
	{
		(*s).calldepth = (NI16)((*framePtr__system_2566).calldepth + ((NI16) 1));
	}
	LA1_: ;
	(*s).prev = framePtr__system_2566;
	framePtr__system_2566 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;
		callDepthLimitReached__system_2999();
	}
	LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_2566 = (*framePtr__system_2566).prev;
}
static N_INLINE(tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ*, X5BX5D___ast_246)(tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ** s, NI sLen_0, NI i) {
	tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ* result;
	NI TM__egaGbf9cvcvVfE5PvoKJgvA_56;
	nimfr_("[]", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system.nim");
	result = NIM_NIL;
	nimln_(2642, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system.nim");
	if (nimSubInt(sLen_0, i, &TM__egaGbf9cvcvVfE5PvoKJgvA_56)) { raiseOverflow(); };
	if ((NI)(TM__egaGbf9cvcvVfE5PvoKJgvA_56) < 0 || (NI)(TM__egaGbf9cvcvVfE5PvoKJgvA_56) >= sLen_0){ raiseIndexError2((NI)(TM__egaGbf9cvcvVfE5PvoKJgvA_56),sLen_0-1); }
	result = s[(NI)(TM__egaGbf9cvcvVfE5PvoKJgvA_56)];
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, joinShow__ast_229)(tySequence__5Ea4hthuw6lQuV4Ge38uDA* a, NimStringDesc* c) {
	NimStringDesc* result;
	tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ* T11_;
	NimStringDesc* T12_;
	nimfr_("joinShow", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\ast.nim");
{	result = NIM_NIL;
	nimln_(134, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\ast.nim");
	{
		NI T3_;
		T3_ = (a ? a->Sup.len : 0);
		if (!(T3_ == ((NI) 0))) goto LA4_;
		nimln_(135, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\ast.nim");
		result = ((NimStringDesc*) NIM_NIL);
		goto BeforeRet_;
	}
	LA4_: ;
	{
		NI i;
		NI colontmp_;
		NI T7_;
		NI TM__egaGbf9cvcvVfE5PvoKJgvA_54;
		NI i_2;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(136, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\ast.nim");
		T7_ = (a ? a->Sup.len : 0);
		if (nimSubInt(T7_, ((NI) 1), &TM__egaGbf9cvcvVfE5PvoKJgvA_54)) { raiseOverflow(); };
		colontmp_ = (NI)(TM__egaGbf9cvcvVfE5PvoKJgvA_54);
		nimln_(119, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\iterators_1.nim");
		i_2 = ((NI) 0);
		{
			nimln_(120, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\iterators_1.nim");
			while (1) {
				NimStringDesc* T10_;
				NI TM__egaGbf9cvcvVfE5PvoKJgvA_55;
				if (!(i_2 < colontmp_)) goto LA9;
				nimln_(136, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\ast.nim");
				i = i_2;
				nimln_(137, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\ast.nim");
				if (i < 0 || i >= (a ? a->Sup.len : 0)){ raiseIndexError2(i,(a ? a->Sup.len : 0)-1); }
				T10_ = NIM_NIL;
				T10_ = dollar___ast_113(a->data[i]);
				result = resizeString(result, (T10_ ? T10_->Sup.len : 0) + 0);
appendString(result, T10_);
				nimln_(136, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\ast.nim");
				result = resizeString(result, (c ? c->Sup.len : 0) + 0);
appendString(result, c);
				nimln_(122, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\iterators_1.nim");
				if (nimAddInt(i_2, ((NI) 1), &TM__egaGbf9cvcvVfE5PvoKJgvA_55)) { raiseOverflow(); };
				i_2 = (NI)(TM__egaGbf9cvcvVfE5PvoKJgvA_55);
			} LA9: ;
		}
	}
	nimln_(139, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\ast.nim");
	T11_ = NIM_NIL;
	T11_ = X5BX5D___ast_246(a->data, (a ? a->Sup.len : 0), ((NI) 1));
	T12_ = NIM_NIL;
	T12_ = dollar___ast_113(T11_);
	result = resizeString(result, (T12_ ? T12_->Sup.len : 0) + 0);
appendString(result, T12_);
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar___ast_113)(tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ* e) {
	NimStringDesc* result;
	nimfr_("$", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\ast.nim");
{	result = NIM_NIL;
	nimln_(194, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\ast.nim");
	{
		if (!(e == ((tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ*) NIM_NIL))) goto LA3_;
		nimln_(195, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\ast.nim");
		result = copyString(((NimStringDesc*) &TM__egaGbf9cvcvVfE5PvoKJgvA_25));
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(196, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\ast.nim");
	switch ((*e).k) {
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 16):
	{
		result = copyString(((NimStringDesc*) &TM__egaGbf9cvcvVfE5PvoKJgvA_26));
	}
	break;
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 5):
	{
		NimStringDesc* T7_;
		NimStringDesc* T8_;
		nimln_(200, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\ast.nim");
		T7_ = NIM_NIL;
		if (!(((524320 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 		{ raiseFieldError2(((NimStringDesc*) &TM__egaGbf9cvcvVfE5PvoKJgvA_28), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
		T8_ = NIM_NIL;
		T8_ = dollar___ast_113((*e)._k_1.voidexpr);
		T7_ = rawNewString((T8_ ? T8_->Sup.len : 0) + 6);
appendString(T7_, ((NimStringDesc*) &TM__egaGbf9cvcvVfE5PvoKJgvA_27));
appendString(T7_, T8_);
		result = T7_;
	}
	break;
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 19):
	{
		NimStringDesc* T10_;
		NimStringDesc* T11_;
		nimln_(202, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\ast.nim");
		T10_ = NIM_NIL;
		if (!(((524320 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 		{ raiseFieldError2(((NimStringDesc*) &TM__egaGbf9cvcvVfE5PvoKJgvA_28), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
		T11_ = NIM_NIL;
		T11_ = dollar___ast_113((*e)._k_1.voidexpr);
		T10_ = rawNewString((T11_ ? T11_->Sup.len : 0) + 3);
appendString(T10_, ((NimStringDesc*) &TM__egaGbf9cvcvVfE5PvoKJgvA_29));
appendString(T10_, T11_);
appendString(T10_, ((NimStringDesc*) &TM__egaGbf9cvcvVfE5PvoKJgvA_30));
		result = T10_;
	}
	break;
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 11):
	{
		result = copyString(((NimStringDesc*) &TM__egaGbf9cvcvVfE5PvoKJgvA_31));
	}
	break;
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 13):
	{
		result = copyString(((NimStringDesc*) &TM__egaGbf9cvcvVfE5PvoKJgvA_32));
	}
	break;
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 18):
	{
		NimStringDesc* T15_;
		NimStringDesc* T16_;
		NimStringDesc* T17_;
		nimln_(208, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\ast.nim");
		T15_ = NIM_NIL;
		if (!(((393216 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 		{ raiseFieldError2(((NimStringDesc*) &TM__egaGbf9cvcvVfE5PvoKJgvA_33), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
		T16_ = NIM_NIL;
		T16_ = dollar___ast_113((*e)._k_14.obj);
		if (!(((393216 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 		{ raiseFieldError2(((NimStringDesc*) &TM__egaGbf9cvcvVfE5PvoKJgvA_34), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
		T17_ = NIM_NIL;
		T17_ = dollar___systemZdollars_3((*e)._k_14.idx);
		T15_ = rawNewString((T16_ ? T16_->Sup.len : 0) + (T17_ ? T17_->Sup.len : 0) + 1);
appendString(T15_, T16_);
appendChar(T15_, 46);
appendString(T15_, T17_);
		result = T15_;
	}
	break;
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 17):
	{
		NimStringDesc* T19_;
		NimStringDesc* T20_;
		NimStringDesc* T21_;
		nimln_(210, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\ast.nim");
		T19_ = NIM_NIL;
		if (!(((393216 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 		{ raiseFieldError2(((NimStringDesc*) &TM__egaGbf9cvcvVfE5PvoKJgvA_33), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
		T20_ = NIM_NIL;
		T20_ = dollar___ast_113((*e)._k_14.obj);
		if (!(((393216 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 		{ raiseFieldError2(((NimStringDesc*) &TM__egaGbf9cvcvVfE5PvoKJgvA_34), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
		T21_ = NIM_NIL;
		T21_ = dollar___systemZdollars_3((*e)._k_14.idx);
		T19_ = rawNewString((T20_ ? T20_->Sup.len : 0) + (T21_ ? T21_->Sup.len : 0) + 2);
appendString(T19_, T20_);
appendString(T19_, ((NimStringDesc*) &TM__egaGbf9cvcvVfE5PvoKJgvA_35));
appendString(T19_, T21_);
		result = T19_;
	}
	break;
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 15):
	{
		nimln_(212, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\ast.nim");
		if (!(((32768 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 		{ raiseFieldError2(((NimStringDesc*) &TM__egaGbf9cvcvVfE5PvoKJgvA_36), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
		result = reprStr((*e)._k_7.str);
	}
	break;
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 0):
	{
		NimStringDesc* T24_;
		NimStringDesc* T25_;
		NimStringDesc* T26_;
		NimStringDesc* T27_;
		nimln_(214, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\ast.nim");
		T24_ = NIM_NIL;
		if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 		{ raiseFieldError2(((NimStringDesc*) &TM__egaGbf9cvcvVfE5PvoKJgvA_37), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
		T25_ = NIM_NIL;
		T25_ = dollar___ast_113((*e)._k_2.lhs);
		if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 		{ raiseFieldError2(((NimStringDesc*) &TM__egaGbf9cvcvVfE5PvoKJgvA_38), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
		T26_ = NIM_NIL;
		T26_ = dollar___operators_88((*e)._k_2.bop);
		if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 		{ raiseFieldError2(((NimStringDesc*) &TM__egaGbf9cvcvVfE5PvoKJgvA_39), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
		T27_ = NIM_NIL;
		T27_ = dollar___ast_113((*e)._k_2.rhs);
		T24_ = rawNewString((T25_ ? T25_->Sup.len : 0) + (T26_ ? T26_->Sup.len : 0) + (T27_ ? T27_->Sup.len : 0) + 4);
appendChar(T24_, 40);
appendString(T24_, T25_);
appendChar(T24_, 32);
appendString(T24_, T26_);
appendChar(T24_, 32);
appendString(T24_, T27_);
appendChar(T24_, 41);
		result = T24_;
	}
	break;
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 2):
	{
		NimStringDesc* T29_;
		NimStringDesc* T30_;
		nimln_(216, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\ast.nim");
		T29_ = NIM_NIL;
		if (!(((4 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 		{ raiseFieldError2(((NimStringDesc*) &TM__egaGbf9cvcvVfE5PvoKJgvA_40), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
		T30_ = NIM_NIL;
		T30_ = dollar___ast_113((*e)._k_4.poperand);
		if (!(((4 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 		{ raiseFieldError2(((NimStringDesc*) &TM__egaGbf9cvcvVfE5PvoKJgvA_41), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
		T29_ = rawNewString((T30_ ? T30_->Sup.len : 0) + (reprEnum((NI)(*e)._k_4.pop, (&NTIpostfixop__jgPOCDkMnYUH9ajYVCnMILw_)) ? reprEnum((NI)(*e)._k_4.pop, (&NTIpostfixop__jgPOCDkMnYUH9ajYVCnMILw_))->Sup.len : 0) + 0);
appendString(T29_, T30_);
appendString(T29_, reprEnum((NI)(*e)._k_4.pop, (&NTIpostfixop__jgPOCDkMnYUH9ajYVCnMILw_)));
		result = T29_;
	}
	break;
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 1):
	{
		NimStringDesc* T32_;
		NimStringDesc* T33_;
		NimStringDesc* T34_;
		nimln_(218, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\ast.nim");
		T32_ = NIM_NIL;
		if (!(((2 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 		{ raiseFieldError2(((NimStringDesc*) &TM__egaGbf9cvcvVfE5PvoKJgvA_42), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
		T33_ = NIM_NIL;
		T33_ = dollar___operators_85((*e)._k_3.uop);
		if (!(((2 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 		{ raiseFieldError2(((NimStringDesc*) &TM__egaGbf9cvcvVfE5PvoKJgvA_43), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
		T34_ = NIM_NIL;
		T34_ = dollar___ast_113((*e)._k_3.uoperand);
		T32_ = rawNewString((T33_ ? T33_->Sup.len : 0) + (T34_ ? T34_->Sup.len : 0) + 0);
appendString(T32_, T33_);
appendString(T32_, T34_);
		result = T32_;
	}
	break;
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 3):
	{
		nimln_(220, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\ast.nim");
		if (!(((8 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 		{ raiseFieldError2(((NimStringDesc*) &TM__egaGbf9cvcvVfE5PvoKJgvA_44), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
		result = dollar___systemZdollars_3((*e)._k_5.ival);
	}
	break;
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 4):
	{
		nimln_(222, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\ast.nim");
		if (!(((16 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 		{ raiseFieldError2(((NimStringDesc*) &TM__egaGbf9cvcvVfE5PvoKJgvA_45), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
		result = dollar___system_3154((*e)._k_6.fval);
	}
	break;
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 6):
	{
		if (!(((64 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 		{ raiseFieldError2(((NimStringDesc*) &TM__egaGbf9cvcvVfE5PvoKJgvA_46), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
		result = copyString((*e)._k_8.sval);
	}
	break;
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 7):
	{
		NimStringDesc* T39_;
		NimStringDesc* T40_;
		NimStringDesc* T41_;
		NimStringDesc* T42_;
		nimln_(226, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\ast.nim");
		T39_ = NIM_NIL;
		if (!(((128 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 		{ raiseFieldError2(((NimStringDesc*) &TM__egaGbf9cvcvVfE5PvoKJgvA_47), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
		T40_ = NIM_NIL;
		T40_ = dollar___ast_113((*e)._k_10.cond);
		if (!(((128 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 		{ raiseFieldError2(((NimStringDesc*) &TM__egaGbf9cvcvVfE5PvoKJgvA_48), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
		T41_ = NIM_NIL;
		T41_ = dollar___ast_113((*e)._k_10.cleft);
		if (!(((128 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 		{ raiseFieldError2(((NimStringDesc*) &TM__egaGbf9cvcvVfE5PvoKJgvA_49), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
		T42_ = NIM_NIL;
		T42_ = dollar___ast_113((*e)._k_10.cright);
		T39_ = rawNewString((T40_ ? T40_->Sup.len : 0) + (T41_ ? T41_->Sup.len : 0) + (T42_ ? T42_->Sup.len : 0) + 2);
appendString(T39_, T40_);
appendChar(T39_, 63);
appendString(T39_, T41_);
appendChar(T39_, 58);
appendString(T39_, T42_);
		result = T39_;
	}
	break;
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 8):
	{
		NimStringDesc* T44_;
		NimStringDesc* T45_;
		NimStringDesc* T46_;
		nimln_(228, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\ast.nim");
		T44_ = NIM_NIL;
		T45_ = NIM_NIL;
		T45_ = dollar___types_88((*e).ty, ((NI) 0));
		if (!(((256 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 		{ raiseFieldError2(((NimStringDesc*) &TM__egaGbf9cvcvVfE5PvoKJgvA_50), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
		T46_ = NIM_NIL;
		T46_ = dollar___ast_113((*e)._k_11.castval);
		T44_ = rawNewString((T45_ ? T45_->Sup.len : 0) + (T46_ ? T46_->Sup.len : 0) + 2);
appendChar(T44_, 40);
appendString(T44_, T45_);
appendChar(T44_, 41);
appendString(T44_, T46_);
		result = T44_;
	}
	break;
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 10):
	{
		NimStringDesc* T48_;
		NimStringDesc* T49_;
		NimStringDesc* T50_;
		nimln_(230, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\ast.nim");
		T48_ = NIM_NIL;
		if (!(((1024 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 		{ raiseFieldError2(((NimStringDesc*) &TM__egaGbf9cvcvVfE5PvoKJgvA_51), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
		T49_ = NIM_NIL;
		T49_ = dollar___ast_113((*e)._k_13.left);
		if (!(((1024 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 		{ raiseFieldError2(((NimStringDesc*) &TM__egaGbf9cvcvVfE5PvoKJgvA_52), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
		T50_ = NIM_NIL;
		T50_ = dollar___ast_113((*e)._k_13.right);
		T48_ = rawNewString((T49_ ? T49_->Sup.len : 0) + (T50_ ? T50_->Sup.len : 0) + 2);
appendString(T48_, T49_);
appendChar(T48_, 91);
appendString(T48_, T50_);
appendChar(T48_, 93);
		result = T48_;
	}
	break;
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 9):
	{
		NimStringDesc* T52_;
		NimStringDesc* T53_;
		NimStringDesc* T54_;
		nimln_(232, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\ast.nim");
		T52_ = NIM_NIL;
		if (!(((512 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 		{ raiseFieldError2(((NimStringDesc*) &TM__egaGbf9cvcvVfE5PvoKJgvA_53), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
		T53_ = NIM_NIL;
		T53_ = dollar___ast_113((*e)._k_12.callfunc);
		if (!(((512 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 		{ raiseFieldError2(((NimStringDesc*) &TM__egaGbf9cvcvVfE5PvoKJgvA_57), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
		T54_ = NIM_NIL;
		T54_ = joinShow__ast_229((*e)._k_12.callargs, ((NimStringDesc*) &TM__egaGbf9cvcvVfE5PvoKJgvA_58));
		T52_ = rawNewString((T53_ ? T53_->Sup.len : 0) + (T54_ ? T54_->Sup.len : 0) + 2);
appendString(T52_, T53_);
appendChar(T52_, 40);
appendString(T52_, T54_);
appendChar(T52_, 41);
		result = T52_;
	}
	break;
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 12):
	{
		NimStringDesc* T56_;
		NimStringDesc* T57_;
		nimln_(234, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\ast.nim");
		T56_ = NIM_NIL;
		if (!(((12288 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 		{ raiseFieldError2(((NimStringDesc*) &TM__egaGbf9cvcvVfE5PvoKJgvA_60), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
		T57_ = NIM_NIL;
		T57_ = dollar___ast_282((*e)._k_9.arr);
		T56_ = rawNewString((T57_ ? T57_->Sup.len : 0) + 2);
appendString(T56_, ((NimStringDesc*) &TM__egaGbf9cvcvVfE5PvoKJgvA_59));
appendString(T56_, T57_);
appendString(T56_, ((NimStringDesc*) &TM__egaGbf9cvcvVfE5PvoKJgvA_61));
		result = T56_;
	}
	break;
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 14):
	{
		result = copyString(((NimStringDesc*) &TM__egaGbf9cvcvVfE5PvoKJgvA_62));
	}
	break;
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isConstant__ast_339)(tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ* e) {
	NIM_BOOL result;
	nimfr_("isConstant", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\ast.nim");
	result = (NIM_BOOL)0;
	nimln_(239, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\ast.nim");
	nimln_(240, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\ast.nim");
	switch ((*e).k) {
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 5):
	{
		result = NIM_FALSE;
	}
	break;
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 19):
	{
		result = NIM_TRUE;
	}
	break;
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 0):
	{
		NIM_BOOL T4_;
		nimln_(246, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\ast.nim");
		T4_ = (NIM_BOOL)0;
		if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 		{ raiseFieldError2(((NimStringDesc*) &TM__egaGbf9cvcvVfE5PvoKJgvA_37), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
		T4_ = isConstant__ast_339((*e)._k_2.lhs);
		if (!(T4_)) goto LA5_;
		if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 		{ raiseFieldError2(((NimStringDesc*) &TM__egaGbf9cvcvVfE5PvoKJgvA_39), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
		T4_ = isConstant__ast_339((*e)._k_2.rhs);
		LA5_: ;
		result = T4_;
	}
	break;
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 1):
	{
		nimln_(248, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\ast.nim");
		if (!(((2 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 		{ raiseFieldError2(((NimStringDesc*) &TM__egaGbf9cvcvVfE5PvoKJgvA_43), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
		result = isConstant__ast_339((*e)._k_3.uoperand);
	}
	break;
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 2):
	{
		result = NIM_FALSE;
	}
	break;
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 3):
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 4):
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 15):
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 6):
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 12):
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 13):
	{
		result = NIM_TRUE;
	}
	break;
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 7):
	{
		NIM_BOOL T10_;
		NIM_BOOL T11_;
		nimln_(254, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\ast.nim");
		T10_ = (NIM_BOOL)0;
		T11_ = (NIM_BOOL)0;
		if (!(((128 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 		{ raiseFieldError2(((NimStringDesc*) &TM__egaGbf9cvcvVfE5PvoKJgvA_47), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
		T11_ = isConstant__ast_339((*e)._k_10.cond);
		if (!(T11_)) goto LA12_;
		if (!(((128 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 		{ raiseFieldError2(((NimStringDesc*) &TM__egaGbf9cvcvVfE5PvoKJgvA_48), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
		T11_ = isConstant__ast_339((*e)._k_10.cleft);
		LA12_: ;
		T10_ = T11_;
		if (!(T10_)) goto LA13_;
		if (!(((128 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 		{ raiseFieldError2(((NimStringDesc*) &TM__egaGbf9cvcvVfE5PvoKJgvA_49), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
		T10_ = isConstant__ast_339((*e)._k_10.cright);
		LA13_: ;
		result = T10_;
	}
	break;
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 8):
	{
		result = NIM_TRUE;
	}
	break;
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 9):
	{
		result = NIM_FALSE;
	}
	break;
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 10):
	{
		result = NIM_FALSE;
	}
	break;
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 18):
	{
		nimln_(262, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\ast.nim");
		if (!(((393216 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 		{ raiseFieldError2(((NimStringDesc*) &TM__egaGbf9cvcvVfE5PvoKJgvA_33), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
		result = isConstant__ast_339((*e)._k_14.obj);
	}
	break;
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 17):
	{
		result = NIM_FALSE;
	}
	break;
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 14):
	{
		result = NIM_FALSE;
	}
	break;
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 11):
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 16):
	{
		result = NIM_TRUE;
	}
	break;
	}
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, unknown_astDatInit000)(void) {
static TNimNode* TM__egaGbf9cvcvVfE5PvoKJgvA_2_20[20];
NI TM__egaGbf9cvcvVfE5PvoKJgvA_4;
static char* NIM_CONST TM__egaGbf9cvcvVfE5PvoKJgvA_3[20] = {
"SSemicolon", 
"SCompound", 
"SGoto", 
"SContinue", 
"SBreak", 
"SReturn", 
"SExpr", 
"SLabled", 
"SIf", 
"SDoWhile", 
"SWhile", 
"SFor", 
"SSwitch", 
"SDeclOnly", 
"SAsm", 
"SVarDecl", 
"SDefault", 
"SCase", 
"SFunction", 
"SVarDecl1"};
static TNimNode* TM__egaGbf9cvcvVfE5PvoKJgvA_5_3[3];
static TNimNode* TM__egaGbf9cvcvVfE5PvoKJgvA_6_2[2];
static TNimNode* TM__egaGbf9cvcvVfE5PvoKJgvA_7_2[2];
static TNimNode* TM__egaGbf9cvcvVfE5PvoKJgvA_8_20[20];
NI TM__egaGbf9cvcvVfE5PvoKJgvA_10;
static char* NIM_CONST TM__egaGbf9cvcvVfE5PvoKJgvA_9[20] = {
"EBin", 
"EUnary", 
"EPostFix", 
"EIntLit", 
"EFloatLit", 
"EVoid", 
"EVar", 
"ECondition", 
"ECast", 
"ECall", 
"ESubscript", 
"EDefault", 
"EArray", 
"EStruct", 
"EBackend", 
"EString", 
"EUndef", 
"EPointerMemberAccess", 
"EMemberAccess", 
"ArrToAddress"};
static TNimNode* TM__egaGbf9cvcvVfE5PvoKJgvA_11_3[3];
static TNimNode* TM__egaGbf9cvcvVfE5PvoKJgvA_12_2[2];
static TNimNode* TM__egaGbf9cvcvVfE5PvoKJgvA_13_2[2];
static TNimNode* TM__egaGbf9cvcvVfE5PvoKJgvA_14_3[3];
static TNimNode* TM__egaGbf9cvcvVfE5PvoKJgvA_15_2[2];
static TNimNode* TM__egaGbf9cvcvVfE5PvoKJgvA_16_2[2];
static TNimNode* TM__egaGbf9cvcvVfE5PvoKJgvA_17_2[2];
static TNimNode* TM__egaGbf9cvcvVfE5PvoKJgvA_18_2[2];
static TNimNode* TM__egaGbf9cvcvVfE5PvoKJgvA_19_2[2];
static TNimNode* TM__egaGbf9cvcvVfE5PvoKJgvA_20_3[3];
static TNimNode* TM__egaGbf9cvcvVfE5PvoKJgvA_21_2[2];
static TNimNode* TM__egaGbf9cvcvVfE5PvoKJgvA_22_4[4];
static TNimNode* TM__egaGbf9cvcvVfE5PvoKJgvA_23_2[2];
static TNimNode* TM__egaGbf9cvcvVfE5PvoKJgvA_24_3[3];
static TNimNode TM__egaGbf9cvcvVfE5PvoKJgvA_0[117];
NTIstmt58objecttype__D3ZZSzbHHz9aqVhgDX6uEAA_.size = sizeof(tyObject_StmtcolonObjectType___D3ZZSzbHHz9aqVhgDX6uEAA);
NTIstmt58objecttype__D3ZZSzbHHz9aqVhgDX6uEAA_.align = NIM_ALIGNOF(tyObject_StmtcolonObjectType___D3ZZSzbHHz9aqVhgDX6uEAA);
NTIstmt58objecttype__D3ZZSzbHHz9aqVhgDX6uEAA_.kind = 18;
NTIstmt58objecttype__D3ZZSzbHHz9aqVhgDX6uEAA_.base = 0;
NTIstmtkind__wYBYg9bKbICo3tyQx0kTk1w_.size = sizeof(tyEnum_StmtKind__wYBYg9bKbICo3tyQx0kTk1w);
NTIstmtkind__wYBYg9bKbICo3tyQx0kTk1w_.align = NIM_ALIGNOF(tyEnum_StmtKind__wYBYg9bKbICo3tyQx0kTk1w);
NTIstmtkind__wYBYg9bKbICo3tyQx0kTk1w_.kind = 14;
NTIstmtkind__wYBYg9bKbICo3tyQx0kTk1w_.base = 0;
NTIstmtkind__wYBYg9bKbICo3tyQx0kTk1w_.flags = 3;
for (TM__egaGbf9cvcvVfE5PvoKJgvA_4 = 0; TM__egaGbf9cvcvVfE5PvoKJgvA_4 < 20; TM__egaGbf9cvcvVfE5PvoKJgvA_4++) {
TM__egaGbf9cvcvVfE5PvoKJgvA_0[TM__egaGbf9cvcvVfE5PvoKJgvA_4+1].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[TM__egaGbf9cvcvVfE5PvoKJgvA_4+1].offset = TM__egaGbf9cvcvVfE5PvoKJgvA_4;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[TM__egaGbf9cvcvVfE5PvoKJgvA_4+1].name = TM__egaGbf9cvcvVfE5PvoKJgvA_3[TM__egaGbf9cvcvVfE5PvoKJgvA_4];
TM__egaGbf9cvcvVfE5PvoKJgvA_2_20[TM__egaGbf9cvcvVfE5PvoKJgvA_4] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[TM__egaGbf9cvcvVfE5PvoKJgvA_4+1];
}
TM__egaGbf9cvcvVfE5PvoKJgvA_0[21].len = 20; TM__egaGbf9cvcvVfE5PvoKJgvA_0[21].kind = 2; TM__egaGbf9cvcvVfE5PvoKJgvA_0[21].sons = &TM__egaGbf9cvcvVfE5PvoKJgvA_2_20[0];
NTIstmtkind__wYBYg9bKbICo3tyQx0kTk1w_.node = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[21];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[0].kind = 3;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[0].offset = offsetof(tyObject_StmtcolonObjectType___D3ZZSzbHHz9aqVhgDX6uEAA, k);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[0].typ = (&NTIstmtkind__wYBYg9bKbICo3tyQx0kTk1w_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[0].name = "k";
TM__egaGbf9cvcvVfE5PvoKJgvA_0[0].sons = &NimDT___D3ZZSzbHHz9aqVhgDX6uEAA_k[0];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[0].len = 20;
TM__egaGbf9cvcvVfE5PvoKJgvA_5_3[0] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[23];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[23].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[23].offset = offsetof(tyObject_StmtcolonObjectType___D3ZZSzbHHz9aqVhgDX6uEAA, _k_1.funcname);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[23].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[23].name = "funcname";
TM__egaGbf9cvcvVfE5PvoKJgvA_5_3[1] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[24];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[24].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[24].offset = offsetof(tyObject_StmtcolonObjectType___D3ZZSzbHHz9aqVhgDX6uEAA, _k_1.functy);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[24].typ = (&NTIctype__9cf0EuNkYZeO83WITZYEetQ_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[24].name = "functy";
TM__egaGbf9cvcvVfE5PvoKJgvA_5_3[2] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[25];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[25].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[25].offset = offsetof(tyObject_StmtcolonObjectType___D3ZZSzbHHz9aqVhgDX6uEAA, _k_1.funcbody);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[25].typ = (&NTIstmt__5KgliZANPtggDh8VWtfw3Q_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[25].name = "funcbody";
TM__egaGbf9cvcvVfE5PvoKJgvA_0[22].len = 3; TM__egaGbf9cvcvVfE5PvoKJgvA_0[22].kind = 2; TM__egaGbf9cvcvVfE5PvoKJgvA_0[22].sons = &TM__egaGbf9cvcvVfE5PvoKJgvA_5_3[0];
NimDT___D3ZZSzbHHz9aqVhgDX6uEAA_k[18] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[22];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[26].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[26].offset = offsetof(tyObject_StmtcolonObjectType___D3ZZSzbHHz9aqVhgDX6uEAA, _k_2.asms);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[26].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[26].name = "asms";
NimDT___D3ZZSzbHHz9aqVhgDX6uEAA_k[14] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[26];
NTIstmtlist__xkcxUtflRxy5Nb0qaCHLZQ_.size = sizeof(tySequence__xkcxUtflRxy5Nb0qaCHLZQ*);
NTIstmtlist__xkcxUtflRxy5Nb0qaCHLZQ_.align = NIM_ALIGNOF(tySequence__xkcxUtflRxy5Nb0qaCHLZQ*);
NTIstmtlist__xkcxUtflRxy5Nb0qaCHLZQ_.kind = 24;
NTIstmtlist__xkcxUtflRxy5Nb0qaCHLZQ_.base = (&NTIstmt__5KgliZANPtggDh8VWtfw3Q_);
NTIstmtlist__xkcxUtflRxy5Nb0qaCHLZQ_.marker = Marker_tySequence__xkcxUtflRxy5Nb0qaCHLZQ;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[27].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[27].offset = offsetof(tyObject_StmtcolonObjectType___D3ZZSzbHHz9aqVhgDX6uEAA, _k_3.stmts);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[27].typ = (&NTIstmtlist__xkcxUtflRxy5Nb0qaCHLZQ_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[27].name = "stmts";
NimDT___D3ZZSzbHHz9aqVhgDX6uEAA_k[1] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[27];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[28].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[28].offset = offsetof(tyObject_StmtcolonObjectType___D3ZZSzbHHz9aqVhgDX6uEAA, _k_4.default_stmt);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[28].typ = (&NTIstmt__5KgliZANPtggDh8VWtfw3Q_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[28].name = "default_stmt";
NimDT___D3ZZSzbHHz9aqVhgDX6uEAA_k[16] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[28];
TM__egaGbf9cvcvVfE5PvoKJgvA_6_2[0] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[30];
NTIexpr58objecttype__eqRwdyQ9bUMO9bghkVuWSD9cQ_.size = sizeof(tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ);
NTIexpr58objecttype__eqRwdyQ9bUMO9bghkVuWSD9cQ_.align = NIM_ALIGNOF(tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ);
NTIexpr58objecttype__eqRwdyQ9bUMO9bghkVuWSD9cQ_.kind = 18;
NTIexpr58objecttype__eqRwdyQ9bUMO9bghkVuWSD9cQ_.base = 0;
TM__egaGbf9cvcvVfE5PvoKJgvA_7_2[0] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[32];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[32].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[32].offset = offsetof(tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ, ty);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[32].typ = (&NTIctype__9cf0EuNkYZeO83WITZYEetQ_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[32].name = "ty";
TM__egaGbf9cvcvVfE5PvoKJgvA_7_2[1] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[33];
NTIexprkind__kR6KxRhax5CY59atptiseeQ_.size = sizeof(tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ);
NTIexprkind__kR6KxRhax5CY59atptiseeQ_.align = NIM_ALIGNOF(tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ);
NTIexprkind__kR6KxRhax5CY59atptiseeQ_.kind = 14;
NTIexprkind__kR6KxRhax5CY59atptiseeQ_.base = 0;
NTIexprkind__kR6KxRhax5CY59atptiseeQ_.flags = 3;
for (TM__egaGbf9cvcvVfE5PvoKJgvA_10 = 0; TM__egaGbf9cvcvVfE5PvoKJgvA_10 < 20; TM__egaGbf9cvcvVfE5PvoKJgvA_10++) {
TM__egaGbf9cvcvVfE5PvoKJgvA_0[TM__egaGbf9cvcvVfE5PvoKJgvA_10+34].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[TM__egaGbf9cvcvVfE5PvoKJgvA_10+34].offset = TM__egaGbf9cvcvVfE5PvoKJgvA_10;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[TM__egaGbf9cvcvVfE5PvoKJgvA_10+34].name = TM__egaGbf9cvcvVfE5PvoKJgvA_9[TM__egaGbf9cvcvVfE5PvoKJgvA_10];
TM__egaGbf9cvcvVfE5PvoKJgvA_8_20[TM__egaGbf9cvcvVfE5PvoKJgvA_10] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[TM__egaGbf9cvcvVfE5PvoKJgvA_10+34];
}
TM__egaGbf9cvcvVfE5PvoKJgvA_0[54].len = 20; TM__egaGbf9cvcvVfE5PvoKJgvA_0[54].kind = 2; TM__egaGbf9cvcvVfE5PvoKJgvA_0[54].sons = &TM__egaGbf9cvcvVfE5PvoKJgvA_8_20[0];
NTIexprkind__kR6KxRhax5CY59atptiseeQ_.node = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[54];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[33].kind = 3;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[33].offset = offsetof(tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ, k);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[33].typ = (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[33].name = "k";
TM__egaGbf9cvcvVfE5PvoKJgvA_0[33].sons = &NimDT___eqRwdyQ9bUMO9bghkVuWSD9cQ_k[0];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[33].len = 20;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[55].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[55].offset = offsetof(tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ, _k_1.voidexpr);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[55].typ = (&NTIexpr__A0r19bnoIYBiAGuW7tYi0BA_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[55].name = "voidexpr";
NimDT___eqRwdyQ9bUMO9bghkVuWSD9cQ_k[5] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[55];
NimDT___eqRwdyQ9bUMO9bghkVuWSD9cQ_k[19] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[55];
TM__egaGbf9cvcvVfE5PvoKJgvA_11_3[0] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[57];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[57].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[57].offset = offsetof(tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ, _k_2.lhs);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[57].typ = (&NTIexpr__A0r19bnoIYBiAGuW7tYi0BA_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[57].name = "lhs";
TM__egaGbf9cvcvVfE5PvoKJgvA_11_3[1] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[58];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[58].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[58].offset = offsetof(tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ, _k_2.rhs);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[58].typ = (&NTIexpr__A0r19bnoIYBiAGuW7tYi0BA_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[58].name = "rhs";
TM__egaGbf9cvcvVfE5PvoKJgvA_11_3[2] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[59];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[59].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[59].offset = offsetof(tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ, _k_2.bop);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[59].typ = (&NTIbinop__fynptmmwPBA9aKeAoNUe1qA_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[59].name = "bop";
TM__egaGbf9cvcvVfE5PvoKJgvA_0[56].len = 3; TM__egaGbf9cvcvVfE5PvoKJgvA_0[56].kind = 2; TM__egaGbf9cvcvVfE5PvoKJgvA_0[56].sons = &TM__egaGbf9cvcvVfE5PvoKJgvA_11_3[0];
NimDT___eqRwdyQ9bUMO9bghkVuWSD9cQ_k[0] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[56];
TM__egaGbf9cvcvVfE5PvoKJgvA_12_2[0] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[61];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[61].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[61].offset = offsetof(tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ, _k_3.uop);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[61].typ = (&NTIunaryop__UBzoLjzsBr0iHTGRBtQ54w_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[61].name = "uop";
TM__egaGbf9cvcvVfE5PvoKJgvA_12_2[1] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[62];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[62].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[62].offset = offsetof(tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ, _k_3.uoperand);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[62].typ = (&NTIexpr__A0r19bnoIYBiAGuW7tYi0BA_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[62].name = "uoperand";
TM__egaGbf9cvcvVfE5PvoKJgvA_0[60].len = 2; TM__egaGbf9cvcvVfE5PvoKJgvA_0[60].kind = 2; TM__egaGbf9cvcvVfE5PvoKJgvA_0[60].sons = &TM__egaGbf9cvcvVfE5PvoKJgvA_12_2[0];
NimDT___eqRwdyQ9bUMO9bghkVuWSD9cQ_k[1] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[60];
TM__egaGbf9cvcvVfE5PvoKJgvA_13_2[0] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[64];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[64].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[64].offset = offsetof(tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ, _k_4.pop);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[64].typ = (&NTIpostfixop__jgPOCDkMnYUH9ajYVCnMILw_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[64].name = "pop";
TM__egaGbf9cvcvVfE5PvoKJgvA_13_2[1] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[65];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[65].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[65].offset = offsetof(tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ, _k_4.poperand);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[65].typ = (&NTIexpr__A0r19bnoIYBiAGuW7tYi0BA_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[65].name = "poperand";
TM__egaGbf9cvcvVfE5PvoKJgvA_0[63].len = 2; TM__egaGbf9cvcvVfE5PvoKJgvA_0[63].kind = 2; TM__egaGbf9cvcvVfE5PvoKJgvA_0[63].sons = &TM__egaGbf9cvcvVfE5PvoKJgvA_13_2[0];
NimDT___eqRwdyQ9bUMO9bghkVuWSD9cQ_k[2] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[63];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[66].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[66].offset = offsetof(tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ, _k_5.ival);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[66].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[66].name = "ival";
NimDT___eqRwdyQ9bUMO9bghkVuWSD9cQ_k[3] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[66];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[67].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[67].offset = offsetof(tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ, _k_6.fval);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[67].typ = (&NTIfloat__w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[67].name = "fval";
NimDT___eqRwdyQ9bUMO9bghkVuWSD9cQ_k[4] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[67];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[68].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[68].offset = offsetof(tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ, _k_7.str);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[68].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[68].name = "str";
NimDT___eqRwdyQ9bUMO9bghkVuWSD9cQ_k[15] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[68];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[69].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[69].offset = offsetof(tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ, _k_8.sval);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[69].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[69].name = "sval";
NimDT___eqRwdyQ9bUMO9bghkVuWSD9cQ_k[6] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[69];
NTIseqLexprT__5Ea4hthuw6lQuV4Ge38uDA_.size = sizeof(tySequence__5Ea4hthuw6lQuV4Ge38uDA*);
NTIseqLexprT__5Ea4hthuw6lQuV4Ge38uDA_.align = NIM_ALIGNOF(tySequence__5Ea4hthuw6lQuV4Ge38uDA*);
NTIseqLexprT__5Ea4hthuw6lQuV4Ge38uDA_.kind = 24;
NTIseqLexprT__5Ea4hthuw6lQuV4Ge38uDA_.base = (&NTIexpr__A0r19bnoIYBiAGuW7tYi0BA_);
NTIseqLexprT__5Ea4hthuw6lQuV4Ge38uDA_.marker = Marker_tySequence__5Ea4hthuw6lQuV4Ge38uDA;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[70].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[70].offset = offsetof(tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ, _k_9.arr);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[70].typ = (&NTIseqLexprT__5Ea4hthuw6lQuV4Ge38uDA_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[70].name = "arr";
NimDT___eqRwdyQ9bUMO9bghkVuWSD9cQ_k[12] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[70];
NimDT___eqRwdyQ9bUMO9bghkVuWSD9cQ_k[13] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[70];
TM__egaGbf9cvcvVfE5PvoKJgvA_14_3[0] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[72];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[72].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[72].offset = offsetof(tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ, _k_10.cond);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[72].typ = (&NTIexpr__A0r19bnoIYBiAGuW7tYi0BA_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[72].name = "cond";
TM__egaGbf9cvcvVfE5PvoKJgvA_14_3[1] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[73];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[73].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[73].offset = offsetof(tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ, _k_10.cleft);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[73].typ = (&NTIexpr__A0r19bnoIYBiAGuW7tYi0BA_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[73].name = "cleft";
TM__egaGbf9cvcvVfE5PvoKJgvA_14_3[2] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[74];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[74].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[74].offset = offsetof(tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ, _k_10.cright);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[74].typ = (&NTIexpr__A0r19bnoIYBiAGuW7tYi0BA_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[74].name = "cright";
TM__egaGbf9cvcvVfE5PvoKJgvA_0[71].len = 3; TM__egaGbf9cvcvVfE5PvoKJgvA_0[71].kind = 2; TM__egaGbf9cvcvVfE5PvoKJgvA_0[71].sons = &TM__egaGbf9cvcvVfE5PvoKJgvA_14_3[0];
NimDT___eqRwdyQ9bUMO9bghkVuWSD9cQ_k[7] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[71];
TM__egaGbf9cvcvVfE5PvoKJgvA_15_2[0] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[76];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[76].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[76].offset = offsetof(tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ, _k_11.castop);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[76].typ = (&NTIcastop__9crSbEPW1bL178akY7zCPGA_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[76].name = "castop";
TM__egaGbf9cvcvVfE5PvoKJgvA_15_2[1] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[77];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[77].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[77].offset = offsetof(tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ, _k_11.castval);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[77].typ = (&NTIexpr__A0r19bnoIYBiAGuW7tYi0BA_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[77].name = "castval";
TM__egaGbf9cvcvVfE5PvoKJgvA_0[75].len = 2; TM__egaGbf9cvcvVfE5PvoKJgvA_0[75].kind = 2; TM__egaGbf9cvcvVfE5PvoKJgvA_0[75].sons = &TM__egaGbf9cvcvVfE5PvoKJgvA_15_2[0];
NimDT___eqRwdyQ9bUMO9bghkVuWSD9cQ_k[8] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[75];
TM__egaGbf9cvcvVfE5PvoKJgvA_16_2[0] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[79];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[79].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[79].offset = offsetof(tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ, _k_12.callfunc);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[79].typ = (&NTIexpr__A0r19bnoIYBiAGuW7tYi0BA_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[79].name = "callfunc";
TM__egaGbf9cvcvVfE5PvoKJgvA_16_2[1] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[80];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[80].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[80].offset = offsetof(tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ, _k_12.callargs);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[80].typ = (&NTIseqLexprT__5Ea4hthuw6lQuV4Ge38uDA_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[80].name = "callargs";
TM__egaGbf9cvcvVfE5PvoKJgvA_0[78].len = 2; TM__egaGbf9cvcvVfE5PvoKJgvA_0[78].kind = 2; TM__egaGbf9cvcvVfE5PvoKJgvA_0[78].sons = &TM__egaGbf9cvcvVfE5PvoKJgvA_16_2[0];
NimDT___eqRwdyQ9bUMO9bghkVuWSD9cQ_k[9] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[78];
TM__egaGbf9cvcvVfE5PvoKJgvA_17_2[0] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[82];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[82].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[82].offset = offsetof(tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ, _k_13.left);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[82].typ = (&NTIexpr__A0r19bnoIYBiAGuW7tYi0BA_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[82].name = "left";
TM__egaGbf9cvcvVfE5PvoKJgvA_17_2[1] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[83];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[83].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[83].offset = offsetof(tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ, _k_13.right);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[83].typ = (&NTIexpr__A0r19bnoIYBiAGuW7tYi0BA_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[83].name = "right";
TM__egaGbf9cvcvVfE5PvoKJgvA_0[81].len = 2; TM__egaGbf9cvcvVfE5PvoKJgvA_0[81].kind = 2; TM__egaGbf9cvcvVfE5PvoKJgvA_0[81].sons = &TM__egaGbf9cvcvVfE5PvoKJgvA_17_2[0];
NimDT___eqRwdyQ9bUMO9bghkVuWSD9cQ_k[10] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[81];
TM__egaGbf9cvcvVfE5PvoKJgvA_18_2[0] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[85];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[85].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[85].offset = offsetof(tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ, _k_14.obj);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[85].typ = (&NTIexpr__A0r19bnoIYBiAGuW7tYi0BA_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[85].name = "obj";
TM__egaGbf9cvcvVfE5PvoKJgvA_18_2[1] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[86];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[86].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[86].offset = offsetof(tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ, _k_14.idx);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[86].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[86].name = "idx";
TM__egaGbf9cvcvVfE5PvoKJgvA_0[84].len = 2; TM__egaGbf9cvcvVfE5PvoKJgvA_0[84].kind = 2; TM__egaGbf9cvcvVfE5PvoKJgvA_0[84].sons = &TM__egaGbf9cvcvVfE5PvoKJgvA_18_2[0];
NimDT___eqRwdyQ9bUMO9bghkVuWSD9cQ_k[17] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[84];
NimDT___eqRwdyQ9bUMO9bghkVuWSD9cQ_k[18] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[84];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[87].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[87].offset = offsetof(tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ, _k_15.p);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[87].typ = (&NTIpointer__vr5DoT1jILTGdRlYv1OYpw_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[87].name = "p";
NimDT___eqRwdyQ9bUMO9bghkVuWSD9cQ_k[14] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[87];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[88].len = 0; TM__egaGbf9cvcvVfE5PvoKJgvA_0[88].kind = 2;
NimDT___eqRwdyQ9bUMO9bghkVuWSD9cQ_k[11] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[88];
NimDT___eqRwdyQ9bUMO9bghkVuWSD9cQ_k[16] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[88];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[31].len = 2; TM__egaGbf9cvcvVfE5PvoKJgvA_0[31].kind = 2; TM__egaGbf9cvcvVfE5PvoKJgvA_0[31].sons = &TM__egaGbf9cvcvVfE5PvoKJgvA_7_2[0];
NTIexpr58objecttype__eqRwdyQ9bUMO9bghkVuWSD9cQ_.node = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[31];
NTIexpr__A0r19bnoIYBiAGuW7tYi0BA_.size = sizeof(tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ*);
NTIexpr__A0r19bnoIYBiAGuW7tYi0BA_.align = NIM_ALIGNOF(tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ*);
NTIexpr__A0r19bnoIYBiAGuW7tYi0BA_.kind = 22;
NTIexpr__A0r19bnoIYBiAGuW7tYi0BA_.base = (&NTIexpr58objecttype__eqRwdyQ9bUMO9bghkVuWSD9cQ_);
NTIexpr__A0r19bnoIYBiAGuW7tYi0BA_.marker = Marker_tyRef__A0r19bnoIYBiAGuW7tYi0BA;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[30].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[30].offset = offsetof(tyObject_StmtcolonObjectType___D3ZZSzbHHz9aqVhgDX6uEAA, _k_5.case_expr);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[30].typ = (&NTIexpr__A0r19bnoIYBiAGuW7tYi0BA_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[30].name = "case_expr";
TM__egaGbf9cvcvVfE5PvoKJgvA_6_2[1] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[89];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[89].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[89].offset = offsetof(tyObject_StmtcolonObjectType___D3ZZSzbHHz9aqVhgDX6uEAA, _k_5.case_stmt);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[89].typ = (&NTIstmt__5KgliZANPtggDh8VWtfw3Q_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[89].name = "case_stmt";
TM__egaGbf9cvcvVfE5PvoKJgvA_0[29].len = 2; TM__egaGbf9cvcvVfE5PvoKJgvA_0[29].kind = 2; TM__egaGbf9cvcvVfE5PvoKJgvA_0[29].sons = &TM__egaGbf9cvcvVfE5PvoKJgvA_6_2[0];
NimDT___D3ZZSzbHHz9aqVhgDX6uEAA_k[17] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[29];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[90].len = 0; TM__egaGbf9cvcvVfE5PvoKJgvA_0[90].kind = 2;
NimDT___D3ZZSzbHHz9aqVhgDX6uEAA_k[4] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[90];
NimDT___D3ZZSzbHHz9aqVhgDX6uEAA_k[3] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[90];
NimDT___D3ZZSzbHHz9aqVhgDX6uEAA_k[0] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[90];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[91].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[91].offset = offsetof(tyObject_StmtcolonObjectType___D3ZZSzbHHz9aqVhgDX6uEAA, _k_7.exprbody);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[91].typ = (&NTIexpr__A0r19bnoIYBiAGuW7tYi0BA_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[91].name = "exprbody";
NimDT___D3ZZSzbHHz9aqVhgDX6uEAA_k[6] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[91];
NimDT___D3ZZSzbHHz9aqVhgDX6uEAA_k[5] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[91];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[92].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[92].offset = offsetof(tyObject_StmtcolonObjectType___D3ZZSzbHHz9aqVhgDX6uEAA, _k_8.location);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[92].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[92].name = "location";
NimDT___D3ZZSzbHHz9aqVhgDX6uEAA_k[2] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[92];
TM__egaGbf9cvcvVfE5PvoKJgvA_19_2[0] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[94];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[94].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[94].offset = offsetof(tyObject_StmtcolonObjectType___D3ZZSzbHHz9aqVhgDX6uEAA, _k_9.label);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[94].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[94].name = "label";
TM__egaGbf9cvcvVfE5PvoKJgvA_19_2[1] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[95];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[95].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[95].offset = offsetof(tyObject_StmtcolonObjectType___D3ZZSzbHHz9aqVhgDX6uEAA, _k_9.labledstmt);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[95].typ = (&NTIstmt__5KgliZANPtggDh8VWtfw3Q_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[95].name = "labledstmt";
TM__egaGbf9cvcvVfE5PvoKJgvA_0[93].len = 2; TM__egaGbf9cvcvVfE5PvoKJgvA_0[93].kind = 2; TM__egaGbf9cvcvVfE5PvoKJgvA_0[93].sons = &TM__egaGbf9cvcvVfE5PvoKJgvA_19_2[0];
NimDT___D3ZZSzbHHz9aqVhgDX6uEAA_k[7] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[93];
TM__egaGbf9cvcvVfE5PvoKJgvA_20_3[0] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[97];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[97].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[97].offset = offsetof(tyObject_StmtcolonObjectType___D3ZZSzbHHz9aqVhgDX6uEAA, _k_10.iftest);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[97].typ = (&NTIexpr__A0r19bnoIYBiAGuW7tYi0BA_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[97].name = "iftest";
TM__egaGbf9cvcvVfE5PvoKJgvA_20_3[1] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[98];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[98].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[98].offset = offsetof(tyObject_StmtcolonObjectType___D3ZZSzbHHz9aqVhgDX6uEAA, _k_10.ifbody);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[98].typ = (&NTIstmt__5KgliZANPtggDh8VWtfw3Q_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[98].name = "ifbody";
TM__egaGbf9cvcvVfE5PvoKJgvA_20_3[2] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[99];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[99].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[99].offset = offsetof(tyObject_StmtcolonObjectType___D3ZZSzbHHz9aqVhgDX6uEAA, _k_10.elsebody);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[99].typ = (&NTIstmt__5KgliZANPtggDh8VWtfw3Q_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[99].name = "elsebody";
TM__egaGbf9cvcvVfE5PvoKJgvA_0[96].len = 3; TM__egaGbf9cvcvVfE5PvoKJgvA_0[96].kind = 2; TM__egaGbf9cvcvVfE5PvoKJgvA_0[96].sons = &TM__egaGbf9cvcvVfE5PvoKJgvA_20_3[0];
NimDT___D3ZZSzbHHz9aqVhgDX6uEAA_k[8] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[96];
TM__egaGbf9cvcvVfE5PvoKJgvA_21_2[0] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[101];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[101].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[101].offset = offsetof(tyObject_StmtcolonObjectType___D3ZZSzbHHz9aqVhgDX6uEAA, _k_11.test);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[101].typ = (&NTIexpr__A0r19bnoIYBiAGuW7tYi0BA_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[101].name = "test";
TM__egaGbf9cvcvVfE5PvoKJgvA_21_2[1] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[102];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[102].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[102].offset = offsetof(tyObject_StmtcolonObjectType___D3ZZSzbHHz9aqVhgDX6uEAA, _k_11.body);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[102].typ = (&NTIstmt__5KgliZANPtggDh8VWtfw3Q_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[102].name = "body";
TM__egaGbf9cvcvVfE5PvoKJgvA_0[100].len = 2; TM__egaGbf9cvcvVfE5PvoKJgvA_0[100].kind = 2; TM__egaGbf9cvcvVfE5PvoKJgvA_0[100].sons = &TM__egaGbf9cvcvVfE5PvoKJgvA_21_2[0];
NimDT___D3ZZSzbHHz9aqVhgDX6uEAA_k[9] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[100];
NimDT___D3ZZSzbHHz9aqVhgDX6uEAA_k[10] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[100];
NimDT___D3ZZSzbHHz9aqVhgDX6uEAA_k[12] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[100];
TM__egaGbf9cvcvVfE5PvoKJgvA_22_4[0] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[104];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[104].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[104].offset = offsetof(tyObject_StmtcolonObjectType___D3ZZSzbHHz9aqVhgDX6uEAA, _k_12.forinit);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[104].typ = (&NTIstmt__5KgliZANPtggDh8VWtfw3Q_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[104].name = "forinit";
TM__egaGbf9cvcvVfE5PvoKJgvA_22_4[1] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[105];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[105].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[105].offset = offsetof(tyObject_StmtcolonObjectType___D3ZZSzbHHz9aqVhgDX6uEAA, _k_12.forcond);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[105].typ = (&NTIexpr__A0r19bnoIYBiAGuW7tYi0BA_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[105].name = "forcond";
TM__egaGbf9cvcvVfE5PvoKJgvA_22_4[2] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[106];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[106].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[106].offset = offsetof(tyObject_StmtcolonObjectType___D3ZZSzbHHz9aqVhgDX6uEAA, _k_12.forincl);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[106].typ = (&NTIexpr__A0r19bnoIYBiAGuW7tYi0BA_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[106].name = "forincl";
TM__egaGbf9cvcvVfE5PvoKJgvA_22_4[3] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[107];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[107].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[107].offset = offsetof(tyObject_StmtcolonObjectType___D3ZZSzbHHz9aqVhgDX6uEAA, _k_12.forbody);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[107].typ = (&NTIstmt__5KgliZANPtggDh8VWtfw3Q_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[107].name = "forbody";
TM__egaGbf9cvcvVfE5PvoKJgvA_0[103].len = 4; TM__egaGbf9cvcvVfE5PvoKJgvA_0[103].kind = 2; TM__egaGbf9cvcvVfE5PvoKJgvA_0[103].sons = &TM__egaGbf9cvcvVfE5PvoKJgvA_22_4[0];
NimDT___D3ZZSzbHHz9aqVhgDX6uEAA_k[11] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[103];
TM__egaGbf9cvcvVfE5PvoKJgvA_23_2[0] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[109];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[109].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[109].offset = offsetof(tyObject_StmtcolonObjectType___D3ZZSzbHHz9aqVhgDX6uEAA, _k_13.var1name);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[109].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[109].name = "var1name";
TM__egaGbf9cvcvVfE5PvoKJgvA_23_2[1] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[110];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[110].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[110].offset = offsetof(tyObject_StmtcolonObjectType___D3ZZSzbHHz9aqVhgDX6uEAA, _k_13.var1type);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[110].typ = (&NTIctype__9cf0EuNkYZeO83WITZYEetQ_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[110].name = "var1type";
TM__egaGbf9cvcvVfE5PvoKJgvA_0[108].len = 2; TM__egaGbf9cvcvVfE5PvoKJgvA_0[108].kind = 2; TM__egaGbf9cvcvVfE5PvoKJgvA_0[108].sons = &TM__egaGbf9cvcvVfE5PvoKJgvA_23_2[0];
NimDT___D3ZZSzbHHz9aqVhgDX6uEAA_k[19] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[108];
NTILstring_ctype_exprT__QM04Qszh7tudE7LWUtmhXQ_.size = sizeof(tyTuple__QM04Qszh7tudE7LWUtmhXQ);
NTILstring_ctype_exprT__QM04Qszh7tudE7LWUtmhXQ_.align = NIM_ALIGNOF(tyTuple__QM04Qszh7tudE7LWUtmhXQ);
NTILstring_ctype_exprT__QM04Qszh7tudE7LWUtmhXQ_.kind = 18;
NTILstring_ctype_exprT__QM04Qszh7tudE7LWUtmhXQ_.base = 0;
TM__egaGbf9cvcvVfE5PvoKJgvA_24_3[0] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[113];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[113].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[113].offset = offsetof(tyTuple__QM04Qszh7tudE7LWUtmhXQ, Field0);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[113].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[113].name = "Field0";
TM__egaGbf9cvcvVfE5PvoKJgvA_24_3[1] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[114];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[114].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[114].offset = offsetof(tyTuple__QM04Qszh7tudE7LWUtmhXQ, Field1);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[114].typ = (&NTIctype__9cf0EuNkYZeO83WITZYEetQ_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[114].name = "Field1";
TM__egaGbf9cvcvVfE5PvoKJgvA_24_3[2] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[115];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[115].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[115].offset = offsetof(tyTuple__QM04Qszh7tudE7LWUtmhXQ, Field2);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[115].typ = (&NTIexpr__A0r19bnoIYBiAGuW7tYi0BA_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[115].name = "Field2";
TM__egaGbf9cvcvVfE5PvoKJgvA_0[112].len = 3; TM__egaGbf9cvcvVfE5PvoKJgvA_0[112].kind = 2; TM__egaGbf9cvcvVfE5PvoKJgvA_0[112].sons = &TM__egaGbf9cvcvVfE5PvoKJgvA_24_3[0];
NTILstring_ctype_exprT__QM04Qszh7tudE7LWUtmhXQ_.node = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[112];
NTIseqLLstring_ctype_exprTT__sCWjRzukJ9amxY1VYtECwiw_.size = sizeof(tySequence__sCWjRzukJ9amxY1VYtECwiw*);
NTIseqLLstring_ctype_exprTT__sCWjRzukJ9amxY1VYtECwiw_.align = NIM_ALIGNOF(tySequence__sCWjRzukJ9amxY1VYtECwiw*);
NTIseqLLstring_ctype_exprTT__sCWjRzukJ9amxY1VYtECwiw_.kind = 24;
NTIseqLLstring_ctype_exprTT__sCWjRzukJ9amxY1VYtECwiw_.base = (&NTILstring_ctype_exprT__QM04Qszh7tudE7LWUtmhXQ_);
NTIseqLLstring_ctype_exprTT__sCWjRzukJ9amxY1VYtECwiw_.marker = Marker_tySequence__sCWjRzukJ9amxY1VYtECwiw;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[111].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[111].offset = offsetof(tyObject_StmtcolonObjectType___D3ZZSzbHHz9aqVhgDX6uEAA, _k_14.vars);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[111].typ = (&NTIseqLLstring_ctype_exprTT__sCWjRzukJ9amxY1VYtECwiw_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[111].name = "vars";
NimDT___D3ZZSzbHHz9aqVhgDX6uEAA_k[15] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[111];
TM__egaGbf9cvcvVfE5PvoKJgvA_0[116].kind = 1;
TM__egaGbf9cvcvVfE5PvoKJgvA_0[116].offset = offsetof(tyObject_StmtcolonObjectType___D3ZZSzbHHz9aqVhgDX6uEAA, _k_15.decl);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[116].typ = (&NTIctype__9cf0EuNkYZeO83WITZYEetQ_);
TM__egaGbf9cvcvVfE5PvoKJgvA_0[116].name = "decl";
NimDT___D3ZZSzbHHz9aqVhgDX6uEAA_k[13] = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[116];
NTIstmt58objecttype__D3ZZSzbHHz9aqVhgDX6uEAA_.node = &TM__egaGbf9cvcvVfE5PvoKJgvA_0[0];
NTIstmt__5KgliZANPtggDh8VWtfw3Q_.size = sizeof(tyObject_StmtcolonObjectType___D3ZZSzbHHz9aqVhgDX6uEAA*);
NTIstmt__5KgliZANPtggDh8VWtfw3Q_.align = NIM_ALIGNOF(tyObject_StmtcolonObjectType___D3ZZSzbHHz9aqVhgDX6uEAA*);
NTIstmt__5KgliZANPtggDh8VWtfw3Q_.kind = 22;
NTIstmt__5KgliZANPtggDh8VWtfw3Q_.base = (&NTIstmt58objecttype__D3ZZSzbHHz9aqVhgDX6uEAA_);
NTIstmt__5KgliZANPtggDh8VWtfw3Q_.marker = Marker_tyRef__5KgliZANPtggDh8VWtfw3Q;
}

