/* Generated by Nim Compiler v1.6.6 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\Users\林仁傑\source\mingw64\bin\gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN   -IC:\Users\林仁傑\source\nim-1.6.6\lib -IC:\Users\林仁傑\source\Runner\cc -o C:\Users\林仁傑\source\Runner\cc\foo\@mbuiltins.nim.c.o C:\Users\林仁傑\source\Runner\cc\foo\@mbuiltins.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include "string.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_2999)(void);
static N_INLINE(void, popFrame)(void);
extern TFrame* framePtr__system_2566;
extern TFrame* framePtr__system_2566;
extern TFrame* framePtr__system_2566;
extern TFrame* framePtr__system_2566;
extern TFrame* framePtr__system_2566;
extern TFrame* framePtr__system_2566;
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s) {
	NCSTRING result;
	result = (NCSTRING)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (s == ((NimStringDesc*) NIM_NIL));
		if (T3_) goto LA4_;
		T3_ = ((*s).Sup.len == ((NI) 0));
		LA4_: ;
		if (!T3_) goto LA5_;
		result = "";
	}
	goto LA1_;
	LA5_: ;
	{
		result = ((NCSTRING) ((*s).data));
	}
	LA1_: ;
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s) {
	{
		if (!(framePtr__system_2566 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s).calldepth = ((NI16) 0);
	}
	goto LA1_;
	LA3_: ;
	{
		(*s).calldepth = (NI16)((*framePtr__system_2566).calldepth + ((NI16) 1));
	}
	LA1_: ;
	(*s).prev = framePtr__system_2566;
	framePtr__system_2566 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;
		callDepthLimitReached__system_2999();
	}
	LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_2566 = (*framePtr__system_2566).prev;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, is_builtin_name__builtins_9)(NimStringDesc* name) {
	NIM_BOOL result;
	nimfr_("is_builtin_name", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\builtins.nim");
	result = (NIM_BOOL)0;
	nimln_(8, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\builtins.nim");
	{
		int T3_;
		T3_ = (int)0;
		T3_ = strncmp(nimToCStringConv(name), "__builtin_", ((size_t) 10));
		if (!(T3_ == ((NI32) 0))) goto LA4_;
		result = NIM_TRUE;
	}
	goto LA1_;
	LA4_: ;
	{
		int T7_;
		nimln_(10, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\builtins.nim");
		T7_ = (int)0;
		T7_ = strncmp(nimToCStringConv(name), "__sync_", ((size_t) 7));
		if (!(T7_ == ((NI32) 0))) goto LA8_;
		result = NIM_TRUE;
	}
	goto LA1_;
	LA8_: ;
	{
		int T11_;
		nimln_(12, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\builtins.nim");
		T11_ = (int)0;
		T11_ = strncmp(nimToCStringConv(name), "__atomic_", ((size_t) 9));
		if (!(T11_ == ((NI32) 0))) goto LA12_;
		result = NIM_TRUE;
	}
	goto LA1_;
	LA12_: ;
	{
		result = NIM_FALSE;
	}
	LA1_: ;
	popFrame();
	return result;
}
