/* Generated by Nim Compiler v1.6.6 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\Users\林仁傑\source\mingw64\bin\gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN   -IC:\Users\林仁傑\source\nim-1.6.6\lib -IC:\Users\林仁傑\source\Runner\cc -o C:\Users\林仁傑\source\Runner\cc\foo\@mcli.nim.c.o C:\Users\林仁傑\source\Runner\cc\foo\@mcli.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include "stdio.h"
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  typedef struct tyTuple__ATBA8nsHhJsFdrZp9beDcqA tyTuple__ATBA8nsHhJsFdrZp9beDcqA;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack__7fytPA5bBsob6See21YMRA tyObject_GcStack__7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyTuple__ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_CC__H5XRV6CeEvWKbip2uECzdg tyObject_CC__H5XRV6CeEvWKbip2uECzdg;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tyObject_CTypecolonObjectType___y9c8kbbfIvBCGqKHvKcIVGw tyObject_CTypecolonObjectType___y9c8kbbfIvBCGqKHvKcIVGw;
typedef struct tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ;
typedef struct tySequence__1BBmFBuDfKRifk60cOMPTA tySequence__1BBmFBuDfKRifk60cOMPTA;
typedef struct tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA;
typedef struct tyObject_ParsercolonObjectType___lJsmkenZ3vILkn3jj4vS6w tyObject_ParsercolonObjectType___lJsmkenZ3vILkn3jj4vS6w;
typedef struct tySequence__d8M9bCHvPeBbf8w29cp9bhkeA tySequence__d8M9bCHvPeBbf8w29cp9bhkeA;
typedef struct tySequence__yk8YBI4DVEPKlqvq4E3jaQ tySequence__yk8YBI4DVEPKlqvq4E3jaQ;
typedef struct tyObject_TokenVcolonObjectType___UHmww0SAtuepdPeXHZTqZw tyObject_TokenVcolonObjectType___UHmww0SAtuepdPeXHZTqZw;
typedef struct tyObject_Table__IkhSz6chBcQddILqAmB2Bw tyObject_Table__IkhSz6chBcQddILqAmB2Bw;
typedef struct tySequence__JVl4l2FTq9cKT6CTi8NEvdg tySequence__JVl4l2FTq9cKT6CTi8NEvdg;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ tySequence__6H5Oh5UUvVCLiakt9aTwtUQ;
typedef struct tyObject_HashSet__CD8Dpv0WGmASelVaNSo6zg tyObject_HashSet__CD8Dpv0WGmASelVaNSo6zg;
typedef struct tySequence__4eRCaZmrYLLw2k30GPTiMw tySequence__4eRCaZmrYLLw2k30GPTiMw;
typedef struct tySequence__JBVMxYw59aXIATitfVihSXg tySequence__JBVMxYw59aXIATitfVihSXg;
typedef struct tySequence__XXSYSjw7g1bMW9cqPte4oDQ tySequence__XXSYSjw7g1bMW9cqPte4oDQ;
typedef struct tyObject_StreamcolonObjectType___ADoOUY5nj7w3cjSeMpeq9bg tyObject_StreamcolonObjectType___ADoOUY5nj7w3cjSeMpeq9bg;
typedef struct tyObject_Location__Q9aEveWfE4AtLRzHJktGXnA tyObject_Location__Q9aEveWfE4AtLRzHJktGXnA;
typedef struct tyTuple__sAmD9coS5prXHiu3i4hes9aA tyTuple__sAmD9coS5prXHiu3i4hes9aA;
typedef struct tyObject_PPMacrocolonObjectType___qePcXpxo9bHxHmnxPVsHXog tyObject_PPMacrocolonObjectType___qePcXpxo9bHxHmnxPVsHXog;
typedef struct tyTuple__QeWl6B6ffS4pU6WWrtcrDw tyTuple__QeWl6B6ffS4pU6WWrtcrDw;
typedef struct tyObject_Table__39cqxIJDhLlDDNdoZ2A7EbQ tyObject_Table__39cqxIJDhLlDDNdoZ2A7EbQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_NIMCALL_PTR(void, tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct tyTuple__ATBA8nsHhJsFdrZp9beDcqA {
NimStringDesc* Field0;
NI Field1;
tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ Field2;
NimStringDesc* Field3;
};
typedef tyTuple__ATBA8nsHhJsFdrZp9beDcqA tyArray__v2bwnl6nEpojF303kp4mmw[29];
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
NI align;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack__7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ* tyArray__SPr7N6UKfuF549bNPiUvSRw[256];
typedef NU32 tyArray__BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* tyArray__N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray__N1u1nqOgmuJN9cSZrnMHgOQ tyArray__B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw* tyArray__lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA {
tyArray__lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* tyArray__0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw {
tyArray__0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyArray__LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray__LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray__SPr7N6UKfuF549bNPiUvSRw freeSmallChunks;
NU32 flBitmap;
tyArray__BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray__B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack__7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
NI zctThreshold;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
typedef NU8 tyEnum_Input__4xkeTUPZE5X9azudwRBEOVA;
typedef NU8 tyEnum_Output__z2pKOFEGp5K7qKOH5sOfcA;
typedef NU8 tyEnum_VerboseLevel__xI6367Zu5WWcwaENhMBQFA;
typedef NU8 tyEnum_Linker__VnxA6dODl7K2C9a4taFpPxA;
typedef struct {
N_NIMCALL_PTR(unsigned long long, ClP_0) (tyObject_CTypecolonObjectType___y9c8kbbfIvBCGqKHvKcIVGw* ty, void* ClE_0);
void* ClE_0;
} tyProc__GDxfnfju9aOVojHhiPTEm1g;
typedef struct {
N_NIMCALL_PTR(unsigned long long, ClP_0) (tyObject_CTypecolonObjectType___y9c8kbbfIvBCGqKHvKcIVGw* ty, NI idx, void* ClE_0);
void* ClE_0;
} tyProc__V8axfTLMXV2ebRNg6M9aGGQ;
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc__HzVCwACFYM9cx9aV62PdjtuA;
typedef struct {
N_NIMCALL_PTR(NI64, ClP_0) (tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ* e, void* ClE_0);
void* ClE_0;
} tyProc__Ss9bezNnzQaBhBwsIKf0qTg;
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (tySequence__1BBmFBuDfKRifk60cOMPTA* tokens, void* ClE_0);
void* ClE_0;
} tyProc__PTN2F5CmbJA6Q7KsriQPdQ;
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (NimStringDesc* p, void* ClE_0);
void* ClE_0;
} tyProc__k2HFjxisIgDALbEUFojxaQ;
struct tyObject_CC__H5XRV6CeEvWKbip2uECzdg {
tyEnum_Input__4xkeTUPZE5X9azudwRBEOVA input;
tyEnum_Output__z2pKOFEGp5K7qKOH5sOfcA mode;
NIM_BOOL runJit;
unsigned int optLevel;
unsigned int sizeLevel;
unsigned int inlineThreshold;
NimStringDesc* output;
tyEnum_VerboseLevel__xI6367Zu5WWcwaENhMBQFA verboseLevel;
NIM_BOOL opaquePointerEnabled;
tyEnum_Linker__VnxA6dODl7K2C9a4taFpPxA linker;
NimStringDesc* triple;
tySequence__sM4lkSb7zS6F7OVMvW9cffQ* inputs;
unsigned long long pointersize;
tyProc__GDxfnfju9aOVojHhiPTEm1g getSizeof;
tyProc__V8axfTLMXV2ebRNg6M9aGGQ getoffsetof;
tyProc__GDxfnfju9aOVojHhiPTEm1g getAlignOf;
tyProc__HzVCwACFYM9cx9aV62PdjtuA lex;
tyProc__HzVCwACFYM9cx9aV62PdjtuA cpp;
tyProc__Ss9bezNnzQaBhBwsIKf0qTg eval_const_expression;
tyProc__PTN2F5CmbJA6Q7KsriQPdQ pragma;
tyProc__k2HFjxisIgDALbEUFojxaQ pragmas;
};
struct tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA {
NI a;
NI b;
};
typedef N_NIMCALL_PTR(void, tyProc__W6IXMh2CA4X1rFYGjUb4yg) (NimStringDesc* s);
struct tyObject_Table__IkhSz6chBcQddILqAmB2Bw {
tySequence__JVl4l2FTq9cKT6CTi8NEvdg* data;
NI counter;
};
typedef NU8 tyEnum_ParseFlags__exxWDbohGZ4z8m1JX5sOSg;
struct tyObject_HashSet__CD8Dpv0WGmASelVaNSo6zg {
tySequence__4eRCaZmrYLLw2k30GPTiMw* data;
NI counter;
};
struct tyObject_ParsercolonObjectType___lJsmkenZ3vILkn3jj4vS6w {
tyObject_CTypecolonObjectType___y9c8kbbfIvBCGqKHvKcIVGw* currentfunctionRet;
tyObject_CTypecolonObjectType___y9c8kbbfIvBCGqKHvKcIVGw* currentInitTy;
tyObject_CTypecolonObjectType___y9c8kbbfIvBCGqKHvKcIVGw* currentCase;
NimStringDesc* pfunc;
NU32 currentAlign;
tySequence__d8M9bCHvPeBbf8w29cp9bhkeA* fstack;
tySequence__sM4lkSb7zS6F7OVMvW9cffQ* filenamestack;
tySequence__sM4lkSb7zS6F7OVMvW9cffQ* pathstack;
tySequence__yk8YBI4DVEPKlqvq4E3jaQ* locstack;
tyObject_TokenVcolonObjectType___UHmww0SAtuepdPeXHZTqZw* tok;
NI line;
NI col;
NIM_CHAR c;
NIM_BOOL want_expr;
NU16 lastc;
NimStringDesc* filename;
NimStringDesc* path;
tyObject_Table__IkhSz6chBcQddILqAmB2Bw macros;
tyEnum_ParseFlags__exxWDbohGZ4z8m1JX5sOSg flags;
tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* ppstack;
NIM_BOOL ok;
tyObject_HashSet__CD8Dpv0WGmASelVaNSo6zg onces;
tyObject_HashSet__CD8Dpv0WGmASelVaNSo6zg expansion_list;
tySequence__JBVMxYw59aXIATitfVihSXg* lables;
tySequence__XXSYSjw7g1bMW9cqPte4oDQ* tags;
tySequence__XXSYSjw7g1bMW9cqPte4oDQ* typedefs;
tySequence__1BBmFBuDfKRifk60cOMPTA* tokenq;
NI counter;
tyObject_CTypecolonObjectType___y9c8kbbfIvBCGqKHvKcIVGw* retTy;
NIM_BOOL type_error;
NIM_BOOL eval_error;
NIM_BOOL parse_error;
NIM_BOOL bad_error;
};
struct tyObject_Location__Q9aEveWfE4AtLRzHJktGXnA {
NI line;
NI col;
};
struct tyTuple__sAmD9coS5prXHiu3i4hes9aA {
NI Field0;
NimStringDesc* Field1;
tyObject_PPMacrocolonObjectType___qePcXpxo9bHxHmnxPVsHXog* Field2;
};
struct tyTuple__QeWl6B6ffS4pU6WWrtcrDw {
NI Field0;
NimStringDesc* Field1;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence__1BBmFBuDfKRifk60cOMPTA {
  TGenericSeq Sup;
  tyObject_TokenVcolonObjectType___UHmww0SAtuepdPeXHZTqZw* data[SEQ_DECL_SIZE];
};
struct tySequence__d8M9bCHvPeBbf8w29cp9bhkeA {
  TGenericSeq Sup;
  tyObject_StreamcolonObjectType___ADoOUY5nj7w3cjSeMpeq9bg* data[SEQ_DECL_SIZE];
};
struct tySequence__yk8YBI4DVEPKlqvq4E3jaQ {
  TGenericSeq Sup;
  tyObject_Location__Q9aEveWfE4AtLRzHJktGXnA data[SEQ_DECL_SIZE];
};
struct tySequence__JVl4l2FTq9cKT6CTi8NEvdg {
  TGenericSeq Sup;
  tyTuple__sAmD9coS5prXHiu3i4hes9aA data[SEQ_DECL_SIZE];
};
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ {
  TGenericSeq Sup;
  NU8 data[SEQ_DECL_SIZE];
};
struct tySequence__4eRCaZmrYLLw2k30GPTiMw {
  TGenericSeq Sup;
  tyTuple__QeWl6B6ffS4pU6WWrtcrDw data[SEQ_DECL_SIZE];
};
struct tySequence__JBVMxYw59aXIATitfVihSXg {
  TGenericSeq Sup;
  tyObject_HashSet__CD8Dpv0WGmASelVaNSo6zg data[SEQ_DECL_SIZE];
};
struct tySequence__XXSYSjw7g1bMW9cqPte4oDQ {
  TGenericSeq Sup;
  tyObject_Table__39cqxIJDhLlDDNdoZ2A7EbQ* data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, TM__9aH0vWwOpIMj7j9c9bzhanzQQ_3)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(void, decRef__system_5399)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_2999)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_BOOL, ltpercent___system_1005)(NI x, NI y);
static N_INLINE(void, rtlAddZCT__system_5397)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT__system_5348)(tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__system_5354)(void* usr);
N_LIB_PRIVATE N_NIMCALL(void, showVersion__cli_36)(void);
N_LIB_PRIVATE N_NIMCALL(void, ltltlt___stream_52)(struct FILE* stream, NimStringDesc* msg);
N_LIB_PRIVATE N_NIMCALL(void, dumpVersionInfo__llvm_3260)(void);
N_LIB_PRIVATE N_NIMCALL(void, setStdin__cli_37)(void);
N_LIB_PRIVATE N_NIMCALL(void, addStdin__parser_5313)(void);
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous___cli_41)(void);
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous___cli_42)(NimStringDesc* s);
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous___cli_44)(void);
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous___cli_45)(void);
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous___cli_46)(void);
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous___cli_47)(void);
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous___cli_48)(NimStringDesc* s);
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous___cli_50)(void);
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous___cli_51)(void);
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous___cli_52)(void);
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous___cli_53)(void);
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous___cli_54)(void);
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous___cli_55)(void);
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous___cli_56)(void);
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous___cli_57)(void);
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous___cli_58)(void);
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous___cli_59)(void);
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous___cli_60)(void);
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous___cli_61)(void);
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous___cli_62)(void);
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous___cli_63)(void);
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous___cli_64)(void);
N_LIB_PRIVATE N_NIMCALL(void, setInput__cli_38)(NimStringDesc* s);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem__system_1735)(void* a, void* b, NI size);
static N_INLINE(int, nimCmpMem)(void* a, void* b, NI size);
N_LIB_PRIVATE N_NIMCALL(NI, hashString)(NimStringDesc* s);
N_LIB_PRIVATE N_NIMCALL(void, error__core_143)(void);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem__system_1727)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasNext__cli_6)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, get__cli_11)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NimStringDesc*, X5BX5D___pureZunicode_3217)(NimStringDesc* s, tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA x);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
static N_INLINE(tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA, dotdot___stdZenumutils_80)(NI a, NI b);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(void, addFile__cli_120)(NimStringDesc* s);
N_LIB_PRIVATE N_NIMCALL(void, addInclude__parser_8129)(NimStringDesc* filename, NIM_BOOL isInclude);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef__system_5392)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NI, pluspercent___system_696)(NI x, NI y);
N_LIB_PRIVATE N_NIMCALL(void, newBackend__llvm_3179)(NimStringDesc* module_name, NimStringDesc* source_file);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_LIB_PRIVATE N_NIMCALL(void, addString__parser_5285)(NimStringDesc* s, NimStringDesc* filename);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s);
N_LIB_PRIVATE N_NIMCALL(void, ltlt___stream_42)(struct FILE* stream, NimStringDesc* msg);
N_LIB_PRIVATE N_NIMCALL(void, ltlt___stream_79)(struct FILE* stream, int c);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar___systemZdollars_3)(NI x);
N_LIB_PRIVATE N_NIMCALL(void, help__cli_40)(void);
N_LIB_PRIVATE N_NIMCALL(void, ltlt___stream_45)(struct FILE* stream, NIM_CHAR c);
N_LIB_PRIVATE TNimType NTILstring_int_p_stringT__ATBA8nsHhJsFdrZp9beDcqA_;
extern TNimType NTIstring__77mFvmsOLKik79ci2hXkHEg_;
extern TNimType NTIint__rR5Bzr1D5krxoo1NcNyeMA_;
N_LIB_PRIVATE TNimType NTIp__T4eqaYlFJYZUv9aG9b1TV0bQ_;
N_LIB_PRIVATE TNimType NTIarrayL48OO5056_Lstring_int_p_stringTT__v2bwnl6nEpojF303kp4mmw_;
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_4, "v", 1);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_5, "CC: C Compiler", 14);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_6, "Homepage: https://github.com/ianfun/cc.git", 42);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_7, "Bug report: https://github.com/ianfun/cc/issues", 47);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_8, "print version info", 18);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_9, "version", 7);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_10, "help", 4);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_11, "-help", 5);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_12, "stdin", 5);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_13, "add stdin to files", 18);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_14, "jit", 3);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_15, "run `main` function in LLVM JIT", 31);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_16, "target", 6);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_17, "set target triple: e.g: x86_64-pc-linux-gnu, x86_64-pc-windows-msvc", 67);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_18, "verbose", 7);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_19, "enable verbose message", 22);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_20, "note", 4);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_21, "enable note message", 19);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_22, "warning", 7);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_23, "enable warning message", 22);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_24, "Wall", 4);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_25, "\?", 1);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_26, "o", 1);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_27, "set output file path", 20);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_28, "emit-llvm", 9);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_29, "output LLVM Assembly", 20);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_30, "emit-bitcode", 12);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_31, "output LLVM bitcode", 19);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_32, "c", 1);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_33, "output object file", 18);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_34, "ld", 2);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_35, "use ld, The GNU linker", 22);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_36, "lld", 3);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_37, "use LLD, The LLVM linker", 24);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_38, "s", 1);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_39, "output assembly", 15);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_40, "fsyntax-only", 12);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_41, "parse input file, type checking, emit warning and messages.Do not output a file", 79);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_42, "no-opaque-pointers", 18);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_43, "disable opaque pointer", 22);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_44, "O0", 2);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_45, "no optimization(default)", 24);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_46, "O1", 2);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_47, "Somewhere between -O0 and -O2", 29);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_48, "O2", 2);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_49, "enables most optimizations", 26);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_50, "O3", 2);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_51, "enables optimizations that take longer to perform or that may generate larger code(for example, loop unrolling)", 111);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_52, "O4", 2);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_53, " = O3", 5);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_54, "Os", 2);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_55, "reduce code size", 16);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_56, "Oz", 2);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_57, "reduce code size further", 24);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_58, "x", 1);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_59, "C", 1);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_60, "S", 1);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_61, "assembler", 9);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_62, "asm", 3);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_63, "Asm", 3);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_64, "ASM", 3);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_65, "ir", 2);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_66, "IR", 2);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_67, "bc", 2);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_68, "BC", 2);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_69, "unrecognized input language: ", 29);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_70, "set input langauge", 18);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_77, "command expect one argument", 27);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_79, "unrecognized command line option \'-", 35);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_80, "no input files", 14);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_82, ".exe", 4);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_83, ".ll", 3);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_84, ".bc", 3);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_85, ".o", 2);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_86, ".s", 2);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_87, "#define __builtin_LINE() __LINE__\012#define __builtin_FILE() __FILE__\012#define __builtin_FUNCTION() __func__\012void *__builtin_alloca (unsigned long long);\012void *__builtin_alloca_with_align (unsigned long long size, unsigned long long alignment);\012_Bool __builtin_is_constant_evaluated (void);\012long __builtin_expect (long exp, long c);\012long __builtin_expect_with_probability(long exp, long c, double probability);\012_Noreturn void __builtin_trap (void);\012_Noreturn void __builtin_unreachable (void);\012unsigned short __builtin_bswap16 (unsigned short x);\012unsigned __builtin_bswap32 (unsigned x);\012unsigned long long __builtin_bswap64 (unsigned long long x);\012double __builtin_inf (void);\012", 675);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_88, "built-in", 8);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_89, "gcc \"", 5);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_90, "\" -o \"", 6);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_91, "error: gcc returned ", 20);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_92, " exit status", 12);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_93, "ld.lld --hash-style=gnu --no-add-needed  --build-id --eh-frame-hdr -dynamic-linker /lib/x86_64-linux-gnu/libc.so.6 /usr/lib64/ld-linux-x86-64.so.2 ", 147);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_94, " -o ", 4);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_95, "error: ld.lld returned ", 23);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_96, "command line options", 20);
STRING_LITERAL(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_97, "\011\011\011\011", 4);
N_LIB_PRIVATE NI i__cli_5 = ((NI) 0);
N_LIB_PRIVATE tyArray__v2bwnl6nEpojF303kp4mmw cliOptions__cli_65;
extern TFrame* framePtr__system_2566;
extern TFrame* framePtr__system_2566;
extern TFrame* framePtr__system_2566;
extern TFrame* framePtr__system_2566;
extern TFrame* framePtr__system_2566;
extern TFrame* framePtr__system_2566;
extern tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ gch__system_5301;
extern tyObject_CC__H5XRV6CeEvWKbip2uECzdg app__core_82;
extern tySequence__sM4lkSb7zS6F7OVMvW9cffQ* options__core_7;
extern tyObject_ParsercolonObjectType___lJsmkenZ3vILkn3jj4vS6w* p__parser_71;
static N_NIMCALL(void, TM__9aH0vWwOpIMj7j9c9bzhanzQQ_3)(void) {
	NI T1_;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < 29; T1_++) {
	nimGCvisit((void*)cliOptions__cli_65[T1_].Field0, 0);
	nimGCvisit((void*)cliOptions__cli_65[T1_].Field3, 0);
	}
}
static N_INLINE(void, nimFrame)(TFrame* s) {
	{
		if (!(framePtr__system_2566 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s).calldepth = ((NI16) 0);
	}
	goto LA1_;
	LA3_: ;
	{
		(*s).calldepth = (NI16)((*framePtr__system_2566).calldepth + ((NI16) 1));
	}
	LA1_: ;
	(*s).prev = framePtr__system_2566;
	framePtr__system_2566 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;
		callDepthLimitReached__system_2999();
	}
	LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_2566 = (*framePtr__system_2566).prev;
}
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y) {
	NI result;
	nimfr_("-%", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\arithmetics.nim");
	result = (NI)0;
	nimln_(414, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\arithmetics.nim");
	nimln_(418, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\arithmetics.nim");
	result = ((NI) ((NU)((NU64)(((NU) (x))) - (NU64)(((NU) (y))))));
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, ltpercent___system_1005)(NI x, NI y) {
	NIM_BOOL result;
	nimfr_("<%", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\comparisons.nim");
	result = (NIM_BOOL)0;
	nimln_(186, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\comparisons.nim");
	nimln_(188, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\comparisons.nim");
	result = ((NU64)(((NU) (x))) < (NU64)(((NU) (y))));
	popFrame();
	return result;
}
static N_INLINE(void, rtlAddZCT__system_5397)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\gc.nim");
	nimln_(243, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\gc.nim");
	addZCT__system_5348((&gch__system_5301.zct), c);
	popFrame();
}
static N_INLINE(void, decRef__system_5399)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\gc.nim");
	nimln_(248, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\gc.nim");
	(*c).refcount = minuspercent___system_716((*c).refcount, ((NI) 8));
	nimln_(249, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\gc.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = ltpercent___system_1005((*c).refcount, ((NI) 8));
		if (!T3_) goto LA4_;
		nimln_(250, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\gc.nim");
		rtlAddZCT__system_5397(c);
	}
	LA4_: ;
	popFrame();
}
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__system_5354)(void* usr) {
	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* result;
	NI T1_;
	nimfr_("usrToCell", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\gc.nim");
	result = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(177, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\gc.nim");
	T1_ = (NI)0;
	T1_ = minuspercent___system_716(((NI) (ptrdiff_t) (usr)), ((NI) 16));
	result = ((tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*) (T1_));
	popFrame();
	return result;
}
static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T1_;
	nimfr_("nimGCunrefNoCycle", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\gc.nim");
	nimln_(276, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\gc.nim");
	T1_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	T1_ = usrToCell__system_5354(p);
	decRef__system_5399(T1_);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, showVersion__cli_36)(void) {
	nimfr_("showVersion", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	nimln_(61, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	ltltlt___stream_52(stderr, ((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_5));
	nimln_(62, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	ltltlt___stream_52(stderr, ((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_6));
	nimln_(63, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	ltltlt___stream_52(stderr, ((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_7));
	nimln_(64, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	dumpVersionInfo__llvm_3260();
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, setStdin__cli_37)(void) {
	NimStringDesc* T1_;
	nimfr_("setStdin", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	nimln_(67, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	addStdin__parser_5313();
	nimln_(68, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	T1_ = NIM_NIL;
	T1_ = app__core_82.output; app__core_82.output = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_12));
	if (T1_) nimGCunrefNoCycle(T1_);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous___cli_41)(void) {
	nimfr_(":anonymous", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	nimln_(93, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	app__core_82.runJit = NIM_TRUE;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous___cli_42)(NimStringDesc* s) {
	NimStringDesc* T1_;
	nimfr_(":anonymous", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	nimln_(94, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	T1_ = NIM_NIL;
	T1_ = app__core_82.triple; app__core_82.triple = copyStringRC1(s);
	if (T1_) nimGCunrefNoCycle(T1_);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous___cli_44)(void) {
	nimfr_(":anonymous", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	nimln_(95, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	app__core_82.verboseLevel = ((tyEnum_VerboseLevel__xI6367Zu5WWcwaENhMBQFA) 3);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous___cli_45)(void) {
	nimfr_(":anonymous", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	nimln_(96, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	app__core_82.verboseLevel = ((tyEnum_VerboseLevel__xI6367Zu5WWcwaENhMBQFA) 2);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous___cli_46)(void) {
	nimfr_(":anonymous", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	nimln_(97, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	app__core_82.verboseLevel = ((tyEnum_VerboseLevel__xI6367Zu5WWcwaENhMBQFA) 1);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous___cli_47)(void) {
	nimfr_(":anonymous", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	nimln_(98, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	app__core_82.verboseLevel = ((tyEnum_VerboseLevel__xI6367Zu5WWcwaENhMBQFA) 1);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous___cli_48)(NimStringDesc* s) {
	NimStringDesc* T1_;
	nimfr_(":anonymous", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	nimln_(100, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	T1_ = NIM_NIL;
	T1_ = app__core_82.output; app__core_82.output = copyStringRC1(s);
	if (T1_) nimGCunrefNoCycle(T1_);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous___cli_50)(void) {
	nimfr_(":anonymous", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	nimln_(101, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	app__core_82.mode = ((tyEnum_Output__z2pKOFEGp5K7qKOH5sOfcA) 1);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous___cli_51)(void) {
	nimfr_(":anonymous", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	nimln_(102, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	app__core_82.mode = ((tyEnum_Output__z2pKOFEGp5K7qKOH5sOfcA) 2);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous___cli_52)(void) {
	nimfr_(":anonymous", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	nimln_(103, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	app__core_82.mode = ((tyEnum_Output__z2pKOFEGp5K7qKOH5sOfcA) 3);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous___cli_53)(void) {
	nimfr_(":anonymous", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	nimln_(104, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	app__core_82.linker = ((tyEnum_Linker__VnxA6dODl7K2C9a4taFpPxA) 1);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous___cli_54)(void) {
	nimfr_(":anonymous", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	nimln_(105, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	app__core_82.linker = ((tyEnum_Linker__VnxA6dODl7K2C9a4taFpPxA) 0);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous___cli_55)(void) {
	nimfr_(":anonymous", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	nimln_(106, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	app__core_82.mode = ((tyEnum_Output__z2pKOFEGp5K7qKOH5sOfcA) 4);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous___cli_56)(void) {
	nimfr_(":anonymous", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	nimln_(107, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	app__core_82.mode = ((tyEnum_Output__z2pKOFEGp5K7qKOH5sOfcA) 5);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous___cli_57)(void) {
	nimfr_(":anonymous", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	nimln_(108, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	app__core_82.opaquePointerEnabled = NIM_FALSE;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous___cli_58)(void) {
	nimfr_(":anonymous", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	nimln_(109, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	app__core_82.optLevel = ((unsigned int) 0);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous___cli_59)(void) {
	nimfr_(":anonymous", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	nimln_(110, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	app__core_82.optLevel = ((unsigned int) 1);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous___cli_60)(void) {
	nimfr_(":anonymous", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	nimln_(111, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	app__core_82.optLevel = ((unsigned int) 2);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous___cli_61)(void) {
	nimfr_(":anonymous", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	nimln_(112, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	app__core_82.optLevel = ((unsigned int) 3);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous___cli_62)(void) {
	nimfr_(":anonymous", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	nimln_(113, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	app__core_82.optLevel = ((unsigned int) 3);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous___cli_63)(void) {
	nimfr_(":anonymous", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	nimln_(114, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	app__core_82.sizeLevel = ((unsigned int) 1);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous___cli_64)(void) {
	nimfr_(":anonymous", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	nimln_(115, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	app__core_82.sizeLevel = ((unsigned int) 2);
	popFrame();
}
static N_INLINE(int, nimCmpMem)(void* a, void* b, NI size) {
	int result;
	result = (int)0;
	result = memcmp(a, b, ((size_t) (size)));
	return result;
}
static N_INLINE(NIM_BOOL, equalMem__system_1735)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = nimCmpMem(a, b, size);
	result = (T1_ == ((NI32) 0));
	return result;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NI alen;
	NI blen;
	nimfr_("eqStrings", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\strmantle.nim");
{	result = (NIM_BOOL)0;
	nimln_(27, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\strmantle.nim");
	alen = (a ? a->Sup.len : 0);
	nimln_(28, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\strmantle.nim");
	blen = (b ? b->Sup.len : 0);
	nimln_(29, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\strmantle.nim");
	{
		if (!(alen == blen)) goto LA3_;
		nimln_(30, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\strmantle.nim");
		{
			if (!(alen == ((NI) 0))) goto LA7_;
			result = NIM_TRUE;
			goto BeforeRet_;
		}
		LA7_: ;
		nimln_(31, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\strmantle.nim");
		result = equalMem__system_1735(((void*) ((&a->data[((NI) 0)]))), ((void*) ((&b->data[((NI) 0)]))), ((NI) (alen)));
		goto BeforeRet_;
	}
	LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}
static N_INLINE(void, copyMem__system_1727)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	{
		if (!!((src == ((NimStringDesc*) NIM_NIL)))) goto LA3_;
		copyMem__system_1727(((void*) ((&(*dest).data[(*dest).Sup.len]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
		(*dest).Sup.len += (*src).Sup.len;
	}
	LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, setInput__cli_38)(NimStringDesc* s) {
	nimfr_("setInput", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	nimln_(71, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	switch (hashString(s) & 15) {
	case 0: 
if (eqStrings(s, ((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_60))) goto LA2_;
break;
	case 3: 
if (eqStrings(s, ((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_68))) goto LA4_;
break;
	case 5: 
if (eqStrings(s, ((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_63))) goto LA2_;
break;
	case 6: 
if (eqStrings(s, ((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_38))) goto LA2_;
break;
	case 7: 
if (eqStrings(s, ((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_62))) goto LA2_;
if (eqStrings(s, ((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_66))) goto LA3_;
break;
	case 9: 
if (eqStrings(s, ((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_32))) goto LA1_;
break;
	case 10: 
if (eqStrings(s, ((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_65))) goto LA3_;
break;
	case 11: 
if (eqStrings(s, ((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_59))) goto LA1_;
break;
	case 12: 
if (eqStrings(s, ((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_61))) goto LA2_;
if (eqStrings(s, ((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_64))) goto LA2_;
break;
	case 13: 
if (eqStrings(s, ((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_67))) goto LA4_;
break;
	}
	goto LA5_;
	LA1_: ;
	{
		nimln_(73, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
		app__core_82.input = ((tyEnum_Input__4xkeTUPZE5X9azudwRBEOVA) 0);
	}
	goto LA6_;
	LA2_: ;
	{
		nimln_(75, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
		app__core_82.input = ((tyEnum_Input__4xkeTUPZE5X9azudwRBEOVA) 5);
	}
	goto LA6_;
	LA3_: ;
	{
		nimln_(77, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
		app__core_82.input = ((tyEnum_Input__4xkeTUPZE5X9azudwRBEOVA) 1);
	}
	goto LA6_;
	LA4_: ;
	{
		nimln_(79, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
		app__core_82.input = ((tyEnum_Input__4xkeTUPZE5X9azudwRBEOVA) 2);
	}
	goto LA6_;
	LA5_: ;
	{
		NimStringDesc* T12_;
		nimln_(81, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
		error__core_143();
		nimln_(82, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
		T12_ = NIM_NIL;
		T12_ = rawNewString((s ? s->Sup.len : 0) + 29);
appendString(T12_, ((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_69));
appendString(T12_, s);
		ltltlt___stream_52(stderr, T12_);
		nimln_(83, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
		exit(((NI) 0));
	}
	LA6_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasNext__cli_6)(void) {
	NIM_BOOL result;
	NI T1_;
	nimfr_("hasNext", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
{	result = (NIM_BOOL)0;
	nimln_(7, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	T1_ = (options__core_7 ? options__core_7->Sup.len : 0);
	result = (i__cli_5 < T1_);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, get__cli_11)(void) {
	NimStringDesc* result;
	NI TM__9aH0vWwOpIMj7j9c9bzhanzQQ_71;
	nimfr_("get", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	result = NIM_NIL;
	nimln_(10, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	if (i__cli_5 < 0 || i__cli_5 >= (options__core_7 ? options__core_7->Sup.len : 0)){ raiseIndexError2(i__cli_5,(options__core_7 ? options__core_7->Sup.len : 0)-1); }
	result = copyString(options__core_7->data[i__cli_5]);
	nimln_(11, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	if (nimAddInt(i__cli_5, ((NI) 1), &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_71)) { raiseOverflow(); };
	i__cli_5 = (NI)(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_71);
	popFrame();
	return result;
}
static N_INLINE(NimStringDesc*, X5BX5D___pureZunicode_3217)(NimStringDesc* s, tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA x) {
	NimStringDesc* result;
	NI a;
	NI L;
	NI TM__9aH0vWwOpIMj7j9c9bzhanzQQ_72;
	NI TM__9aH0vWwOpIMj7j9c9bzhanzQQ_73;
	NI TM__9aH0vWwOpIMj7j9c9bzhanzQQ_74;
	nimfr_("[]", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system.nim");
	result = NIM_NIL;
	nimln_(2563, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system.nim");
	a = x.a;
	nimln_(2564, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system.nim");
	nimln_(2551, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system.nim");
	if (nimSubInt((s ? s->Sup.len : 0), x.b, &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_72)) { raiseOverflow(); };
	if (nimSubInt((NI)(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_72), a, &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_73)) { raiseOverflow(); };
	if (nimAddInt((NI)(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_73), ((NI) 1), &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_74)) { raiseOverflow(); };
	L = (NI)(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_74);
	nimln_(2565, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system.nim");
	if ((L) < ((NI) 0) || (L) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI(L, ((NI) 0), ((NI) IL64(9223372036854775807))); }
	result = mnewString(((NI) (L)));
	{
		NI i;
		NI i_2;
		i = (NI)0;
		nimln_(119, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\iterators_1.nim");
		i_2 = ((NI) 0);
		{
			nimln_(120, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\iterators_1.nim");
			while (1) {
				NI TM__9aH0vWwOpIMj7j9c9bzhanzQQ_75;
				NI TM__9aH0vWwOpIMj7j9c9bzhanzQQ_76;
				if (!(i_2 < L)) goto LA3;
				nimln_(2566, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system.nim");
				i = i_2;
				if (i < 0 || i >= (result ? result->Sup.len : 0)){ raiseIndexError2(i,(result ? result->Sup.len : 0)-1); }
				if (nimAddInt(i, a, &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_75)) { raiseOverflow(); };
				if ((NI)(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_75) < 0 || (NI)(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_75) >= (s ? s->Sup.len : 0)){ raiseIndexError2((NI)(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_75),(s ? s->Sup.len : 0)-1); }
				result->data[i] = s->data[(NI)(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_75)];
				nimln_(122, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\iterators_1.nim");
				if (nimAddInt(i_2, ((NI) 1), &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_76)) { raiseOverflow(); };
				i_2 = (NI)(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_76);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
	nimSetMem__systemZmemory_7(p, ((int) 0), size);
}
static N_INLINE(tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA, dotdot___stdZenumutils_80)(NI a, NI b) {
	tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA result;
	nimfr_("..", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system.nim");
	nimZeroMem((void*)(&result), sizeof(tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA));
	nimln_(512, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system.nim");
	nimZeroMem((void*)(&result), sizeof(tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA));
	result.a = a;
	result.b = b;
	popFrame();
	return result;
}
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[(*dest).Sup.len] = c;
	(*dest).data[(NI)((*dest).Sup.len + ((NI) 1))] = 0;
	(*dest).Sup.len += ((NI) 1);
}
N_LIB_PRIVATE N_NIMCALL(void, addFile__cli_120)(NimStringDesc* s) {
	nimfr_("addFile", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	nimln_(130, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	addInclude__parser_8129(s, NIM_FALSE);
	popFrame();
}
static N_INLINE(NI, pluspercent___system_696)(NI x, NI y) {
	NI result;
	nimfr_("+%", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\arithmetics.nim");
	result = (NI)0;
	nimln_(403, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\arithmetics.nim");
	nimln_(407, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\arithmetics.nim");
	result = ((NI) ((NU)((NU64)(((NU) (x))) + (NU64)(((NU) (y))))));
	popFrame();
	return result;
}
static N_INLINE(void, incRef__system_5392)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\gc.nim");
	nimln_(231, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\gc.nim");
	(*c).refcount = pluspercent___system_696((*c).refcount, ((NI) 8));
	popFrame();
}
static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\gc.nim");
	nimln_(286, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\gc.nim");
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell__system_5354(src);
		incRef__system_5392(T5_);
	}
	LA3_: ;
	nimln_(287, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\gc.nim");
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell__system_5354((*dest));
		decRef__system_5399(T10_);
	}
	LA8_: ;
	nimln_(288, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\gc.nim");
	(*dest) = src;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, parseCLI__cli_123)(void) {
	NIM_BOOL inputs;
	NI name;
	nimfr_("parseCLI", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	nimln_(135, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	inputs = NIM_FALSE;
	name = (NI)0;
	{
		nimln_(137, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
		while (1) {
			NIM_BOOL T3_;
			NimStringDesc* one;
			T3_ = (NIM_BOOL)0;
			T3_ = hasNext__cli_6();
			if (!T3_) goto LA2;
			nimln_(138, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
			one = get__cli_11();
			nimln_(139, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
			{
				NimStringDesc* o;
				tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA T8_;
				NIM_BOOL has;
				if (((NI) 0) < 0 || ((NI) 0) >= (one ? one->Sup.len : 0)){ raiseIndexError2(((NI) 0),(one ? one->Sup.len : 0)-1); }
				if (!((NU8)(one->data[((NI) 0)]) == (NU8)(45))) goto LA6_;
				nimln_(140, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
				T8_ = dotdot___stdZenumutils_80(((NI) 1), ((NI) 1));
				o = X5BX5D___pureZunicode_3217(one, T8_);
				nimln_(141, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
				has = NIM_FALSE;
				{
					tyTuple__ATBA8nsHhJsFdrZp9beDcqA i;
					NI i_2;
					nimZeroMem((void*)(&i), sizeof(tyTuple__ATBA8nsHhJsFdrZp9beDcqA));
					nimln_(33, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\iterators.nim");
					i_2 = ((NI) 0);
					{
						nimln_(34, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\iterators.nim");
						while (1) {
							NI TM__9aH0vWwOpIMj7j9c9bzhanzQQ_78;
							nimln_(142, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
							i.Field0 = cliOptions__cli_65[(i_2)- 0].Field0;
							i.Field1 = cliOptions__cli_65[(i_2)- 0].Field1;
							i.Field2 = cliOptions__cli_65[(i_2)- 0].Field2;
							i.Field3 = cliOptions__cli_65[(i_2)- 0].Field3;
							{
								nimln_(143, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
								if (!eqStrings(i.Field0, o)) goto LA14_;
								nimln_(144, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
								has = NIM_TRUE;
								nimln_(145, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
								{
									NimStringDesc* s;
									if (!(i.Field1 == ((NI) 1))) goto LA18_;
									nimln_(146, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
									{
										NIM_BOOL T22_;
										T22_ = (NIM_BOOL)0;
										T22_ = hasNext__cli_6();
										if (!(T22_ == NIM_FALSE)) goto LA23_;
										nimln_(147, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
										ltltlt___stream_52(stderr, ((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_77));
										nimln_(148, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
										exit(((NI) 1));
									}
									LA23_: ;
									nimln_(149, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
									s = get__cli_11();
									nimln_(150, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
									((tyProc__W6IXMh2CA4X1rFYGjUb4yg) (i.Field2))(s);
								}
								goto LA16_;
								LA18_: ;
								{
									nimln_(152, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
									i.Field2();
								}
								LA16_: ;
							}
							LA14_: ;
							nimln_(36, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\iterators.nim");
							{
								if (!(((NI) 28) <= ((NI) (i_2)))) goto LA28_;
								goto LA10;
							}
							LA28_: ;
							nimln_(37, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\iterators.nim");
							if (nimAddInt(i_2, ((NI) 1), &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_78)) { raiseOverflow(); };
							if (TM__9aH0vWwOpIMj7j9c9bzhanzQQ_78 < 0 || TM__9aH0vWwOpIMj7j9c9bzhanzQQ_78 > 28){ raiseOverflow(); }
							i_2 = (NI)(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_78);
						}
					} LA10: ;
				}
				nimln_(153, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
				{
					NimStringDesc* T34_;
					if (!(has == NIM_FALSE)) goto LA32_;
					nimln_(154, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
					error__core_143();
					nimln_(155, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
					T34_ = NIM_NIL;
					T34_ = rawNewString((o ? o->Sup.len : 0) + 36);
appendString(T34_, ((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_79));
appendString(T34_, o);
appendChar(T34_, 39);
					ltltlt___stream_52(stderr, T34_);
				}
				LA32_: ;
			}
			goto LA4_;
			LA6_: ;
			{
				nimln_(157, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
				{
					if (!(inputs == NIM_FALSE)) goto LA38_;
					nimln_(158, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
					inputs = NIM_TRUE;
					nimln_(159, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
					name = i__cli_5;
				}
				LA38_: ;
				nimln_(160, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
				addFile__cli_120(one);
			}
			LA4_: ;
		} LA2: ;
	}
	nimln_(161, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	{
		NI T42_;
		T42_ = ((*p__parser_71).fstack ? (*p__parser_71).fstack->Sup.len : 0);
		if (!(T42_ == ((NI) 0))) goto LA43_;
		nimln_(162, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
		error__core_143();
		nimln_(163, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
		ltltlt___stream_52(stderr, ((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_80));
		nimln_(164, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
		exit(((NI) 1));
	}
	LA43_: ;
	nimln_(165, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	{
		NI TM__9aH0vWwOpIMj7j9c9bzhanzQQ_81;
		if (!((app__core_82.output ? app__core_82.output->Sup.len : 0) == ((NI) 0))) goto LA47_;
		nimln_(166, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
		if (nimSubInt(name, ((NI) 1), &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_81)) { raiseOverflow(); };
		i__cli_5 = (NI)(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_81);
		nimln_(167, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
		asgnRef((void**) (&app__core_82.output), get__cli_11());
	}
	LA47_: ;
	nimln_(168, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	newBackend__llvm_3179(app__core_82.output, app__core_82.output);
	nimln_(169, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	switch (app__core_82.mode) {
	case ((tyEnum_Output__z2pKOFEGp5K7qKOH5sOfcA) 0):
	{
		nimln_(171, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
		asgnRef((void**) (&app__core_82.output), resizeString(app__core_82.output, 4));
appendString(app__core_82.output, ((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_82));
	}
	break;
	case ((tyEnum_Output__z2pKOFEGp5K7qKOH5sOfcA) 1):
	{
		nimln_(173, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
		asgnRef((void**) (&app__core_82.output), resizeString(app__core_82.output, 3));
appendString(app__core_82.output, ((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_83));
	}
	break;
	case ((tyEnum_Output__z2pKOFEGp5K7qKOH5sOfcA) 2):
	{
		nimln_(175, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
		asgnRef((void**) (&app__core_82.output), resizeString(app__core_82.output, 3));
appendString(app__core_82.output, ((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_84));
	}
	break;
	case ((tyEnum_Output__z2pKOFEGp5K7qKOH5sOfcA) 3):
	{
		nimln_(177, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
		asgnRef((void**) (&app__core_82.output), resizeString(app__core_82.output, 2));
appendString(app__core_82.output, ((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_85));
	}
	break;
	case ((tyEnum_Output__z2pKOFEGp5K7qKOH5sOfcA) 4):
	{
		nimln_(179, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
		asgnRef((void**) (&app__core_82.output), resizeString(app__core_82.output, 2));
appendString(app__core_82.output, ((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_86));
	}
	break;
	case ((tyEnum_Output__z2pKOFEGp5K7qKOH5sOfcA) 5):
	{
	}
	break;
	}
	nimln_(182, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	addString__parser_5285(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_87), ((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_88));
	popFrame();
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s) {
	NCSTRING result;
	result = (NCSTRING)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (s == ((NimStringDesc*) NIM_NIL));
		if (T3_) goto LA4_;
		T3_ = ((*s).Sup.len == ((NI) 0));
		LA4_: ;
		if (!T3_) goto LA5_;
		result = "";
	}
	goto LA1_;
	LA5_: ;
	{
		result = ((NCSTRING) ((*s).data));
	}
	LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, runLD__cli_22)(NimStringDesc* input, NimStringDesc* path) {
	NimStringDesc* cmd;
	NimStringDesc* T1_;
	int status;
	nimfr_("runLD", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	nimln_(22, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	T1_ = NIM_NIL;
	T1_ = rawNewString((input ? input->Sup.len : 0) + (path ? path->Sup.len : 0) + 12);
appendString(T1_, ((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_89));
appendString(T1_, input);
appendString(T1_, ((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_90));
appendString(T1_, path);
appendChar(T1_, 34);
	cmd = T1_;
	nimln_(23, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	status = system(nimToCStringConv(cmd));
	nimln_(24, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	{
		if (!!((status == ((NI32) 0)))) goto LA4_;
		nimln_(25, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
		error__core_143();
		nimln_(26, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
		ltlt___stream_42(stderr, ((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_91));
		nimln_(27, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
		ltlt___stream_79(stderr, status);
		nimln_(28, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
		ltlt___stream_42(stderr, ((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_92));
	}
	LA4_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, runLLD__cli_31)(NimStringDesc* input, NimStringDesc* output) {
	NimStringDesc* cmd;
	int status;
	nimfr_("runLLD", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	nimln_(49, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	cmd = copyString(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_93));
	nimln_(50, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	cmd = resizeString(cmd, (input ? input->Sup.len : 0) + 0);
appendString(cmd, input);
	nimln_(51, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	cmd = resizeString(cmd, 4);
appendString(cmd, ((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_94));
	nimln_(52, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	cmd = resizeString(cmd, (output ? output->Sup.len : 0) + 0);
appendString(cmd, output);
	nimln_(53, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	status = system(nimToCStringConv(cmd));
	nimln_(54, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	{
		NimStringDesc* T5_;
		if (!!((status == ((NI32) 0)))) goto LA3_;
		nimln_(55, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
		error__core_143();
		nimln_(56, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
		ltlt___stream_42(stderr, ((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_95));
		nimln_(57, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
		T5_ = NIM_NIL;
		T5_ = dollar___systemZdollars_3(((NI) (status)));
		ltlt___stream_42(stderr, T5_);
		nimln_(58, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
		ltlt___stream_42(stderr, ((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_92));
	}
	LA3_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, help__cli_40)(void) {
	nimfr_("help", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	nimln_(120, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	ltltlt___stream_52(stderr, ((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_96));
	{
		tyTuple__ATBA8nsHhJsFdrZp9beDcqA i;
		NI i_2;
		nimZeroMem((void*)(&i), sizeof(tyTuple__ATBA8nsHhJsFdrZp9beDcqA));
		nimln_(33, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\iterators.nim");
		i_2 = ((NI) 0);
		{
			nimln_(34, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\iterators.nim");
			while (1) {
				NI TM__9aH0vWwOpIMj7j9c9bzhanzQQ_98;
				nimln_(121, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
				i.Field0 = cliOptions__cli_65[(i_2)- 0].Field0;
				i.Field1 = cliOptions__cli_65[(i_2)- 0].Field1;
				i.Field2 = cliOptions__cli_65[(i_2)- 0].Field2;
				i.Field3 = cliOptions__cli_65[(i_2)- 0].Field3;
				ltlt___stream_45(stderr, 45);
				ltlt___stream_42(stderr, i.Field0);
				ltlt___stream_42(stderr, ((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_97));
				ltlt___stream_42(stderr, i.Field3);
				nimln_(36, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\iterators.nim");
				{
					if (!(((NI) 28) <= ((NI) (i_2)))) goto LA6_;
					goto LA2;
				}
				LA6_: ;
				nimln_(37, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\iterators.nim");
				if (nimAddInt(i_2, ((NI) 1), &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_98)) { raiseOverflow(); };
				if (TM__9aH0vWwOpIMj7j9c9bzhanzQQ_98 < 0 || TM__9aH0vWwOpIMj7j9c9bzhanzQQ_98 > 28){ raiseOverflow(); }
				i_2 = (NI)(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_98);
			}
		} LA2: ;
	}
	nimln_(126, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	ltlt___stream_45(((struct FILE*) (stderr)), 10);
	nimln_(127, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	showVersion__cli_36();
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, unknown_cliInit000)(void) {
{
	TFrame FR_; FR_.len = 0;

	nimRegisterGlobalMarker(TM__9aH0vWwOpIMj7j9c9bzhanzQQ_3);

}/* preInitProc end */
{
	NimStringDesc* T1_;
	NimStringDesc* T2_;
	NimStringDesc* T3_;
	NimStringDesc* T4_;
	NimStringDesc* T5_;
	NimStringDesc* T6_;
	NimStringDesc* T7_;
	NimStringDesc* T8_;
	NimStringDesc* T9_;
	NimStringDesc* T10_;
	NimStringDesc* T11_;
	NimStringDesc* T12_;
	NimStringDesc* T13_;
	NimStringDesc* T14_;
	NimStringDesc* T15_;
	NimStringDesc* T16_;
	NimStringDesc* T17_;
	NimStringDesc* T18_;
	NimStringDesc* T19_;
	NimStringDesc* T20_;
	NimStringDesc* T21_;
	NimStringDesc* T22_;
	NimStringDesc* T23_;
	NimStringDesc* T24_;
	NimStringDesc* T25_;
	NimStringDesc* T26_;
	NimStringDesc* T27_;
	NimStringDesc* T28_;
	NimStringDesc* T29_;
	NimStringDesc* T30_;
	NimStringDesc* T31_;
	NimStringDesc* T32_;
	NimStringDesc* T33_;
	NimStringDesc* T34_;
	NimStringDesc* T35_;
	NimStringDesc* T36_;
	NimStringDesc* T37_;
	NimStringDesc* T38_;
	NimStringDesc* T39_;
	NimStringDesc* T40_;
	NimStringDesc* T41_;
	NimStringDesc* T42_;
	NimStringDesc* T43_;
	NimStringDesc* T44_;
	NimStringDesc* T45_;
	NimStringDesc* T46_;
	NimStringDesc* T47_;
	NimStringDesc* T48_;
	NimStringDesc* T49_;
	NimStringDesc* T50_;
	NimStringDesc* T51_;
	NimStringDesc* T52_;
	NimStringDesc* T53_;
	NimStringDesc* T54_;
	NimStringDesc* T55_;
	NimStringDesc* T56_;
	NimStringDesc* T57_;
	NimStringDesc* T58_;
	nimfr_("cli", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	nimln_(87, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\cli.nim");
	T1_ = NIM_NIL;
	T1_ = cliOptions__cli_65[0].Field0; cliOptions__cli_65[0].Field0 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_4));
	if (T1_) nimGCunrefNoCycle(T1_);
	cliOptions__cli_65[0].Field1 = ((NI) 0);
	cliOptions__cli_65[0].Field2 = showVersion__cli_36;
	T2_ = NIM_NIL;
	T2_ = cliOptions__cli_65[0].Field3; cliOptions__cli_65[0].Field3 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_8));
	if (T2_) nimGCunrefNoCycle(T2_);
	T3_ = NIM_NIL;
	T3_ = cliOptions__cli_65[1].Field0; cliOptions__cli_65[1].Field0 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_9));
	if (T3_) nimGCunrefNoCycle(T3_);
	cliOptions__cli_65[1].Field1 = ((NI) 0);
	cliOptions__cli_65[1].Field2 = showVersion__cli_36;
	T4_ = NIM_NIL;
	T4_ = cliOptions__cli_65[1].Field3; cliOptions__cli_65[1].Field3 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_8));
	if (T4_) nimGCunrefNoCycle(T4_);
	T5_ = NIM_NIL;
	T5_ = cliOptions__cli_65[2].Field0; cliOptions__cli_65[2].Field0 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_10));
	if (T5_) nimGCunrefNoCycle(T5_);
	cliOptions__cli_65[2].Field1 = ((NI) 0);
	cliOptions__cli_65[2].Field2 = help__cli_40;
	T6_ = NIM_NIL;
	T6_ = cliOptions__cli_65[2].Field3; cliOptions__cli_65[2].Field3 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_10));
	if (T6_) nimGCunrefNoCycle(T6_);
	T7_ = NIM_NIL;
	T7_ = cliOptions__cli_65[3].Field0; cliOptions__cli_65[3].Field0 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_11));
	if (T7_) nimGCunrefNoCycle(T7_);
	cliOptions__cli_65[3].Field1 = ((NI) 0);
	cliOptions__cli_65[3].Field2 = help__cli_40;
	T8_ = NIM_NIL;
	T8_ = cliOptions__cli_65[3].Field3; cliOptions__cli_65[3].Field3 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_10));
	if (T8_) nimGCunrefNoCycle(T8_);
	T9_ = NIM_NIL;
	T9_ = cliOptions__cli_65[4].Field0; cliOptions__cli_65[4].Field0 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_12));
	if (T9_) nimGCunrefNoCycle(T9_);
	cliOptions__cli_65[4].Field1 = ((NI) 0);
	cliOptions__cli_65[4].Field2 = setStdin__cli_37;
	T10_ = NIM_NIL;
	T10_ = cliOptions__cli_65[4].Field3; cliOptions__cli_65[4].Field3 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_13));
	if (T10_) nimGCunrefNoCycle(T10_);
	T11_ = NIM_NIL;
	T11_ = cliOptions__cli_65[5].Field0; cliOptions__cli_65[5].Field0 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_14));
	if (T11_) nimGCunrefNoCycle(T11_);
	cliOptions__cli_65[5].Field1 = ((NI) 0);
	cliOptions__cli_65[5].Field2 = colonanonymous___cli_41;
	T12_ = NIM_NIL;
	T12_ = cliOptions__cli_65[5].Field3; cliOptions__cli_65[5].Field3 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_15));
	if (T12_) nimGCunrefNoCycle(T12_);
	T13_ = NIM_NIL;
	T13_ = cliOptions__cli_65[6].Field0; cliOptions__cli_65[6].Field0 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_16));
	if (T13_) nimGCunrefNoCycle(T13_);
	cliOptions__cli_65[6].Field1 = ((NI) 1);
	cliOptions__cli_65[6].Field2 = ((tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ) (colonanonymous___cli_42));
	T14_ = NIM_NIL;
	T14_ = cliOptions__cli_65[6].Field3; cliOptions__cli_65[6].Field3 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_17));
	if (T14_) nimGCunrefNoCycle(T14_);
	T15_ = NIM_NIL;
	T15_ = cliOptions__cli_65[7].Field0; cliOptions__cli_65[7].Field0 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_18));
	if (T15_) nimGCunrefNoCycle(T15_);
	cliOptions__cli_65[7].Field1 = ((NI) 0);
	cliOptions__cli_65[7].Field2 = colonanonymous___cli_44;
	T16_ = NIM_NIL;
	T16_ = cliOptions__cli_65[7].Field3; cliOptions__cli_65[7].Field3 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_19));
	if (T16_) nimGCunrefNoCycle(T16_);
	T17_ = NIM_NIL;
	T17_ = cliOptions__cli_65[8].Field0; cliOptions__cli_65[8].Field0 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_20));
	if (T17_) nimGCunrefNoCycle(T17_);
	cliOptions__cli_65[8].Field1 = ((NI) 0);
	cliOptions__cli_65[8].Field2 = colonanonymous___cli_45;
	T18_ = NIM_NIL;
	T18_ = cliOptions__cli_65[8].Field3; cliOptions__cli_65[8].Field3 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_21));
	if (T18_) nimGCunrefNoCycle(T18_);
	T19_ = NIM_NIL;
	T19_ = cliOptions__cli_65[9].Field0; cliOptions__cli_65[9].Field0 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_22));
	if (T19_) nimGCunrefNoCycle(T19_);
	cliOptions__cli_65[9].Field1 = ((NI) 0);
	cliOptions__cli_65[9].Field2 = colonanonymous___cli_46;
	T20_ = NIM_NIL;
	T20_ = cliOptions__cli_65[9].Field3; cliOptions__cli_65[9].Field3 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_23));
	if (T20_) nimGCunrefNoCycle(T20_);
	T21_ = NIM_NIL;
	T21_ = cliOptions__cli_65[10].Field0; cliOptions__cli_65[10].Field0 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_24));
	if (T21_) nimGCunrefNoCycle(T21_);
	cliOptions__cli_65[10].Field1 = ((NI) 0);
	cliOptions__cli_65[10].Field2 = colonanonymous___cli_47;
	T22_ = NIM_NIL;
	T22_ = cliOptions__cli_65[10].Field3; cliOptions__cli_65[10].Field3 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_23));
	if (T22_) nimGCunrefNoCycle(T22_);
	T23_ = NIM_NIL;
	T23_ = cliOptions__cli_65[11].Field0; cliOptions__cli_65[11].Field0 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_25));
	if (T23_) nimGCunrefNoCycle(T23_);
	cliOptions__cli_65[11].Field1 = ((NI) 0);
	cliOptions__cli_65[11].Field2 = help__cli_40;
	T24_ = NIM_NIL;
	T24_ = cliOptions__cli_65[11].Field3; cliOptions__cli_65[11].Field3 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_10));
	if (T24_) nimGCunrefNoCycle(T24_);
	T25_ = NIM_NIL;
	T25_ = cliOptions__cli_65[12].Field0; cliOptions__cli_65[12].Field0 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_26));
	if (T25_) nimGCunrefNoCycle(T25_);
	cliOptions__cli_65[12].Field1 = ((NI) 1);
	cliOptions__cli_65[12].Field2 = ((tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ) (colonanonymous___cli_48));
	T26_ = NIM_NIL;
	T26_ = cliOptions__cli_65[12].Field3; cliOptions__cli_65[12].Field3 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_27));
	if (T26_) nimGCunrefNoCycle(T26_);
	T27_ = NIM_NIL;
	T27_ = cliOptions__cli_65[13].Field0; cliOptions__cli_65[13].Field0 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_28));
	if (T27_) nimGCunrefNoCycle(T27_);
	cliOptions__cli_65[13].Field1 = ((NI) 0);
	cliOptions__cli_65[13].Field2 = ((tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ) (colonanonymous___cli_50));
	T28_ = NIM_NIL;
	T28_ = cliOptions__cli_65[13].Field3; cliOptions__cli_65[13].Field3 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_29));
	if (T28_) nimGCunrefNoCycle(T28_);
	T29_ = NIM_NIL;
	T29_ = cliOptions__cli_65[14].Field0; cliOptions__cli_65[14].Field0 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_30));
	if (T29_) nimGCunrefNoCycle(T29_);
	cliOptions__cli_65[14].Field1 = ((NI) 0);
	cliOptions__cli_65[14].Field2 = ((tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ) (colonanonymous___cli_51));
	T30_ = NIM_NIL;
	T30_ = cliOptions__cli_65[14].Field3; cliOptions__cli_65[14].Field3 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_31));
	if (T30_) nimGCunrefNoCycle(T30_);
	T31_ = NIM_NIL;
	T31_ = cliOptions__cli_65[15].Field0; cliOptions__cli_65[15].Field0 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_32));
	if (T31_) nimGCunrefNoCycle(T31_);
	cliOptions__cli_65[15].Field1 = ((NI) 0);
	cliOptions__cli_65[15].Field2 = ((tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ) (colonanonymous___cli_52));
	T32_ = NIM_NIL;
	T32_ = cliOptions__cli_65[15].Field3; cliOptions__cli_65[15].Field3 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_33));
	if (T32_) nimGCunrefNoCycle(T32_);
	T33_ = NIM_NIL;
	T33_ = cliOptions__cli_65[16].Field0; cliOptions__cli_65[16].Field0 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_34));
	if (T33_) nimGCunrefNoCycle(T33_);
	cliOptions__cli_65[16].Field1 = ((NI) 0);
	cliOptions__cli_65[16].Field2 = ((tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ) (colonanonymous___cli_53));
	T34_ = NIM_NIL;
	T34_ = cliOptions__cli_65[16].Field3; cliOptions__cli_65[16].Field3 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_35));
	if (T34_) nimGCunrefNoCycle(T34_);
	T35_ = NIM_NIL;
	T35_ = cliOptions__cli_65[17].Field0; cliOptions__cli_65[17].Field0 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_36));
	if (T35_) nimGCunrefNoCycle(T35_);
	cliOptions__cli_65[17].Field1 = ((NI) 0);
	cliOptions__cli_65[17].Field2 = ((tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ) (colonanonymous___cli_54));
	T36_ = NIM_NIL;
	T36_ = cliOptions__cli_65[17].Field3; cliOptions__cli_65[17].Field3 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_37));
	if (T36_) nimGCunrefNoCycle(T36_);
	T37_ = NIM_NIL;
	T37_ = cliOptions__cli_65[18].Field0; cliOptions__cli_65[18].Field0 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_38));
	if (T37_) nimGCunrefNoCycle(T37_);
	cliOptions__cli_65[18].Field1 = ((NI) 0);
	cliOptions__cli_65[18].Field2 = ((tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ) (colonanonymous___cli_55));
	T38_ = NIM_NIL;
	T38_ = cliOptions__cli_65[18].Field3; cliOptions__cli_65[18].Field3 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_39));
	if (T38_) nimGCunrefNoCycle(T38_);
	T39_ = NIM_NIL;
	T39_ = cliOptions__cli_65[19].Field0; cliOptions__cli_65[19].Field0 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_40));
	if (T39_) nimGCunrefNoCycle(T39_);
	cliOptions__cli_65[19].Field1 = ((NI) 0);
	cliOptions__cli_65[19].Field2 = ((tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ) (colonanonymous___cli_56));
	T40_ = NIM_NIL;
	T40_ = cliOptions__cli_65[19].Field3; cliOptions__cli_65[19].Field3 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_41));
	if (T40_) nimGCunrefNoCycle(T40_);
	T41_ = NIM_NIL;
	T41_ = cliOptions__cli_65[20].Field0; cliOptions__cli_65[20].Field0 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_42));
	if (T41_) nimGCunrefNoCycle(T41_);
	cliOptions__cli_65[20].Field1 = ((NI) 0);
	cliOptions__cli_65[20].Field2 = colonanonymous___cli_57;
	T42_ = NIM_NIL;
	T42_ = cliOptions__cli_65[20].Field3; cliOptions__cli_65[20].Field3 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_43));
	if (T42_) nimGCunrefNoCycle(T42_);
	T43_ = NIM_NIL;
	T43_ = cliOptions__cli_65[21].Field0; cliOptions__cli_65[21].Field0 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_44));
	if (T43_) nimGCunrefNoCycle(T43_);
	cliOptions__cli_65[21].Field1 = ((NI) 0);
	cliOptions__cli_65[21].Field2 = colonanonymous___cli_58;
	T44_ = NIM_NIL;
	T44_ = cliOptions__cli_65[21].Field3; cliOptions__cli_65[21].Field3 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_45));
	if (T44_) nimGCunrefNoCycle(T44_);
	T45_ = NIM_NIL;
	T45_ = cliOptions__cli_65[22].Field0; cliOptions__cli_65[22].Field0 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_46));
	if (T45_) nimGCunrefNoCycle(T45_);
	cliOptions__cli_65[22].Field1 = ((NI) 0);
	cliOptions__cli_65[22].Field2 = colonanonymous___cli_59;
	T46_ = NIM_NIL;
	T46_ = cliOptions__cli_65[22].Field3; cliOptions__cli_65[22].Field3 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_47));
	if (T46_) nimGCunrefNoCycle(T46_);
	T47_ = NIM_NIL;
	T47_ = cliOptions__cli_65[23].Field0; cliOptions__cli_65[23].Field0 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_48));
	if (T47_) nimGCunrefNoCycle(T47_);
	cliOptions__cli_65[23].Field1 = ((NI) 0);
	cliOptions__cli_65[23].Field2 = colonanonymous___cli_60;
	T48_ = NIM_NIL;
	T48_ = cliOptions__cli_65[23].Field3; cliOptions__cli_65[23].Field3 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_49));
	if (T48_) nimGCunrefNoCycle(T48_);
	T49_ = NIM_NIL;
	T49_ = cliOptions__cli_65[24].Field0; cliOptions__cli_65[24].Field0 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_50));
	if (T49_) nimGCunrefNoCycle(T49_);
	cliOptions__cli_65[24].Field1 = ((NI) 0);
	cliOptions__cli_65[24].Field2 = colonanonymous___cli_61;
	T50_ = NIM_NIL;
	T50_ = cliOptions__cli_65[24].Field3; cliOptions__cli_65[24].Field3 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_51));
	if (T50_) nimGCunrefNoCycle(T50_);
	T51_ = NIM_NIL;
	T51_ = cliOptions__cli_65[25].Field0; cliOptions__cli_65[25].Field0 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_52));
	if (T51_) nimGCunrefNoCycle(T51_);
	cliOptions__cli_65[25].Field1 = ((NI) 0);
	cliOptions__cli_65[25].Field2 = colonanonymous___cli_62;
	T52_ = NIM_NIL;
	T52_ = cliOptions__cli_65[25].Field3; cliOptions__cli_65[25].Field3 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_53));
	if (T52_) nimGCunrefNoCycle(T52_);
	T53_ = NIM_NIL;
	T53_ = cliOptions__cli_65[26].Field0; cliOptions__cli_65[26].Field0 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_54));
	if (T53_) nimGCunrefNoCycle(T53_);
	cliOptions__cli_65[26].Field1 = ((NI) 0);
	cliOptions__cli_65[26].Field2 = colonanonymous___cli_63;
	T54_ = NIM_NIL;
	T54_ = cliOptions__cli_65[26].Field3; cliOptions__cli_65[26].Field3 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_55));
	if (T54_) nimGCunrefNoCycle(T54_);
	T55_ = NIM_NIL;
	T55_ = cliOptions__cli_65[27].Field0; cliOptions__cli_65[27].Field0 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_56));
	if (T55_) nimGCunrefNoCycle(T55_);
	cliOptions__cli_65[27].Field1 = ((NI) 0);
	cliOptions__cli_65[27].Field2 = colonanonymous___cli_64;
	T56_ = NIM_NIL;
	T56_ = cliOptions__cli_65[27].Field3; cliOptions__cli_65[27].Field3 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_57));
	if (T56_) nimGCunrefNoCycle(T56_);
	T57_ = NIM_NIL;
	T57_ = cliOptions__cli_65[28].Field0; cliOptions__cli_65[28].Field0 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_58));
	if (T57_) nimGCunrefNoCycle(T57_);
	cliOptions__cli_65[28].Field1 = ((NI) 1);
	cliOptions__cli_65[28].Field2 = setInput__cli_38;
	T58_ = NIM_NIL;
	T58_ = cliOptions__cli_65[28].Field3; cliOptions__cli_65[28].Field3 = copyStringRC1(((NimStringDesc*) &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_70));
	if (T58_) nimGCunrefNoCycle(T58_);
	popFrame();
}
}

N_LIB_PRIVATE N_NIMCALL(void, unknown_cliDatInit000)(void) {
static TNimNode* TM__9aH0vWwOpIMj7j9c9bzhanzQQ_2_4[4];
static TNimNode TM__9aH0vWwOpIMj7j9c9bzhanzQQ_0[5];
NTILstring_int_p_stringT__ATBA8nsHhJsFdrZp9beDcqA_.size = sizeof(tyTuple__ATBA8nsHhJsFdrZp9beDcqA);
NTILstring_int_p_stringT__ATBA8nsHhJsFdrZp9beDcqA_.align = NIM_ALIGNOF(tyTuple__ATBA8nsHhJsFdrZp9beDcqA);
NTILstring_int_p_stringT__ATBA8nsHhJsFdrZp9beDcqA_.kind = 18;
NTILstring_int_p_stringT__ATBA8nsHhJsFdrZp9beDcqA_.base = 0;
TM__9aH0vWwOpIMj7j9c9bzhanzQQ_2_4[0] = &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_0[1];
TM__9aH0vWwOpIMj7j9c9bzhanzQQ_0[1].kind = 1;
TM__9aH0vWwOpIMj7j9c9bzhanzQQ_0[1].offset = offsetof(tyTuple__ATBA8nsHhJsFdrZp9beDcqA, Field0);
TM__9aH0vWwOpIMj7j9c9bzhanzQQ_0[1].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__9aH0vWwOpIMj7j9c9bzhanzQQ_0[1].name = "Field0";
TM__9aH0vWwOpIMj7j9c9bzhanzQQ_2_4[1] = &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_0[2];
TM__9aH0vWwOpIMj7j9c9bzhanzQQ_0[2].kind = 1;
TM__9aH0vWwOpIMj7j9c9bzhanzQQ_0[2].offset = offsetof(tyTuple__ATBA8nsHhJsFdrZp9beDcqA, Field1);
TM__9aH0vWwOpIMj7j9c9bzhanzQQ_0[2].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__9aH0vWwOpIMj7j9c9bzhanzQQ_0[2].name = "Field1";
TM__9aH0vWwOpIMj7j9c9bzhanzQQ_2_4[2] = &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_0[3];
NTIp__T4eqaYlFJYZUv9aG9b1TV0bQ_.size = sizeof(tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ);
NTIp__T4eqaYlFJYZUv9aG9b1TV0bQ_.align = NIM_ALIGNOF(tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ);
NTIp__T4eqaYlFJYZUv9aG9b1TV0bQ_.kind = 25;
NTIp__T4eqaYlFJYZUv9aG9b1TV0bQ_.base = 0;
NTIp__T4eqaYlFJYZUv9aG9b1TV0bQ_.flags = 3;
TM__9aH0vWwOpIMj7j9c9bzhanzQQ_0[3].kind = 1;
TM__9aH0vWwOpIMj7j9c9bzhanzQQ_0[3].offset = offsetof(tyTuple__ATBA8nsHhJsFdrZp9beDcqA, Field2);
TM__9aH0vWwOpIMj7j9c9bzhanzQQ_0[3].typ = (&NTIp__T4eqaYlFJYZUv9aG9b1TV0bQ_);
TM__9aH0vWwOpIMj7j9c9bzhanzQQ_0[3].name = "Field2";
TM__9aH0vWwOpIMj7j9c9bzhanzQQ_2_4[3] = &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_0[4];
TM__9aH0vWwOpIMj7j9c9bzhanzQQ_0[4].kind = 1;
TM__9aH0vWwOpIMj7j9c9bzhanzQQ_0[4].offset = offsetof(tyTuple__ATBA8nsHhJsFdrZp9beDcqA, Field3);
TM__9aH0vWwOpIMj7j9c9bzhanzQQ_0[4].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__9aH0vWwOpIMj7j9c9bzhanzQQ_0[4].name = "Field3";
TM__9aH0vWwOpIMj7j9c9bzhanzQQ_0[0].len = 4; TM__9aH0vWwOpIMj7j9c9bzhanzQQ_0[0].kind = 2; TM__9aH0vWwOpIMj7j9c9bzhanzQQ_0[0].sons = &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_2_4[0];
NTILstring_int_p_stringT__ATBA8nsHhJsFdrZp9beDcqA_.node = &TM__9aH0vWwOpIMj7j9c9bzhanzQQ_0[0];
NTIarrayL48OO5056_Lstring_int_p_stringTT__v2bwnl6nEpojF303kp4mmw_.size = sizeof(tyArray__v2bwnl6nEpojF303kp4mmw);
NTIarrayL48OO5056_Lstring_int_p_stringTT__v2bwnl6nEpojF303kp4mmw_.align = NIM_ALIGNOF(tyArray__v2bwnl6nEpojF303kp4mmw);
NTIarrayL48OO5056_Lstring_int_p_stringTT__v2bwnl6nEpojF303kp4mmw_.kind = 16;
NTIarrayL48OO5056_Lstring_int_p_stringTT__v2bwnl6nEpojF303kp4mmw_.base = (&NTILstring_int_p_stringT__ATBA8nsHhJsFdrZp9beDcqA_);
}

