/* Generated by Nim Compiler v1.6.6 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\Users\林仁傑\source\mingw64\bin\gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN -O3 -fno-strict-aliasing -fno-ident   -IC:\Users\林仁傑\source\nim-1.6.6\lib -IC:\Users\林仁傑\source\Runner\cc -o C:\Users\林仁傑\source\Runner\cc\foo\@meval.nim.c.o C:\Users\林仁傑\source\Runner\cc\foo\@meval.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include "myop.h"
#include <stdio.h>
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct tyObject_ExprcolonObjectType___Ld3U3el9c2u0v5WPEru9aAXw tyObject_ExprcolonObjectType___Ld3U3el9c2u0v5WPEru9aAXw;
typedef struct tyObject_CC__H5XRV6CeEvWKbip2uECzdg tyObject_CC__H5XRV6CeEvWKbip2uECzdg;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tyObject_CTypecolonObjectType___669aUsdhlkr5szWZ35W8JUA tyObject_CTypecolonObjectType___669aUsdhlkr5szWZ35W8JUA;
typedef struct tySequence__F6J9bpZgRLM5S9cNqjuQrSeA tySequence__F6J9bpZgRLM5S9cNqjuQrSeA;
typedef struct tySequence__ZqeB251HneTylbv5m5d76w tySequence__ZqeB251HneTylbv5m5d76w;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_ParsercolonObjectType___lJsmkenZ3vILkn3jj4vS6w tyObject_ParsercolonObjectType___lJsmkenZ3vILkn3jj4vS6w;
typedef struct tySequence__d8M9bCHvPeBbf8w29cp9bhkeA tySequence__d8M9bCHvPeBbf8w29cp9bhkeA;
typedef struct tySequence__iEfejykTAWxucr89a2Y8CFg tySequence__iEfejykTAWxucr89a2Y8CFg;
typedef struct tyObject_TokenVcolonObjectType___lRlrHZo24HpsGbzfojuaDQ tyObject_TokenVcolonObjectType___lRlrHZo24HpsGbzfojuaDQ;
typedef struct tyObject_Table__CtYeAdp7A9axrKUPBwv1xHQ tyObject_Table__CtYeAdp7A9axrKUPBwv1xHQ;
typedef struct tySequence__6SIq7N6Cr9bPurfGdJ2Db3g tySequence__6SIq7N6Cr9bPurfGdJ2Db3g;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ tySequence__6H5Oh5UUvVCLiakt9aTwtUQ;
typedef struct tyObject_HashSet__CD8Dpv0WGmASelVaNSo6zg tyObject_HashSet__CD8Dpv0WGmASelVaNSo6zg;
typedef struct tySequence__4eRCaZmrYLLw2k30GPTiMw tySequence__4eRCaZmrYLLw2k30GPTiMw;
typedef struct tySequence__S2ZCjudIhzhqZE9aEf8xWpQ tySequence__S2ZCjudIhzhqZE9aEf8xWpQ;
typedef struct tySequence__9aQu7KHzT3MCzCPUHElLXhA tySequence__9aQu7KHzT3MCzCPUHElLXhA;
typedef struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack__7fytPA5bBsob6See21YMRA tyObject_GcStack__7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyTuple__ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_StreamcolonObjectType___ADoOUY5nj7w3cjSeMpeq9bg tyObject_StreamcolonObjectType___ADoOUY5nj7w3cjSeMpeq9bg;
typedef struct tyObject_Location__9aHACwS4DmM7l2Os9bhVgD2g tyObject_Location__9aHACwS4DmM7l2Os9bhVgD2g;
typedef struct tyTuple__rEp35MwVsaBzpv9aRM0tLBw tyTuple__rEp35MwVsaBzpv9aRM0tLBw;
typedef struct tyObject_PPMacrocolonObjectType___g0dKpYGo2HbLlgWbQhVXqw tyObject_PPMacrocolonObjectType___g0dKpYGo2HbLlgWbQhVXqw;
typedef struct tyTuple__QeWl6B6ffS4pU6WWrtcrDw tyTuple__QeWl6B6ffS4pU6WWrtcrDw;
typedef struct tyObject_Table__TcTVv1CARFmKztRUfh9bJdA tyObject_Table__TcTVv1CARFmKztRUfh9bJdA;
typedef struct tyObject_Table__9a1wEv2Z3d9cBSBDdbID9bbLg tyObject_Table__9a1wEv2Z3d9cBSBDdbID9bbLg;
typedef struct {
N_NIMCALL_PTR(NI64, ClP_0) (tyObject_ExprcolonObjectType___Ld3U3el9c2u0v5WPEru9aAXw* e, void* ClE_0);
void* ClE_0;
} tyProc__8UNH05QTEiXxPrySuACpwA;
typedef NU8 tyEnum_Output__z2pKOFEGp5K7qKOH5sOfcA;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_VerboseLevel__xI6367Zu5WWcwaENhMBQFA;
typedef NU8 tyEnum_Linker__VnxA6dODl7K2C9a4taFpPxA;
typedef struct {
N_NIMCALL_PTR(unsigned long long, ClP_0) (tyObject_CTypecolonObjectType___669aUsdhlkr5szWZ35W8JUA* ty, void* ClE_0);
void* ClE_0;
} tyProc__jlyesgiGy4lygacwBnHOXw;
typedef struct {
N_NIMCALL_PTR(unsigned long long, ClP_0) (tyObject_CTypecolonObjectType___669aUsdhlkr5szWZ35W8JUA* ty, NI idx, void* ClE_0);
void* ClE_0;
} tyProc__cwiwUf9cOHdpZArzVgCyIGg;
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc__HzVCwACFYM9cx9aV62PdjtuA;
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (tySequence__F6J9bpZgRLM5S9cNqjuQrSeA* tokens, void* ClE_0);
void* ClE_0;
} tyProc__10T9aNjflTPCGrhfwY67CAQ;
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (NimStringDesc* p, void* ClE_0);
void* ClE_0;
} tyProc__k2HFjxisIgDALbEUFojxaQ;
struct tyObject_CC__H5XRV6CeEvWKbip2uECzdg {
tyEnum_Output__z2pKOFEGp5K7qKOH5sOfcA mode;
NIM_BOOL runJit;
unsigned int optLevel;
unsigned int sizeLevel;
unsigned int inlineThreshold;
NimStringDesc* output;
tyEnum_VerboseLevel__xI6367Zu5WWcwaENhMBQFA verboseLevel;
NIM_BOOL opaquePointerEnabled;
tyEnum_Linker__VnxA6dODl7K2C9a4taFpPxA linker;
tySequence__sM4lkSb7zS6F7OVMvW9cffQ* inputs;
unsigned long long pointersize;
tyProc__jlyesgiGy4lygacwBnHOXw getSizeof;
tyProc__cwiwUf9cOHdpZArzVgCyIGg getoffsetof;
tyProc__jlyesgiGy4lygacwBnHOXw getAlignOf;
tyProc__HzVCwACFYM9cx9aV62PdjtuA lex;
tyProc__HzVCwACFYM9cx9aV62PdjtuA cpp;
tyProc__8UNH05QTEiXxPrySuACpwA eval_const_expression;
tyProc__10T9aNjflTPCGrhfwY67CAQ pragma;
tyProc__k2HFjxisIgDALbEUFojxaQ pragmas;
};
typedef NU8 tyEnum_ExprKind__TB3iVeHmrzFlITKM7ipYaQ;
typedef NU8 tyEnum_BinOP__O3wU4d17EOgoxS7drPcQgg;
typedef NU8 tyEnum_UnaryOP__fqj34jPuXAjoaVY0RlcILg;
typedef NU8 tyEnum_PostfixOP__c6hoX24As00qAHY3VE5j9cA;
typedef NU8 tyEnum_CastOp__BfoWHvqCSK5cukgPf0Ms2A;
struct tyObject_ExprcolonObjectType___Ld3U3el9c2u0v5WPEru9aAXw {
tyObject_CTypecolonObjectType___669aUsdhlkr5szWZ35W8JUA* ty;
tyEnum_ExprKind__TB3iVeHmrzFlITKM7ipYaQ k;
union{
struct {tyObject_ExprcolonObjectType___Ld3U3el9c2u0v5WPEru9aAXw* voidexpr;
} _k_1;
struct {tyObject_ExprcolonObjectType___Ld3U3el9c2u0v5WPEru9aAXw* lhs;
tyObject_ExprcolonObjectType___Ld3U3el9c2u0v5WPEru9aAXw* rhs;
tyEnum_BinOP__O3wU4d17EOgoxS7drPcQgg bop;
} _k_2;
struct {tyEnum_UnaryOP__fqj34jPuXAjoaVY0RlcILg uop;
tyObject_ExprcolonObjectType___Ld3U3el9c2u0v5WPEru9aAXw* uoperand;
} _k_3;
struct {tyEnum_PostfixOP__c6hoX24As00qAHY3VE5j9cA pop;
tyObject_ExprcolonObjectType___Ld3U3el9c2u0v5WPEru9aAXw* poperand;
} _k_4;
struct {NI ival;
} _k_5;
struct {NF fval;
} _k_6;
struct {NimStringDesc* str;
} _k_7;
struct {NimStringDesc* sval;
} _k_8;
struct {tySequence__ZqeB251HneTylbv5m5d76w* arr;
} _k_9;
struct {tyObject_ExprcolonObjectType___Ld3U3el9c2u0v5WPEru9aAXw* cond;
tyObject_ExprcolonObjectType___Ld3U3el9c2u0v5WPEru9aAXw* cleft;
tyObject_ExprcolonObjectType___Ld3U3el9c2u0v5WPEru9aAXw* cright;
} _k_10;
struct {tyEnum_CastOp__BfoWHvqCSK5cukgPf0Ms2A castop;
tyObject_ExprcolonObjectType___Ld3U3el9c2u0v5WPEru9aAXw* castval;
} _k_11;
struct {tyObject_ExprcolonObjectType___Ld3U3el9c2u0v5WPEru9aAXw* callfunc;
tySequence__ZqeB251HneTylbv5m5d76w* callargs;
} _k_12;
struct {tyObject_ExprcolonObjectType___Ld3U3el9c2u0v5WPEru9aAXw* left;
tyObject_ExprcolonObjectType___Ld3U3el9c2u0v5WPEru9aAXw* right;
} _k_13;
struct {tyObject_ExprcolonObjectType___Ld3U3el9c2u0v5WPEru9aAXw* obj;
NI idx;
} _k_14;
struct {void* p;
} _k_15;
};
};
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
NI align;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_Table__CtYeAdp7A9axrKUPBwv1xHQ {
tySequence__6SIq7N6Cr9bPurfGdJ2Db3g* data;
NI counter;
};
typedef NU8 tyEnum_ParseFlags__sajOPjv6AdI5er3sDtuCcQ;
struct tyObject_HashSet__CD8Dpv0WGmASelVaNSo6zg {
tySequence__4eRCaZmrYLLw2k30GPTiMw* data;
NI counter;
};
struct tyObject_ParsercolonObjectType___lJsmkenZ3vILkn3jj4vS6w {
tyObject_CTypecolonObjectType___669aUsdhlkr5szWZ35W8JUA* currentfunctionRet;
tyObject_CTypecolonObjectType___669aUsdhlkr5szWZ35W8JUA* currentInitTy;
tySequence__d8M9bCHvPeBbf8w29cp9bhkeA* fstack;
tySequence__sM4lkSb7zS6F7OVMvW9cffQ* filenamestack;
tySequence__sM4lkSb7zS6F7OVMvW9cffQ* pathstack;
tySequence__iEfejykTAWxucr89a2Y8CFg* locstack;
tyObject_TokenVcolonObjectType___lRlrHZo24HpsGbzfojuaDQ* tok;
NI line;
NI col;
NIM_CHAR c;
NIM_BOOL want_expr;
NU16 lastc;
NimStringDesc* filename;
NimStringDesc* path;
tyObject_Table__CtYeAdp7A9axrKUPBwv1xHQ macros;
tyEnum_ParseFlags__sajOPjv6AdI5er3sDtuCcQ flags;
tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* ppstack;
NIM_BOOL ok;
tyObject_HashSet__CD8Dpv0WGmASelVaNSo6zg onces;
tyObject_HashSet__CD8Dpv0WGmASelVaNSo6zg expansion_list;
tySequence__S2ZCjudIhzhqZE9aEf8xWpQ* lables;
tySequence__9aQu7KHzT3MCzCPUHElLXhA* tags;
tySequence__9aQu7KHzT3MCzCPUHElLXhA* typedefs;
tySequence__F6J9bpZgRLM5S9cNqjuQrSeA* tokenq;
NI counter;
tyObject_CTypecolonObjectType___669aUsdhlkr5szWZ35W8JUA* retTy;
NIM_BOOL type_error;
NIM_BOOL eval_error;
NIM_BOOL parse_error;
NIM_BOOL bad_error;
};
typedef NimStringDesc* tyArray__nHXaesL0DJZHyVS07ARPRA[1];
typedef N_CLOSURE_PTR(NI64, TM__K5VqFIgwzZfjyHdregweGA_24) (tyObject_ExprcolonObjectType___Ld3U3el9c2u0v5WPEru9aAXw* e, void* ClE_0);
struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack__7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ* tyArray__SPr7N6UKfuF549bNPiUvSRw[256];
typedef NU32 tyArray__BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* tyArray__N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray__N1u1nqOgmuJN9cSZrnMHgOQ tyArray__B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw* tyArray__lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA {
tyArray__lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* tyArray__0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw {
tyArray__0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyArray__LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray__LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray__SPr7N6UKfuF549bNPiUvSRw freeSmallChunks;
NU32 flBitmap;
tyArray__BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray__B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack__7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
NI zctThreshold;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct tyObject_Location__9aHACwS4DmM7l2Os9bhVgD2g {
NI line;
NI col;
};
struct tyTuple__rEp35MwVsaBzpv9aRM0tLBw {
NI Field0;
NimStringDesc* Field1;
tyObject_PPMacrocolonObjectType___g0dKpYGo2HbLlgWbQhVXqw* Field2;
};
struct tyTuple__QeWl6B6ffS4pU6WWrtcrDw {
NI Field0;
NimStringDesc* Field1;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence__F6J9bpZgRLM5S9cNqjuQrSeA {
  TGenericSeq Sup;
  tyObject_TokenVcolonObjectType___lRlrHZo24HpsGbzfojuaDQ* data[SEQ_DECL_SIZE];
};
struct tySequence__ZqeB251HneTylbv5m5d76w {
  TGenericSeq Sup;
  tyObject_ExprcolonObjectType___Ld3U3el9c2u0v5WPEru9aAXw* data[SEQ_DECL_SIZE];
};
struct tySequence__d8M9bCHvPeBbf8w29cp9bhkeA {
  TGenericSeq Sup;
  tyObject_StreamcolonObjectType___ADoOUY5nj7w3cjSeMpeq9bg* data[SEQ_DECL_SIZE];
};
struct tySequence__iEfejykTAWxucr89a2Y8CFg {
  TGenericSeq Sup;
  tyObject_Location__9aHACwS4DmM7l2Os9bhVgD2g data[SEQ_DECL_SIZE];
};
struct tySequence__6SIq7N6Cr9bPurfGdJ2Db3g {
  TGenericSeq Sup;
  tyTuple__rEp35MwVsaBzpv9aRM0tLBw data[SEQ_DECL_SIZE];
};
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ {
  TGenericSeq Sup;
  NU8 data[SEQ_DECL_SIZE];
};
struct tySequence__4eRCaZmrYLLw2k30GPTiMw {
  TGenericSeq Sup;
  tyTuple__QeWl6B6ffS4pU6WWrtcrDw data[SEQ_DECL_SIZE];
};
struct tySequence__S2ZCjudIhzhqZE9aEf8xWpQ {
  TGenericSeq Sup;
  tyObject_Table__TcTVv1CARFmKztRUfh9bJdA* data[SEQ_DECL_SIZE];
};
struct tySequence__9aQu7KHzT3MCzCPUHElLXhA {
  TGenericSeq Sup;
  tyObject_Table__9a1wEv2Z3d9cBSBDdbID9bbLg* data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(NI64, evali__eval_21)(tyObject_ExprcolonObjectType___Ld3U3el9c2u0v5WPEru9aAXw* e);
N_LIB_PRIVATE N_NOINLINE(void, raiseFieldError2)(NimStringDesc* f, NimStringDesc* discVal);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, reprDiscriminant)(NI e, TNimType* typ);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(NIM_BOOL, nimDivInt64)(NI64 a, NI64 b, NI64* res);
N_LIB_PRIVATE N_NIMCALL(void, eval_error__eval_15)(NimStringDesc* msg);
static N_INLINE(void, writeLine__core_2838)(FILE* f, NimStringDesc** x, NI xLen_0);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
N_LIB_PRIVATE N_NIMCALL(void, write__systemZio_220)(FILE* f, NimStringDesc* s);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem__system_1727)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar___systemZdollars_3)(NI x);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar___core_498)(tyObject_ExprcolonObjectType___Ld3U3el9c2u0v5WPEru9aAXw* e);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef__system_5358)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NI, pluspercent___system_696)(NI x, NI y);
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__system_5320)(void* usr);
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y);
static N_INLINE(void, decRef__system_5365)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NIM_BOOL, ltpercent___system_1005)(NI x, NI y);
static N_INLINE(void, rtlAddZCT__system_5363)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT__system_5314)(tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
STRING_LITERAL(TM__K5VqFIgwzZfjyHdregweGA_2, "field \'bop\' is not accessible for type \'Expr\' using \'k = ", 57);
extern TNimType NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_;
STRING_LITERAL(TM__K5VqFIgwzZfjyHdregweGA_3, "field \'lhs\' is not accessible for type \'Expr\' using \'k = ", 57);
STRING_LITERAL(TM__K5VqFIgwzZfjyHdregweGA_4, "field \'rhs\' is not accessible for type \'Expr\' using \'k = ", 57);
STRING_LITERAL(TM__K5VqFIgwzZfjyHdregweGA_10, "\012", 1);
STRING_LITERAL(TM__K5VqFIgwzZfjyHdregweGA_11, "\033[34m", 5);
STRING_LITERAL(TM__K5VqFIgwzZfjyHdregweGA_12, ": ", 2);
STRING_LITERAL(TM__K5VqFIgwzZfjyHdregweGA_13, ": parse error: ", 15);
STRING_LITERAL(TM__K5VqFIgwzZfjyHdregweGA_14, "\033[0m", 4);
STRING_LITERAL(TM__K5VqFIgwzZfjyHdregweGA_15, "cannot eval constant-expression: ", 33);
STRING_LITERAL(TM__K5VqFIgwzZfjyHdregweGA_16, "field \'uop\' is not accessible for type \'Expr\' using \'k = ", 57);
STRING_LITERAL(TM__K5VqFIgwzZfjyHdregweGA_17, "field \'uoperand\' is not accessible for type \'Expr\' using \'k = ", 62);
STRING_LITERAL(TM__K5VqFIgwzZfjyHdregweGA_18, "cannot eval constant-expression: bad unary operator: ", 53);
STRING_LITERAL(TM__K5VqFIgwzZfjyHdregweGA_19, "field \'ival\' is not accessible for type \'Expr\' using \'k = ", 58);
STRING_LITERAL(TM__K5VqFIgwzZfjyHdregweGA_20, "floating constant in constant-expression", 40);
STRING_LITERAL(TM__K5VqFIgwzZfjyHdregweGA_21, "field \'cond\' is not accessible for type \'Expr\' using \'k = ", 58);
STRING_LITERAL(TM__K5VqFIgwzZfjyHdregweGA_22, "field \'cleft\' is not accessible for type \'Expr\' using \'k = ", 59);
STRING_LITERAL(TM__K5VqFIgwzZfjyHdregweGA_23, "field \'cright\' is not accessible for type \'Expr\' using \'k = ", 60);
extern tyObject_CC__H5XRV6CeEvWKbip2uECzdg app__core_2785;
extern tyObject_ParsercolonObjectType___lJsmkenZ3vILkn3jj4vS6w* p__parser_67;
extern tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ gch__system_5267;
static N_INLINE(NIM_BOOL, nimDivInt64)(NI64 a, NI64 b, NI64* res) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a == (IL64(-9223372036854775807) - IL64(1)));
		if (!(T3_)) goto LA4_;
		T3_ = (b == IL64(-1));
		LA4_: ;
		if (!T3_) goto LA5_;
		result = NIM_TRUE;
	}
	goto LA1_;
	LA5_: ;
	{
		(*res) = (NI64)(a / b);
	}
	LA1_: ;
	return result;
}
static N_INLINE(void, writeLine__core_2838)(FILE* f, NimStringDesc** x, NI xLen_0) {
	{
		NimStringDesc** i;
		NI i_2;
		i = (NimStringDesc**)0;
		i_2 = ((NI) 0);
		{
			while (1) {
				NI TM__K5VqFIgwzZfjyHdregweGA_9;
				if (!(i_2 < xLen_0)) goto LA3;
				if (i_2 < 0 || i_2 >= xLen_0){ raiseIndexError2(i_2,xLen_0-1); }
				i = (&x[i_2]);
				write__systemZio_220(f, (*i));
				if (nimAddInt(i_2, ((NI) 1), &TM__K5VqFIgwzZfjyHdregweGA_9)) { raiseOverflow(); };
				i_2 = (NI)(TM__K5VqFIgwzZfjyHdregweGA_9);
			} LA3: ;
		}
	}
	write__systemZio_220(f, ((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_10));
}
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
	nimSetMem__systemZmemory_7(p, ((int) 0), size);
}
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}
static N_INLINE(void, copyMem__system_1727)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	{
		if (!!((src == ((NimStringDesc*) NIM_NIL)))) goto LA3_;
		copyMem__system_1727(((void*) ((&(*dest).data[(*dest).Sup.len]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
		(*dest).Sup.len += (*src).Sup.len;
	}
	LA3_: ;
}
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[(*dest).Sup.len] = c;
	(*dest).data[(NI)((*dest).Sup.len + ((NI) 1))] = 0;
	(*dest).Sup.len += ((NI) 1);
}
N_LIB_PRIVATE N_NIMCALL(void, eval_error__eval_15)(NimStringDesc* msg) {
	{
		tyArray__nHXaesL0DJZHyVS07ARPRA T5_;
		NimStringDesc* T6_;
		NimStringDesc* T7_;
		NimStringDesc* T8_;
		if (!((*p__parser_67).eval_error == NIM_FALSE)) goto LA3_;
		nimZeroMem((void*)T5_, sizeof(tyArray__nHXaesL0DJZHyVS07ARPRA));
		T6_ = NIM_NIL;
		T7_ = NIM_NIL;
		T7_ = dollar___systemZdollars_3((*p__parser_67).line);
		T8_ = NIM_NIL;
		T8_ = dollar___systemZdollars_3((*p__parser_67).col);
		T6_ = rawNewString(((*p__parser_67).filename ? (*p__parser_67).filename->Sup.len : 0) + (T7_ ? T7_->Sup.len : 0) + (T8_ ? T8_->Sup.len : 0) + (msg ? msg->Sup.len : 0) + 27);
appendString(T6_, ((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_11));
appendString(T6_, (*p__parser_67).filename);
appendString(T6_, ((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_12));
appendString(T6_, T7_);
appendChar(T6_, 46);
appendString(T6_, T8_);
appendString(T6_, ((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_13));
appendString(T6_, msg);
appendString(T6_, ((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_14));
		T5_[0] = T6_;
		writeLine__core_2838(stderr, T5_, 1);
		(*p__parser_67).eval_error = NIM_TRUE;
	}
	LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(NI64, evali__eval_21)(tyObject_ExprcolonObjectType___Ld3U3el9c2u0v5WPEru9aAXw* e) {
	NI64 result;
	result = (NI64)0;
	switch ((*e).k) {
	case ((tyEnum_ExprKind__TB3iVeHmrzFlITKM7ipYaQ) 0):
	{
		if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 		{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_2), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
		switch ((*e)._k_2.bop) {
		case ((tyEnum_BinOP__O3wU4d17EOgoxS7drPcQgg) 2):
		{
			NI64 T3_;
			NI64 T4_;
			NI64 TM__K5VqFIgwzZfjyHdregweGA_5;
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_3), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
			T3_ = (NI64)0;
			T3_ = evali__eval_21((*e)._k_2.lhs);
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_4), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
			T4_ = (NI64)0;
			T4_ = evali__eval_21((*e)._k_2.rhs);
			if (nimAddInt64(T3_, T4_, &TM__K5VqFIgwzZfjyHdregweGA_5)) { raiseOverflow(); };
			result = (NI64)(TM__K5VqFIgwzZfjyHdregweGA_5);
		}
		break;
		case ((tyEnum_BinOP__O3wU4d17EOgoxS7drPcQgg) 5):
		{
			NI64 T6_;
			NI64 T7_;
			NI64 TM__K5VqFIgwzZfjyHdregweGA_6;
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_3), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
			T6_ = (NI64)0;
			T6_ = evali__eval_21((*e)._k_2.lhs);
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_4), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
			T7_ = (NI64)0;
			T7_ = evali__eval_21((*e)._k_2.rhs);
			if (nimSubInt64(T6_, T7_, &TM__K5VqFIgwzZfjyHdregweGA_6)) { raiseOverflow(); };
			result = (NI64)(TM__K5VqFIgwzZfjyHdregweGA_6);
		}
		break;
		case ((tyEnum_BinOP__O3wU4d17EOgoxS7drPcQgg) 8):
		{
			NI64 T9_;
			NI64 T10_;
			NI64 TM__K5VqFIgwzZfjyHdregweGA_7;
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_3), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
			T9_ = (NI64)0;
			T9_ = evali__eval_21((*e)._k_2.lhs);
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_4), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
			T10_ = (NI64)0;
			T10_ = evali__eval_21((*e)._k_2.rhs);
			if (nimMulInt64(T9_, T10_, &TM__K5VqFIgwzZfjyHdregweGA_7)) { raiseOverflow(); };
			result = (NI64)(TM__K5VqFIgwzZfjyHdregweGA_7);
		}
		break;
		case ((tyEnum_BinOP__O3wU4d17EOgoxS7drPcQgg) 1):
		{
			NI64 T12_;
			NI64 T13_;
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_3), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
			T12_ = (NI64)0;
			T12_ = evali__eval_21((*e)._k_2.lhs);
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_4), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
			T13_ = (NI64)0;
			T13_ = evali__eval_21((*e)._k_2.rhs);
			result = ((NI64) ((NU64)((NU64)(((NU64) (T12_))) + (NU64)(((NU64) (T13_))))));
		}
		break;
		case ((tyEnum_BinOP__O3wU4d17EOgoxS7drPcQgg) 4):
		{
			NI64 T15_;
			NI64 T16_;
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_3), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
			T15_ = (NI64)0;
			T15_ = evali__eval_21((*e)._k_2.lhs);
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_4), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
			T16_ = (NI64)0;
			T16_ = evali__eval_21((*e)._k_2.rhs);
			result = ((NI64) ((NU64)((NU64)(((NU64) (T15_))) - (NU64)(((NU64) (T16_))))));
		}
		break;
		case ((tyEnum_BinOP__O3wU4d17EOgoxS7drPcQgg) 7):
		{
			NI64 T18_;
			NI64 T19_;
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_3), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
			T18_ = (NI64)0;
			T18_ = evali__eval_21((*e)._k_2.lhs);
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_4), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
			T19_ = (NI64)0;
			T19_ = evali__eval_21((*e)._k_2.rhs);
			result = ((NI64) ((NU64)((NU64)(((NU64) (T18_))) * (NU64)(((NU64) (T19_))))));
		}
		break;
		case ((tyEnum_BinOP__O3wU4d17EOgoxS7drPcQgg) 10):
		{
			NI64 T21_;
			NI64 T22_;
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_3), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
			T21_ = (NI64)0;
			T21_ = evali__eval_21((*e)._k_2.lhs);
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_4), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
			T22_ = (NI64)0;
			T22_ = evali__eval_21((*e)._k_2.rhs);
			result = ((NI64) ((NU64)((NU64)(((NU64) (T21_))) / (NU64)(((NU64) (T22_))))));
		}
		break;
		case ((tyEnum_BinOP__O3wU4d17EOgoxS7drPcQgg) 11):
		{
			NI64 T24_;
			NI64 T25_;
			NI64 TM__K5VqFIgwzZfjyHdregweGA_8;
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_3), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
			T24_ = (NI64)0;
			T24_ = evali__eval_21((*e)._k_2.lhs);
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_4), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
			T25_ = (NI64)0;
			T25_ = evali__eval_21((*e)._k_2.rhs);
			if (T25_ == 0){ raiseDivByZero(); }
			if (nimDivInt64(T24_, T25_, &TM__K5VqFIgwzZfjyHdregweGA_8)) { raiseOverflow(); };
			result = (NI64)(TM__K5VqFIgwzZfjyHdregweGA_8);
		}
		break;
		case ((tyEnum_BinOP__O3wU4d17EOgoxS7drPcQgg) 13):
		{
			NI64 T27_;
			NI64 T28_;
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_3), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
			T27_ = (NI64)0;
			T27_ = evali__eval_21((*e)._k_2.lhs);
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_4), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
			T28_ = (NI64)0;
			T28_ = evali__eval_21((*e)._k_2.rhs);
			result = ((NI64) ((NU64)((NU64)(((NU64) (T27_))) % (NU64)(((NU64) (T28_))))));
		}
		break;
		case ((tyEnum_BinOP__O3wU4d17EOgoxS7drPcQgg) 16):
		{
			NI64 T30_;
			NI64 T31_;
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_3), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
			T30_ = (NI64)0;
			T30_ = evali__eval_21((*e)._k_2.lhs);
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_4), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
			T31_ = (NI64)0;
			T31_ = evali__eval_21((*e)._k_2.rhs);
			result = ((NI64) ((NU64)((NU64)(((NU64) (T30_))) >> (NU64)(((NU64) (T31_))))));
		}
		break;
		case ((tyEnum_BinOP__O3wU4d17EOgoxS7drPcQgg) 17):
		{
			NI64 T33_;
			NI64 T34_;
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_3), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
			T33_ = (NI64)0;
			T33_ = evali__eval_21((*e)._k_2.lhs);
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_4), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
			T34_ = (NI64)0;
			T34_ = evali__eval_21((*e)._k_2.rhs);
			result = (NI64)((NI64)(T33_) >> (NU64)(T34_));
		}
		break;
		case ((tyEnum_BinOP__O3wU4d17EOgoxS7drPcQgg) 27):
		{
			NI T36_;
			T36_ = (NI)0;
			{
				NI64 T39_;
				NI64 T40_;
				if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 				{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_3), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
				T39_ = (NI64)0;
				T39_ = evali__eval_21((*e)._k_2.lhs);
				if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 				{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_4), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
				T40_ = (NI64)0;
				T40_ = evali__eval_21((*e)._k_2.rhs);
				if (!(T39_ == T40_)) goto LA41_;
				T36_ = ((NI) 1);
			}
			goto LA37_;
			LA41_: ;
			{
				T36_ = ((NI) 0);
			}
			LA37_: ;
			result = ((NI64) (T36_));
		}
		break;
		case ((tyEnum_BinOP__O3wU4d17EOgoxS7drPcQgg) 28):
		{
			NI T45_;
			T45_ = (NI)0;
			{
				NI64 T48_;
				NI64 T49_;
				if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 				{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_3), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
				T48_ = (NI64)0;
				T48_ = evali__eval_21((*e)._k_2.lhs);
				if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 				{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_4), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
				T49_ = (NI64)0;
				T49_ = evali__eval_21((*e)._k_2.rhs);
				if (!!((T48_ == T49_))) goto LA50_;
				T45_ = ((NI) 1);
			}
			goto LA46_;
			LA50_: ;
			{
				T45_ = ((NI) 0);
			}
			LA46_: ;
			result = ((NI64) (T45_));
		}
		break;
		case ((tyEnum_BinOP__O3wU4d17EOgoxS7drPcQgg) 34):
		{
			NI T54_;
			T54_ = (NI)0;
			{
				NI64 T57_;
				NI64 T58_;
				if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 				{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_4), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
				T57_ = (NI64)0;
				T57_ = evali__eval_21((*e)._k_2.rhs);
				if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 				{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_3), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
				T58_ = (NI64)0;
				T58_ = evali__eval_21((*e)._k_2.lhs);
				if (!(T57_ <= T58_)) goto LA59_;
				T54_ = ((NI) 1);
			}
			goto LA55_;
			LA59_: ;
			{
				T54_ = ((NI) 0);
			}
			LA55_: ;
			result = ((NI64) (T54_));
		}
		break;
		case ((tyEnum_BinOP__O3wU4d17EOgoxS7drPcQgg) 33):
		{
			NI T63_;
			T63_ = (NI)0;
			{
				NI64 T66_;
				NI64 T67_;
				if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 				{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_4), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
				T66_ = (NI64)0;
				T66_ = evali__eval_21((*e)._k_2.rhs);
				if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 				{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_3), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
				T67_ = (NI64)0;
				T67_ = evali__eval_21((*e)._k_2.lhs);
				if (!(T66_ < T67_)) goto LA68_;
				T63_ = ((NI) 1);
			}
			goto LA64_;
			LA68_: ;
			{
				T63_ = ((NI) 0);
			}
			LA64_: ;
			result = ((NI64) (T63_));
		}
		break;
		case ((tyEnum_BinOP__O3wU4d17EOgoxS7drPcQgg) 36):
		{
			NI T72_;
			T72_ = (NI)0;
			{
				NI64 T75_;
				NI64 T76_;
				if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 				{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_3), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
				T75_ = (NI64)0;
				T75_ = evali__eval_21((*e)._k_2.lhs);
				if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 				{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_4), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
				T76_ = (NI64)0;
				T76_ = evali__eval_21((*e)._k_2.rhs);
				if (!(T75_ <= T76_)) goto LA77_;
				T72_ = ((NI) 1);
			}
			goto LA73_;
			LA77_: ;
			{
				T72_ = ((NI) 0);
			}
			LA73_: ;
			result = ((NI64) (T72_));
		}
		break;
		case ((tyEnum_BinOP__O3wU4d17EOgoxS7drPcQgg) 35):
		{
			NI T81_;
			T81_ = (NI)0;
			{
				NI64 T84_;
				NI64 T85_;
				if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 				{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_3), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
				T84_ = (NI64)0;
				T84_ = evali__eval_21((*e)._k_2.lhs);
				if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 				{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_4), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
				T85_ = (NI64)0;
				T85_ = evali__eval_21((*e)._k_2.rhs);
				if (!(T84_ < T85_)) goto LA86_;
				T81_ = ((NI) 1);
			}
			goto LA82_;
			LA86_: ;
			{
				T81_ = ((NI) 0);
			}
			LA82_: ;
			result = ((NI64) (T81_));
		}
		break;
		case ((tyEnum_BinOP__O3wU4d17EOgoxS7drPcQgg) 30):
		{
			NI T90_;
			T90_ = (NI)0;
			{
				NI64 T93_;
				NI64 T94_;
				if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 				{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_4), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
				T93_ = (NI64)0;
				T93_ = evali__eval_21((*e)._k_2.rhs);
				if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 				{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_3), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
				T94_ = (NI64)0;
				T94_ = evali__eval_21((*e)._k_2.lhs);
				if (!((NU64)(((NU64) (T93_))) <= (NU64)(((NU64) (T94_))))) goto LA95_;
				T90_ = ((NI) 1);
			}
			goto LA91_;
			LA95_: ;
			{
				T90_ = ((NI) 0);
			}
			LA91_: ;
			result = ((NI64) (T90_));
		}
		break;
		case ((tyEnum_BinOP__O3wU4d17EOgoxS7drPcQgg) 29):
		{
			NI T99_;
			T99_ = (NI)0;
			{
				NI64 T102_;
				NI64 T103_;
				if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 				{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_4), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
				T102_ = (NI64)0;
				T102_ = evali__eval_21((*e)._k_2.rhs);
				if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 				{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_3), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
				T103_ = (NI64)0;
				T103_ = evali__eval_21((*e)._k_2.lhs);
				if (!((NU64)(((NU64) (T102_))) < (NU64)(((NU64) (T103_))))) goto LA104_;
				T99_ = ((NI) 1);
			}
			goto LA100_;
			LA104_: ;
			{
				T99_ = ((NI) 0);
			}
			LA100_: ;
			result = ((NI64) (T99_));
		}
		break;
		case ((tyEnum_BinOP__O3wU4d17EOgoxS7drPcQgg) 32):
		{
			NI T108_;
			T108_ = (NI)0;
			{
				NI64 T111_;
				NI64 T112_;
				if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 				{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_3), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
				T111_ = (NI64)0;
				T111_ = evali__eval_21((*e)._k_2.lhs);
				if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 				{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_4), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
				T112_ = (NI64)0;
				T112_ = evali__eval_21((*e)._k_2.rhs);
				if (!((NU64)(((NU64) (T111_))) <= (NU64)(((NU64) (T112_))))) goto LA113_;
				T108_ = ((NI) 1);
			}
			goto LA109_;
			LA113_: ;
			{
				T108_ = ((NI) 0);
			}
			LA109_: ;
			result = ((NI64) (T108_));
		}
		break;
		case ((tyEnum_BinOP__O3wU4d17EOgoxS7drPcQgg) 31):
		{
			NI T117_;
			T117_ = (NI)0;
			{
				NI64 T120_;
				NI64 T121_;
				if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 				{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_3), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
				T120_ = (NI64)0;
				T120_ = evali__eval_21((*e)._k_2.lhs);
				if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 				{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_4), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
				T121_ = (NI64)0;
				T121_ = evali__eval_21((*e)._k_2.rhs);
				if (!((NU64)(((NU64) (T120_))) < (NU64)(((NU64) (T121_))))) goto LA122_;
				T117_ = ((NI) 1);
			}
			goto LA118_;
			LA122_: ;
			{
				T117_ = ((NI) 0);
			}
			LA118_: ;
			result = ((NI64) (T117_));
		}
		break;
		case ((tyEnum_BinOP__O3wU4d17EOgoxS7drPcQgg) 19):
		{
			NI64 T126_;
			NI64 T127_;
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_3), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
			T126_ = (NI64)0;
			T126_ = evali__eval_21((*e)._k_2.lhs);
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_4), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
			T127_ = (NI64)0;
			T127_ = evali__eval_21((*e)._k_2.rhs);
			result = (NI64)(T126_ & T127_);
		}
		break;
		case ((tyEnum_BinOP__O3wU4d17EOgoxS7drPcQgg) 20):
		{
			NI64 T129_;
			NI64 T130_;
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_3), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
			T129_ = (NI64)0;
			T129_ = evali__eval_21((*e)._k_2.lhs);
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_4), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
			T130_ = (NI64)0;
			T130_ = evali__eval_21((*e)._k_2.rhs);
			result = (NI64)(T129_ ^ T130_);
		}
		break;
		case ((tyEnum_BinOP__O3wU4d17EOgoxS7drPcQgg) 21):
		{
			NI64 T132_;
			NI64 T133_;
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_3), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
			T132_ = (NI64)0;
			T132_ = evali__eval_21((*e)._k_2.lhs);
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_4), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
			T133_ = (NI64)0;
			T133_ = evali__eval_21((*e)._k_2.rhs);
			result = (NI64)(T132_ | T133_);
		}
		break;
		case ((tyEnum_BinOP__O3wU4d17EOgoxS7drPcQgg) 22):
		{
			NI64 T135_;
			NI64 T136_;
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_3), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
			T135_ = (NI64)0;
			T135_ = evali__eval_21((*e)._k_2.lhs);
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_4), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
			T136_ = (NI64)0;
			T136_ = evali__eval_21((*e)._k_2.rhs);
			result = myopand(T135_, T136_);
		}
		break;
		case ((tyEnum_BinOP__O3wU4d17EOgoxS7drPcQgg) 23):
		{
			NI64 T138_;
			NI64 T139_;
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_3), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
			T138_ = (NI64)0;
			T138_ = evali__eval_21((*e)._k_2.lhs);
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_4), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
			T139_ = (NI64)0;
			T139_ = evali__eval_21((*e)._k_2.rhs);
			result = myopor(T138_, T139_);
		}
		break;
		default:
		{
			NimStringDesc* T141_;
			NimStringDesc* T142_;
			T141_ = NIM_NIL;
			T142_ = NIM_NIL;
			T142_ = dollar___core_498(e);
			T141_ = rawNewString((T142_ ? T142_->Sup.len : 0) + 33);
appendString(T141_, ((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_15));
appendString(T141_, T142_);
			eval_error__eval_15(T141_);
			result = IL64(0);
		}
		break;
		}
	}
	break;
	case ((tyEnum_ExprKind__TB3iVeHmrzFlITKM7ipYaQ) 1):
	{
		if (!(((2 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 		{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_16), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
		switch ((*e)._k_3.uop) {
		case ((tyEnum_UnaryOP__fqj34jPuXAjoaVY0RlcILg) 0):
		{
			if (!(((2 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_17), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
			result = evali__eval_21((*e)._k_3.uoperand);
		}
		break;
		case ((tyEnum_UnaryOP__fqj34jPuXAjoaVY0RlcILg) 1):
		{
			NI64 T146_;
			NI64 T147_;
			if (!(((2 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_17), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
			T146_ = (NI64)0;
			T146_ = evali__eval_21((*e)._k_3.uoperand);
			T147_ = (NI64)0;
			T147_ = myopneg(((NU64) (T146_)));
			result = ((NI64) (T147_));
		}
		break;
		case ((tyEnum_UnaryOP__fqj34jPuXAjoaVY0RlcILg) 2):
		{
			NI64 T149_;
			if (!(((2 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_17), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
			T149_ = (NI64)0;
			T149_ = evali__eval_21((*e)._k_3.uoperand);
			result = myopneg(T149_);
		}
		break;
		case ((tyEnum_UnaryOP__fqj34jPuXAjoaVY0RlcILg) 9):
		{
			NI64 T151_;
			if (!(((2 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_17), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
			T151_ = (NI64)0;
			T151_ = evali__eval_21((*e)._k_3.uoperand);
			result = myopnot(T151_);
		}
		break;
		case ((tyEnum_UnaryOP__fqj34jPuXAjoaVY0RlcILg) 4):
		{
			NI64 T153_;
			if (!(((2 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_17), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
			T153_ = (NI64)0;
			T153_ = evali__eval_21((*e)._k_3.uoperand);
			result = (NI64)((NU64) ~(T153_));
		}
		break;
		default:
		{
			NimStringDesc* T155_;
			NimStringDesc* T156_;
			T155_ = NIM_NIL;
			T156_ = NIM_NIL;
			T156_ = dollar___core_498(e);
			T155_ = rawNewString((T156_ ? T156_->Sup.len : 0) + 53);
appendString(T155_, ((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_18));
appendString(T155_, T156_);
			eval_error__eval_15(T155_);
			result = IL64(0);
		}
		break;
		}
	}
	break;
	case ((tyEnum_ExprKind__TB3iVeHmrzFlITKM7ipYaQ) 3):
	{
		if (!(((8 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 		{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_19), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
		result = ((NI64) ((*e)._k_5.ival));
	}
	break;
	case ((tyEnum_ExprKind__TB3iVeHmrzFlITKM7ipYaQ) 4):
	{
		eval_error__eval_15(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_20));
		result = IL64(0);
	}
	break;
	case ((tyEnum_ExprKind__TB3iVeHmrzFlITKM7ipYaQ) 7):
	{
		{
			NI64 T162_;
			if (!(((128 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_21), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
			T162_ = (NI64)0;
			T162_ = evali__eval_21((*e)._k_10.cond);
			if (!!((T162_ == IL64(0)))) goto LA163_;
			if (!(((128 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_22), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
			result = evali__eval_21((*e)._k_10.cleft);
		}
		goto LA160_;
		LA163_: ;
		{
			if (!(((128 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_23), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__TB3iVeHmrzFlITKM7ipYaQ_))); } 
			result = evali__eval_21((*e)._k_10.cright);
		}
		LA160_: ;
	}
	break;
	default:
	{
		NimStringDesc* T167_;
		NimStringDesc* T168_;
		T167_ = NIM_NIL;
		T168_ = NIM_NIL;
		T168_ = dollar___core_498(e);
		T167_ = rawNewString((T168_ ? T168_->Sup.len : 0) + 33);
appendString(T167_, ((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_15));
appendString(T167_, T168_);
		eval_error__eval_15(T167_);
		result = IL64(0);
	}
	break;
	}
	return result;
}
static N_INLINE(NI, pluspercent___system_696)(NI x, NI y) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU64)(((NU) (x))) + (NU64)(((NU) (y))))));
	return result;
}
static N_INLINE(void, incRef__system_5358)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = pluspercent___system_696((*c).refcount, ((NI) 8));
}
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU64)(((NU) (x))) - (NU64)(((NU) (y))))));
	return result;
}
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__system_5320)(void* usr) {
	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* result;
	NI T1_;
	result = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	T1_ = (NI)0;
	T1_ = minuspercent___system_716(((NI) (ptrdiff_t) (usr)), ((NI) 16));
	result = ((tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*) (T1_));
	return result;
}
static N_INLINE(NIM_BOOL, ltpercent___system_1005)(NI x, NI y) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = ((NU64)(((NU) (x))) < (NU64)(((NU) (y))));
	return result;
}
static N_INLINE(void, rtlAddZCT__system_5363)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	addZCT__system_5314((&gch__system_5267.zct), c);
}
static N_INLINE(void, decRef__system_5365)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = minuspercent___system_716((*c).refcount, ((NI) 8));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = ltpercent___system_1005((*c).refcount, ((NI) 8));
		if (!T3_) goto LA4_;
		rtlAddZCT__system_5363(c);
	}
	LA4_: ;
}
static N_INLINE(void, asgnRef)(void** dest, void* src) {
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell__system_5320(src);
		incRef__system_5358(T5_);
	}
	LA3_: ;
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell__system_5320((*dest));
		decRef__system_5365(T10_);
	}
	LA8_: ;
	(*dest) = src;
}
N_LIB_PRIVATE N_NIMCALL(void, setEval__eval_23)(void) {
	tyProc__8UNH05QTEiXxPrySuACpwA T1_;
	nimZeroMem((void*)(&T1_), sizeof(tyProc__8UNH05QTEiXxPrySuACpwA));
	T1_.ClP_0 = ((TM__K5VqFIgwzZfjyHdregweGA_24) (evali__eval_21)); T1_.ClE_0 = NIM_NIL;
	asgnRef((void**) (&app__core_2785.eval_const_expression.ClE_0), T1_.ClE_0);
	app__core_2785.eval_const_expression.ClP_0 = T1_.ClP_0;
}
