/* Generated by Nim Compiler v1.6.6 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\Users\林仁傑\source\mingw64\bin\gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN   -IC:\Users\林仁傑\source\nim-1.6.6\lib -IC:\Users\林仁傑\source\Runner\cc -o C:\Users\林仁傑\source\Runner\cc\foo\@meval.nim.c.o C:\Users\林仁傑\source\Runner\cc\foo\@meval.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include "myop.h"
#include <stdio.h>
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  typedef struct tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ;
typedef struct tyObject_CC__H5XRV6CeEvWKbip2uECzdg tyObject_CC__H5XRV6CeEvWKbip2uECzdg;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tyObject_CTypecolonObjectType___y9c8kbbfIvBCGqKHvKcIVGw tyObject_CTypecolonObjectType___y9c8kbbfIvBCGqKHvKcIVGw;
typedef struct tySequence__1BBmFBuDfKRifk60cOMPTA tySequence__1BBmFBuDfKRifk60cOMPTA;
typedef struct tySequence__5Ea4hthuw6lQuV4Ge38uDA tySequence__5Ea4hthuw6lQuV4Ge38uDA;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_ParsercolonObjectType___lJsmkenZ3vILkn3jj4vS6w tyObject_ParsercolonObjectType___lJsmkenZ3vILkn3jj4vS6w;
typedef struct tySequence__d8M9bCHvPeBbf8w29cp9bhkeA tySequence__d8M9bCHvPeBbf8w29cp9bhkeA;
typedef struct tySequence__yk8YBI4DVEPKlqvq4E3jaQ tySequence__yk8YBI4DVEPKlqvq4E3jaQ;
typedef struct tyObject_TokenVcolonObjectType___UHmww0SAtuepdPeXHZTqZw tyObject_TokenVcolonObjectType___UHmww0SAtuepdPeXHZTqZw;
typedef struct tyObject_Table__IkhSz6chBcQddILqAmB2Bw tyObject_Table__IkhSz6chBcQddILqAmB2Bw;
typedef struct tySequence__JVl4l2FTq9cKT6CTi8NEvdg tySequence__JVl4l2FTq9cKT6CTi8NEvdg;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ tySequence__6H5Oh5UUvVCLiakt9aTwtUQ;
typedef struct tyObject_HashSet__CD8Dpv0WGmASelVaNSo6zg tyObject_HashSet__CD8Dpv0WGmASelVaNSo6zg;
typedef struct tySequence__4eRCaZmrYLLw2k30GPTiMw tySequence__4eRCaZmrYLLw2k30GPTiMw;
typedef struct tySequence__JBVMxYw59aXIATitfVihSXg tySequence__JBVMxYw59aXIATitfVihSXg;
typedef struct tySequence__XXSYSjw7g1bMW9cqPte4oDQ tySequence__XXSYSjw7g1bMW9cqPte4oDQ;
typedef struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack__7fytPA5bBsob6See21YMRA tyObject_GcStack__7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyTuple__ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_StreamcolonObjectType___ADoOUY5nj7w3cjSeMpeq9bg tyObject_StreamcolonObjectType___ADoOUY5nj7w3cjSeMpeq9bg;
typedef struct tyObject_Location__Q9aEveWfE4AtLRzHJktGXnA tyObject_Location__Q9aEveWfE4AtLRzHJktGXnA;
typedef struct tyTuple__sAmD9coS5prXHiu3i4hes9aA tyTuple__sAmD9coS5prXHiu3i4hes9aA;
typedef struct tyObject_PPMacrocolonObjectType___qePcXpxo9bHxHmnxPVsHXog tyObject_PPMacrocolonObjectType___qePcXpxo9bHxHmnxPVsHXog;
typedef struct tyTuple__QeWl6B6ffS4pU6WWrtcrDw tyTuple__QeWl6B6ffS4pU6WWrtcrDw;
typedef struct tyObject_Table__39cqxIJDhLlDDNdoZ2A7EbQ tyObject_Table__39cqxIJDhLlDDNdoZ2A7EbQ;
typedef struct {
N_NIMCALL_PTR(NI64, ClP_0) (tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ* e, void* ClE_0);
void* ClE_0;
} tyProc__Ss9bezNnzQaBhBwsIKf0qTg;
typedef NU8 tyEnum_Input__4xkeTUPZE5X9azudwRBEOVA;
typedef NU8 tyEnum_Output__z2pKOFEGp5K7qKOH5sOfcA;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_VerboseLevel__xI6367Zu5WWcwaENhMBQFA;
typedef NU8 tyEnum_Linker__VnxA6dODl7K2C9a4taFpPxA;
typedef struct {
N_NIMCALL_PTR(unsigned long long, ClP_0) (tyObject_CTypecolonObjectType___y9c8kbbfIvBCGqKHvKcIVGw* ty, void* ClE_0);
void* ClE_0;
} tyProc__GDxfnfju9aOVojHhiPTEm1g;
typedef struct {
N_NIMCALL_PTR(unsigned long long, ClP_0) (tyObject_CTypecolonObjectType___y9c8kbbfIvBCGqKHvKcIVGw* ty, NI idx, void* ClE_0);
void* ClE_0;
} tyProc__V8axfTLMXV2ebRNg6M9aGGQ;
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc__HzVCwACFYM9cx9aV62PdjtuA;
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (tySequence__1BBmFBuDfKRifk60cOMPTA* tokens, void* ClE_0);
void* ClE_0;
} tyProc__PTN2F5CmbJA6Q7KsriQPdQ;
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (NimStringDesc* p, void* ClE_0);
void* ClE_0;
} tyProc__k2HFjxisIgDALbEUFojxaQ;
struct tyObject_CC__H5XRV6CeEvWKbip2uECzdg {
tyEnum_Input__4xkeTUPZE5X9azudwRBEOVA input;
tyEnum_Output__z2pKOFEGp5K7qKOH5sOfcA mode;
NIM_BOOL runJit;
unsigned int optLevel;
unsigned int sizeLevel;
unsigned int inlineThreshold;
NimStringDesc* output;
tyEnum_VerboseLevel__xI6367Zu5WWcwaENhMBQFA verboseLevel;
NIM_BOOL opaquePointerEnabled;
tyEnum_Linker__VnxA6dODl7K2C9a4taFpPxA linker;
NimStringDesc* triple;
tySequence__sM4lkSb7zS6F7OVMvW9cffQ* inputs;
unsigned long long pointersize;
tyProc__GDxfnfju9aOVojHhiPTEm1g getSizeof;
tyProc__V8axfTLMXV2ebRNg6M9aGGQ getoffsetof;
tyProc__GDxfnfju9aOVojHhiPTEm1g getAlignOf;
tyProc__HzVCwACFYM9cx9aV62PdjtuA lex;
tyProc__HzVCwACFYM9cx9aV62PdjtuA cpp;
tyProc__Ss9bezNnzQaBhBwsIKf0qTg eval_const_expression;
tyProc__PTN2F5CmbJA6Q7KsriQPdQ pragma;
tyProc__k2HFjxisIgDALbEUFojxaQ pragmas;
};
typedef NU8 tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ;
typedef NU8 tyEnum_BinOP__fynptmmwPBA9aKeAoNUe1qA;
typedef NU8 tyEnum_UnaryOP__UBzoLjzsBr0iHTGRBtQ54w;
typedef NU8 tyEnum_PostfixOP__jgPOCDkMnYUH9ajYVCnMILw;
typedef NU8 tyEnum_CastOp__9crSbEPW1bL178akY7zCPGA;
struct tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ {
tyObject_CTypecolonObjectType___y9c8kbbfIvBCGqKHvKcIVGw* ty;
tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ k;
union{
struct {tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ* voidexpr;
} _k_1;
struct {tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ* lhs;
tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ* rhs;
tyEnum_BinOP__fynptmmwPBA9aKeAoNUe1qA bop;
} _k_2;
struct {tyEnum_UnaryOP__UBzoLjzsBr0iHTGRBtQ54w uop;
tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ* uoperand;
} _k_3;
struct {tyEnum_PostfixOP__jgPOCDkMnYUH9ajYVCnMILw pop;
tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ* poperand;
} _k_4;
struct {NI ival;
} _k_5;
struct {NF fval;
} _k_6;
struct {NimStringDesc* str;
} _k_7;
struct {NimStringDesc* sval;
} _k_8;
struct {tySequence__5Ea4hthuw6lQuV4Ge38uDA* arr;
} _k_9;
struct {tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ* cond;
tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ* cleft;
tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ* cright;
} _k_10;
struct {tyEnum_CastOp__9crSbEPW1bL178akY7zCPGA castop;
tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ* castval;
} _k_11;
struct {tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ* callfunc;
tySequence__5Ea4hthuw6lQuV4Ge38uDA* callargs;
} _k_12;
struct {tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ* left;
tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ* right;
} _k_13;
struct {tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ* obj;
NI idx;
} _k_14;
struct {void* p;
} _k_15;
};
};
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
NI align;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_Table__IkhSz6chBcQddILqAmB2Bw {
tySequence__JVl4l2FTq9cKT6CTi8NEvdg* data;
NI counter;
};
typedef NU8 tyEnum_ParseFlags__exxWDbohGZ4z8m1JX5sOSg;
struct tyObject_HashSet__CD8Dpv0WGmASelVaNSo6zg {
tySequence__4eRCaZmrYLLw2k30GPTiMw* data;
NI counter;
};
struct tyObject_ParsercolonObjectType___lJsmkenZ3vILkn3jj4vS6w {
tyObject_CTypecolonObjectType___y9c8kbbfIvBCGqKHvKcIVGw* currentfunctionRet;
tyObject_CTypecolonObjectType___y9c8kbbfIvBCGqKHvKcIVGw* currentInitTy;
tyObject_CTypecolonObjectType___y9c8kbbfIvBCGqKHvKcIVGw* currentCase;
NimStringDesc* pfunc;
NU32 currentAlign;
tySequence__d8M9bCHvPeBbf8w29cp9bhkeA* fstack;
tySequence__sM4lkSb7zS6F7OVMvW9cffQ* filenamestack;
tySequence__sM4lkSb7zS6F7OVMvW9cffQ* pathstack;
tySequence__yk8YBI4DVEPKlqvq4E3jaQ* locstack;
tyObject_TokenVcolonObjectType___UHmww0SAtuepdPeXHZTqZw* tok;
NI line;
NI col;
NIM_CHAR c;
NIM_BOOL want_expr;
NU16 lastc;
NimStringDesc* filename;
NimStringDesc* path;
tyObject_Table__IkhSz6chBcQddILqAmB2Bw macros;
tyEnum_ParseFlags__exxWDbohGZ4z8m1JX5sOSg flags;
tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* ppstack;
NIM_BOOL ok;
tyObject_HashSet__CD8Dpv0WGmASelVaNSo6zg onces;
tyObject_HashSet__CD8Dpv0WGmASelVaNSo6zg expansion_list;
tySequence__JBVMxYw59aXIATitfVihSXg* lables;
tySequence__XXSYSjw7g1bMW9cqPte4oDQ* tags;
tySequence__XXSYSjw7g1bMW9cqPte4oDQ* typedefs;
tySequence__1BBmFBuDfKRifk60cOMPTA* tokenq;
NI counter;
tyObject_CTypecolonObjectType___y9c8kbbfIvBCGqKHvKcIVGw* retTy;
NIM_BOOL type_error;
NIM_BOOL eval_error;
NIM_BOOL parse_error;
NIM_BOOL bad_error;
};
typedef NimStringDesc* tyArray__nHXaesL0DJZHyVS07ARPRA[1];
typedef N_CLOSURE_PTR(NI64, TM__K5VqFIgwzZfjyHdregweGA_24) (tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ* e, void* ClE_0);
struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack__7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ* tyArray__SPr7N6UKfuF549bNPiUvSRw[256];
typedef NU32 tyArray__BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* tyArray__N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray__N1u1nqOgmuJN9cSZrnMHgOQ tyArray__B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw* tyArray__lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA {
tyArray__lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* tyArray__0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw {
tyArray__0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyArray__LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray__LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray__SPr7N6UKfuF549bNPiUvSRw freeSmallChunks;
NU32 flBitmap;
tyArray__BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray__B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack__7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
NI zctThreshold;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct tyObject_Location__Q9aEveWfE4AtLRzHJktGXnA {
NI line;
NI col;
};
struct tyTuple__sAmD9coS5prXHiu3i4hes9aA {
NI Field0;
NimStringDesc* Field1;
tyObject_PPMacrocolonObjectType___qePcXpxo9bHxHmnxPVsHXog* Field2;
};
struct tyTuple__QeWl6B6ffS4pU6WWrtcrDw {
NI Field0;
NimStringDesc* Field1;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence__1BBmFBuDfKRifk60cOMPTA {
  TGenericSeq Sup;
  tyObject_TokenVcolonObjectType___UHmww0SAtuepdPeXHZTqZw* data[SEQ_DECL_SIZE];
};
struct tySequence__5Ea4hthuw6lQuV4Ge38uDA {
  TGenericSeq Sup;
  tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ* data[SEQ_DECL_SIZE];
};
struct tySequence__d8M9bCHvPeBbf8w29cp9bhkeA {
  TGenericSeq Sup;
  tyObject_StreamcolonObjectType___ADoOUY5nj7w3cjSeMpeq9bg* data[SEQ_DECL_SIZE];
};
struct tySequence__yk8YBI4DVEPKlqvq4E3jaQ {
  TGenericSeq Sup;
  tyObject_Location__Q9aEveWfE4AtLRzHJktGXnA data[SEQ_DECL_SIZE];
};
struct tySequence__JVl4l2FTq9cKT6CTi8NEvdg {
  TGenericSeq Sup;
  tyTuple__sAmD9coS5prXHiu3i4hes9aA data[SEQ_DECL_SIZE];
};
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ {
  TGenericSeq Sup;
  NU8 data[SEQ_DECL_SIZE];
};
struct tySequence__4eRCaZmrYLLw2k30GPTiMw {
  TGenericSeq Sup;
  tyTuple__QeWl6B6ffS4pU6WWrtcrDw data[SEQ_DECL_SIZE];
};
struct tySequence__JBVMxYw59aXIATitfVihSXg {
  TGenericSeq Sup;
  tyObject_HashSet__CD8Dpv0WGmASelVaNSo6zg data[SEQ_DECL_SIZE];
};
struct tySequence__XXSYSjw7g1bMW9cqPte4oDQ {
  TGenericSeq Sup;
  tyObject_Table__39cqxIJDhLlDDNdoZ2A7EbQ* data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(NI64, evali__eval_24)(tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ* e);
N_LIB_PRIVATE N_NOINLINE(void, raiseFieldError2)(NimStringDesc* f, NimStringDesc* discVal);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, reprDiscriminant)(NI e, TNimType* typ);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(NIM_BOOL, nimDivInt64)(NI64 a, NI64 b, NI64* res);
N_LIB_PRIVATE N_NIMCALL(void, eval_error__eval_18)(NimStringDesc* msg);
static N_INLINE(void, writeLine__llvm_3107)(FILE* f, NimStringDesc** x, NI xLen_0);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
N_LIB_PRIVATE N_NIMCALL(void, write__systemZio_220)(FILE* f, NimStringDesc* s);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_2999)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem__system_1727)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar___systemZdollars_3)(NI x);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar___ast_113)(tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ* e);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef__system_5392)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NI, pluspercent___system_696)(NI x, NI y);
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__system_5354)(void* usr);
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y);
static N_INLINE(void, decRef__system_5399)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NIM_BOOL, ltpercent___system_1005)(NI x, NI y);
static N_INLINE(void, rtlAddZCT__system_5397)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT__system_5348)(tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
STRING_LITERAL(TM__K5VqFIgwzZfjyHdregweGA_2, "field \'bop\' is not accessible for type \'Expr\' using \'k = ", 57);
extern TNimType NTIexprkind__kR6KxRhax5CY59atptiseeQ_;
STRING_LITERAL(TM__K5VqFIgwzZfjyHdregweGA_3, "field \'lhs\' is not accessible for type \'Expr\' using \'k = ", 57);
STRING_LITERAL(TM__K5VqFIgwzZfjyHdregweGA_4, "field \'rhs\' is not accessible for type \'Expr\' using \'k = ", 57);
STRING_LITERAL(TM__K5VqFIgwzZfjyHdregweGA_10, "\012", 1);
STRING_LITERAL(TM__K5VqFIgwzZfjyHdregweGA_11, "\033[34m", 5);
STRING_LITERAL(TM__K5VqFIgwzZfjyHdregweGA_12, ": ", 2);
STRING_LITERAL(TM__K5VqFIgwzZfjyHdregweGA_13, ": parse error: ", 15);
STRING_LITERAL(TM__K5VqFIgwzZfjyHdregweGA_14, "\033[0m", 4);
STRING_LITERAL(TM__K5VqFIgwzZfjyHdregweGA_15, "cannot eval constant-expression: ", 33);
STRING_LITERAL(TM__K5VqFIgwzZfjyHdregweGA_16, "field \'uop\' is not accessible for type \'Expr\' using \'k = ", 57);
STRING_LITERAL(TM__K5VqFIgwzZfjyHdregweGA_17, "field \'uoperand\' is not accessible for type \'Expr\' using \'k = ", 62);
STRING_LITERAL(TM__K5VqFIgwzZfjyHdregweGA_18, "cannot eval constant-expression: bad unary operator: ", 53);
STRING_LITERAL(TM__K5VqFIgwzZfjyHdregweGA_19, "field \'ival\' is not accessible for type \'Expr\' using \'k = ", 58);
STRING_LITERAL(TM__K5VqFIgwzZfjyHdregweGA_20, "floating constant in constant-expression", 40);
STRING_LITERAL(TM__K5VqFIgwzZfjyHdregweGA_21, "field \'cond\' is not accessible for type \'Expr\' using \'k = ", 58);
STRING_LITERAL(TM__K5VqFIgwzZfjyHdregweGA_22, "field \'cleft\' is not accessible for type \'Expr\' using \'k = ", 59);
STRING_LITERAL(TM__K5VqFIgwzZfjyHdregweGA_23, "field \'cright\' is not accessible for type \'Expr\' using \'k = ", 60);
extern tyObject_CC__H5XRV6CeEvWKbip2uECzdg app__core_82;
extern tyObject_ParsercolonObjectType___lJsmkenZ3vILkn3jj4vS6w* p__parser_71;
extern TFrame* framePtr__system_2566;
extern TFrame* framePtr__system_2566;
extern TFrame* framePtr__system_2566;
extern TFrame* framePtr__system_2566;
extern TFrame* framePtr__system_2566;
extern TFrame* framePtr__system_2566;
extern tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ gch__system_5301;
static N_INLINE(NIM_BOOL, nimDivInt64)(NI64 a, NI64 b, NI64* res) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a == (IL64(-9223372036854775807) - IL64(1)));
		if (!(T3_)) goto LA4_;
		T3_ = (b == IL64(-1));
		LA4_: ;
		if (!T3_) goto LA5_;
		result = NIM_TRUE;
	}
	goto LA1_;
	LA5_: ;
	{
		(*res) = (NI64)(a / b);
	}
	LA1_: ;
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s) {
	{
		if (!(framePtr__system_2566 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s).calldepth = ((NI16) 0);
	}
	goto LA1_;
	LA3_: ;
	{
		(*s).calldepth = (NI16)((*framePtr__system_2566).calldepth + ((NI16) 1));
	}
	LA1_: ;
	(*s).prev = framePtr__system_2566;
	framePtr__system_2566 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;
		callDepthLimitReached__system_2999();
	}
	LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_2566 = (*framePtr__system_2566).prev;
}
static N_INLINE(void, writeLine__llvm_3107)(FILE* f, NimStringDesc** x, NI xLen_0) {
	nimfr_("writeLine", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\io.nim");
	{
		NimStringDesc** i;
		NI i_2;
		i = (NimStringDesc**)0;
		nimln_(8, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\iterators.nim");
		i_2 = ((NI) 0);
		{
			nimln_(9, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\iterators.nim");
			while (1) {
				NI TM__K5VqFIgwzZfjyHdregweGA_9;
				if (!(i_2 < xLen_0)) goto LA3;
				nimln_(602, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\io.nim");
				if (i_2 < 0 || i_2 >= xLen_0){ raiseIndexError2(i_2,xLen_0-1); }
				i = (&x[i_2]);
				write__systemZio_220(f, (*i));
				nimln_(11, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\iterators.nim");
				if (nimAddInt(i_2, ((NI) 1), &TM__K5VqFIgwzZfjyHdregweGA_9)) { raiseOverflow(); };
				i_2 = (NI)(TM__K5VqFIgwzZfjyHdregweGA_9);
			} LA3: ;
		}
	}
	nimln_(604, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\io.nim");
	write__systemZio_220(f, ((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_10));
	popFrame();
}
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
	nimSetMem__systemZmemory_7(p, ((int) 0), size);
}
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}
static N_INLINE(void, copyMem__system_1727)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	{
		if (!!((src == ((NimStringDesc*) NIM_NIL)))) goto LA3_;
		copyMem__system_1727(((void*) ((&(*dest).data[(*dest).Sup.len]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
		(*dest).Sup.len += (*src).Sup.len;
	}
	LA3_: ;
}
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[(*dest).Sup.len] = c;
	(*dest).data[(NI)((*dest).Sup.len + ((NI) 1))] = 0;
	(*dest).Sup.len += ((NI) 1);
}
N_LIB_PRIVATE N_NIMCALL(void, eval_error__eval_18)(NimStringDesc* msg) {
	nimfr_("eval_error", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\eval.nim");
	nimln_(15, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\eval.nim");
	{
		tyArray__nHXaesL0DJZHyVS07ARPRA T5_;
		NimStringDesc* T6_;
		NimStringDesc* T7_;
		NimStringDesc* T8_;
		if (!((*p__parser_71).eval_error == NIM_FALSE)) goto LA3_;
		nimln_(16, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\eval.nim");
		nimZeroMem((void*)T5_, sizeof(tyArray__nHXaesL0DJZHyVS07ARPRA));
		T6_ = NIM_NIL;
		T7_ = NIM_NIL;
		T7_ = dollar___systemZdollars_3((*p__parser_71).line);
		T8_ = NIM_NIL;
		T8_ = dollar___systemZdollars_3((*p__parser_71).col);
		T6_ = rawNewString(((*p__parser_71).filename ? (*p__parser_71).filename->Sup.len : 0) + (T7_ ? T7_->Sup.len : 0) + (T8_ ? T8_->Sup.len : 0) + (msg ? msg->Sup.len : 0) + 27);
appendString(T6_, ((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_11));
appendString(T6_, (*p__parser_71).filename);
appendString(T6_, ((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_12));
appendString(T6_, T7_);
appendChar(T6_, 46);
appendString(T6_, T8_);
appendString(T6_, ((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_13));
appendString(T6_, msg);
appendString(T6_, ((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_14));
		T5_[0] = T6_;
		writeLine__llvm_3107(stderr, T5_, 1);
		nimln_(17, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\eval.nim");
		(*p__parser_71).eval_error = NIM_TRUE;
	}
	LA3_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NI64, evali__eval_24)(tyObject_ExprcolonObjectType___eqRwdyQ9bUMO9bghkVuWSD9cQ* e) {
	NI64 result;
	nimfr_("evali", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\eval.nim");
	result = (NI64)0;
	nimln_(26, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\eval.nim");
	nimln_(29, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\eval.nim");
	switch ((*e).k) {
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 0):
	{
		nimln_(31, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\eval.nim");
		if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 		{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_2), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
		switch ((*e)._k_2.bop) {
		case ((tyEnum_BinOP__fynptmmwPBA9aKeAoNUe1qA) 2):
		case ((tyEnum_BinOP__fynptmmwPBA9aKeAoNUe1qA) 1):
		{
			NI64 T3_;
			NI64 T4_;
			NI64 TM__K5VqFIgwzZfjyHdregweGA_5;
			nimln_(33, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\eval.nim");
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_3), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
			T3_ = (NI64)0;
			T3_ = evali__eval_24((*e)._k_2.lhs);
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_4), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
			T4_ = (NI64)0;
			T4_ = evali__eval_24((*e)._k_2.rhs);
			if (nimAddInt64(T3_, T4_, &TM__K5VqFIgwzZfjyHdregweGA_5)) { raiseOverflow(); };
			result = (NI64)(TM__K5VqFIgwzZfjyHdregweGA_5);
		}
		break;
		case ((tyEnum_BinOP__fynptmmwPBA9aKeAoNUe1qA) 5):
		case ((tyEnum_BinOP__fynptmmwPBA9aKeAoNUe1qA) 4):
		{
			NI64 T6_;
			NI64 T7_;
			NI64 TM__K5VqFIgwzZfjyHdregweGA_6;
			nimln_(35, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\eval.nim");
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_3), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
			T6_ = (NI64)0;
			T6_ = evali__eval_24((*e)._k_2.lhs);
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_4), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
			T7_ = (NI64)0;
			T7_ = evali__eval_24((*e)._k_2.rhs);
			if (nimSubInt64(T6_, T7_, &TM__K5VqFIgwzZfjyHdregweGA_6)) { raiseOverflow(); };
			result = (NI64)(TM__K5VqFIgwzZfjyHdregweGA_6);
		}
		break;
		case ((tyEnum_BinOP__fynptmmwPBA9aKeAoNUe1qA) 8):
		case ((tyEnum_BinOP__fynptmmwPBA9aKeAoNUe1qA) 7):
		{
			NI64 T9_;
			NI64 T10_;
			NI64 TM__K5VqFIgwzZfjyHdregweGA_7;
			nimln_(37, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\eval.nim");
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_3), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
			T9_ = (NI64)0;
			T9_ = evali__eval_24((*e)._k_2.lhs);
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_4), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
			T10_ = (NI64)0;
			T10_ = evali__eval_24((*e)._k_2.rhs);
			if (nimMulInt64(T9_, T10_, &TM__K5VqFIgwzZfjyHdregweGA_7)) { raiseOverflow(); };
			result = (NI64)(TM__K5VqFIgwzZfjyHdregweGA_7);
		}
		break;
		case ((tyEnum_BinOP__fynptmmwPBA9aKeAoNUe1qA) 10):
		{
			NI64 T12_;
			NI64 T13_;
			nimln_(39, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\eval.nim");
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_3), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
			T12_ = (NI64)0;
			T12_ = evali__eval_24((*e)._k_2.lhs);
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_4), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
			T13_ = (NI64)0;
			T13_ = evali__eval_24((*e)._k_2.rhs);
			result = ((NI64) ((NU64)((NU64)(((NU64) (T12_))) / (NU64)(((NU64) (T13_))))));
		}
		break;
		case ((tyEnum_BinOP__fynptmmwPBA9aKeAoNUe1qA) 11):
		{
			NI64 T15_;
			NI64 T16_;
			NI64 TM__K5VqFIgwzZfjyHdregweGA_8;
			nimln_(41, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\eval.nim");
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_3), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
			T15_ = (NI64)0;
			T15_ = evali__eval_24((*e)._k_2.lhs);
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_4), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
			T16_ = (NI64)0;
			T16_ = evali__eval_24((*e)._k_2.rhs);
			if (T16_ == 0){ raiseDivByZero(); }
			if (nimDivInt64(T15_, T16_, &TM__K5VqFIgwzZfjyHdregweGA_8)) { raiseOverflow(); };
			result = (NI64)(TM__K5VqFIgwzZfjyHdregweGA_8);
		}
		break;
		case ((tyEnum_BinOP__fynptmmwPBA9aKeAoNUe1qA) 13):
		{
			NI64 T18_;
			NI64 T19_;
			nimln_(43, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\eval.nim");
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_3), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
			T18_ = (NI64)0;
			T18_ = evali__eval_24((*e)._k_2.lhs);
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_4), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
			T19_ = (NI64)0;
			T19_ = evali__eval_24((*e)._k_2.rhs);
			result = ((NI64) ((NU64)((NU64)(((NU64) (T18_))) % (NU64)(((NU64) (T19_))))));
		}
		break;
		case ((tyEnum_BinOP__fynptmmwPBA9aKeAoNUe1qA) 16):
		{
			NI64 T21_;
			NI64 T22_;
			nimln_(45, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\eval.nim");
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_3), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
			T21_ = (NI64)0;
			T21_ = evali__eval_24((*e)._k_2.lhs);
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_4), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
			T22_ = (NI64)0;
			T22_ = evali__eval_24((*e)._k_2.rhs);
			result = ((NI64) ((NU64)((NU64)(((NU64) (T21_))) >> (NU64)(((NU64) (T22_))))));
		}
		break;
		case ((tyEnum_BinOP__fynptmmwPBA9aKeAoNUe1qA) 17):
		{
			NI64 T24_;
			NI64 T25_;
			nimln_(49, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\eval.nim");
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_3), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
			T24_ = (NI64)0;
			T24_ = evali__eval_24((*e)._k_2.lhs);
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_4), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
			T25_ = (NI64)0;
			T25_ = evali__eval_24((*e)._k_2.rhs);
			result = (NI64)((NI64)(T24_) >> (NU64)(T25_));
		}
		break;
		case ((tyEnum_BinOP__fynptmmwPBA9aKeAoNUe1qA) 28):
		{
			NI T27_;
			T27_ = (NI)0;
			nimln_(51, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\eval.nim");
			{
				NI64 T30_;
				NI64 T31_;
				if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 				{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_3), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
				T30_ = (NI64)0;
				T30_ = evali__eval_24((*e)._k_2.lhs);
				if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 				{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_4), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
				T31_ = (NI64)0;
				T31_ = evali__eval_24((*e)._k_2.rhs);
				if (!(T30_ == T31_)) goto LA32_;
				T27_ = ((NI) 1);
			}
			goto LA28_;
			LA32_: ;
			{
				T27_ = ((NI) 0);
			}
			LA28_: ;
			result = ((NI64) (T27_));
		}
		break;
		case ((tyEnum_BinOP__fynptmmwPBA9aKeAoNUe1qA) 29):
		{
			NI T36_;
			T36_ = (NI)0;
			nimln_(53, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\eval.nim");
			{
				NI64 T39_;
				NI64 T40_;
				if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 				{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_3), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
				T39_ = (NI64)0;
				T39_ = evali__eval_24((*e)._k_2.lhs);
				if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 				{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_4), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
				T40_ = (NI64)0;
				T40_ = evali__eval_24((*e)._k_2.rhs);
				if (!!((T39_ == T40_))) goto LA41_;
				T36_ = ((NI) 1);
			}
			goto LA37_;
			LA41_: ;
			{
				T36_ = ((NI) 0);
			}
			LA37_: ;
			result = ((NI64) (T36_));
		}
		break;
		case ((tyEnum_BinOP__fynptmmwPBA9aKeAoNUe1qA) 35):
		{
			NI T45_;
			T45_ = (NI)0;
			nimln_(55, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\eval.nim");
			{
				NI64 T48_;
				NI64 T49_;
				if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 				{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_4), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
				T48_ = (NI64)0;
				T48_ = evali__eval_24((*e)._k_2.rhs);
				if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 				{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_3), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
				T49_ = (NI64)0;
				T49_ = evali__eval_24((*e)._k_2.lhs);
				if (!(T48_ <= T49_)) goto LA50_;
				T45_ = ((NI) 1);
			}
			goto LA46_;
			LA50_: ;
			{
				T45_ = ((NI) 0);
			}
			LA46_: ;
			result = ((NI64) (T45_));
		}
		break;
		case ((tyEnum_BinOP__fynptmmwPBA9aKeAoNUe1qA) 34):
		{
			NI T54_;
			T54_ = (NI)0;
			nimln_(57, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\eval.nim");
			{
				NI64 T57_;
				NI64 T58_;
				if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 				{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_4), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
				T57_ = (NI64)0;
				T57_ = evali__eval_24((*e)._k_2.rhs);
				if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 				{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_3), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
				T58_ = (NI64)0;
				T58_ = evali__eval_24((*e)._k_2.lhs);
				if (!(T57_ < T58_)) goto LA59_;
				T54_ = ((NI) 1);
			}
			goto LA55_;
			LA59_: ;
			{
				T54_ = ((NI) 0);
			}
			LA55_: ;
			result = ((NI64) (T54_));
		}
		break;
		case ((tyEnum_BinOP__fynptmmwPBA9aKeAoNUe1qA) 37):
		{
			NI T63_;
			T63_ = (NI)0;
			nimln_(59, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\eval.nim");
			{
				NI64 T66_;
				NI64 T67_;
				if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 				{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_3), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
				T66_ = (NI64)0;
				T66_ = evali__eval_24((*e)._k_2.lhs);
				if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 				{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_4), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
				T67_ = (NI64)0;
				T67_ = evali__eval_24((*e)._k_2.rhs);
				if (!(T66_ <= T67_)) goto LA68_;
				T63_ = ((NI) 1);
			}
			goto LA64_;
			LA68_: ;
			{
				T63_ = ((NI) 0);
			}
			LA64_: ;
			result = ((NI64) (T63_));
		}
		break;
		case ((tyEnum_BinOP__fynptmmwPBA9aKeAoNUe1qA) 36):
		{
			NI T72_;
			T72_ = (NI)0;
			nimln_(61, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\eval.nim");
			{
				NI64 T75_;
				NI64 T76_;
				if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 				{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_3), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
				T75_ = (NI64)0;
				T75_ = evali__eval_24((*e)._k_2.lhs);
				if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 				{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_4), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
				T76_ = (NI64)0;
				T76_ = evali__eval_24((*e)._k_2.rhs);
				if (!(T75_ < T76_)) goto LA77_;
				T72_ = ((NI) 1);
			}
			goto LA73_;
			LA77_: ;
			{
				T72_ = ((NI) 0);
			}
			LA73_: ;
			result = ((NI64) (T72_));
		}
		break;
		case ((tyEnum_BinOP__fynptmmwPBA9aKeAoNUe1qA) 31):
		{
			NI T81_;
			T81_ = (NI)0;
			nimln_(63, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\eval.nim");
			{
				NI64 T84_;
				NI64 T85_;
				if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 				{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_4), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
				T84_ = (NI64)0;
				T84_ = evali__eval_24((*e)._k_2.rhs);
				if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 				{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_3), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
				T85_ = (NI64)0;
				T85_ = evali__eval_24((*e)._k_2.lhs);
				if (!((NU64)(((NU64) (T84_))) <= (NU64)(((NU64) (T85_))))) goto LA86_;
				T81_ = ((NI) 1);
			}
			goto LA82_;
			LA86_: ;
			{
				T81_ = ((NI) 0);
			}
			LA82_: ;
			result = ((NI64) (T81_));
		}
		break;
		case ((tyEnum_BinOP__fynptmmwPBA9aKeAoNUe1qA) 30):
		{
			NI T90_;
			T90_ = (NI)0;
			nimln_(65, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\eval.nim");
			{
				NI64 T93_;
				NI64 T94_;
				if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 				{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_4), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
				T93_ = (NI64)0;
				T93_ = evali__eval_24((*e)._k_2.rhs);
				if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 				{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_3), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
				T94_ = (NI64)0;
				T94_ = evali__eval_24((*e)._k_2.lhs);
				if (!((NU64)(((NU64) (T93_))) < (NU64)(((NU64) (T94_))))) goto LA95_;
				T90_ = ((NI) 1);
			}
			goto LA91_;
			LA95_: ;
			{
				T90_ = ((NI) 0);
			}
			LA91_: ;
			result = ((NI64) (T90_));
		}
		break;
		case ((tyEnum_BinOP__fynptmmwPBA9aKeAoNUe1qA) 33):
		{
			NI T99_;
			T99_ = (NI)0;
			nimln_(67, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\eval.nim");
			{
				NI64 T102_;
				NI64 T103_;
				if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 				{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_3), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
				T102_ = (NI64)0;
				T102_ = evali__eval_24((*e)._k_2.lhs);
				if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 				{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_4), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
				T103_ = (NI64)0;
				T103_ = evali__eval_24((*e)._k_2.rhs);
				if (!((NU64)(((NU64) (T102_))) <= (NU64)(((NU64) (T103_))))) goto LA104_;
				T99_ = ((NI) 1);
			}
			goto LA100_;
			LA104_: ;
			{
				T99_ = ((NI) 0);
			}
			LA100_: ;
			result = ((NI64) (T99_));
		}
		break;
		case ((tyEnum_BinOP__fynptmmwPBA9aKeAoNUe1qA) 32):
		{
			NI T108_;
			T108_ = (NI)0;
			nimln_(69, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\eval.nim");
			{
				NI64 T111_;
				NI64 T112_;
				if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 				{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_3), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
				T111_ = (NI64)0;
				T111_ = evali__eval_24((*e)._k_2.lhs);
				if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 				{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_4), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
				T112_ = (NI64)0;
				T112_ = evali__eval_24((*e)._k_2.rhs);
				if (!((NU64)(((NU64) (T111_))) < (NU64)(((NU64) (T112_))))) goto LA113_;
				T108_ = ((NI) 1);
			}
			goto LA109_;
			LA113_: ;
			{
				T108_ = ((NI) 0);
			}
			LA109_: ;
			result = ((NI64) (T108_));
		}
		break;
		case ((tyEnum_BinOP__fynptmmwPBA9aKeAoNUe1qA) 19):
		{
			NI64 T117_;
			NI64 T118_;
			nimln_(71, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\eval.nim");
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_3), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
			T117_ = (NI64)0;
			T117_ = evali__eval_24((*e)._k_2.lhs);
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_4), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
			T118_ = (NI64)0;
			T118_ = evali__eval_24((*e)._k_2.rhs);
			result = (NI64)(T117_ & T118_);
		}
		break;
		case ((tyEnum_BinOP__fynptmmwPBA9aKeAoNUe1qA) 20):
		{
			NI64 T120_;
			NI64 T121_;
			nimln_(73, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\eval.nim");
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_3), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
			T120_ = (NI64)0;
			T120_ = evali__eval_24((*e)._k_2.lhs);
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_4), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
			T121_ = (NI64)0;
			T121_ = evali__eval_24((*e)._k_2.rhs);
			result = (NI64)(T120_ ^ T121_);
		}
		break;
		case ((tyEnum_BinOP__fynptmmwPBA9aKeAoNUe1qA) 21):
		{
			NI64 T123_;
			NI64 T124_;
			nimln_(75, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\eval.nim");
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_3), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
			T123_ = (NI64)0;
			T123_ = evali__eval_24((*e)._k_2.lhs);
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_4), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
			T124_ = (NI64)0;
			T124_ = evali__eval_24((*e)._k_2.rhs);
			result = (NI64)(T123_ | T124_);
		}
		break;
		case ((tyEnum_BinOP__fynptmmwPBA9aKeAoNUe1qA) 22):
		{
			NI64 T126_;
			NI64 T127_;
			nimln_(77, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\eval.nim");
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_3), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
			T126_ = (NI64)0;
			T126_ = evali__eval_24((*e)._k_2.lhs);
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_4), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
			T127_ = (NI64)0;
			T127_ = evali__eval_24((*e)._k_2.rhs);
			result = myopand(T126_, T127_);
		}
		break;
		case ((tyEnum_BinOP__fynptmmwPBA9aKeAoNUe1qA) 23):
		{
			NI64 T129_;
			NI64 T130_;
			nimln_(79, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\eval.nim");
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_3), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
			T129_ = (NI64)0;
			T129_ = evali__eval_24((*e)._k_2.lhs);
			if (!(((1 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_4), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
			T130_ = (NI64)0;
			T130_ = evali__eval_24((*e)._k_2.rhs);
			result = myopor(T129_, T130_);
		}
		break;
		default:
		{
			NimStringDesc* T132_;
			NimStringDesc* T133_;
			nimln_(81, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\eval.nim");
			T132_ = NIM_NIL;
			T133_ = NIM_NIL;
			T133_ = dollar___ast_113(e);
			T132_ = rawNewString((T133_ ? T133_->Sup.len : 0) + 33);
appendString(T132_, ((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_15));
appendString(T132_, T133_);
			eval_error__eval_18(T132_);
			result = IL64(0);
		}
		break;
		}
	}
	break;
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 1):
	{
		nimln_(84, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\eval.nim");
		if (!(((2 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 		{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_16), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
		switch ((*e)._k_3.uop) {
		case ((tyEnum_UnaryOP__UBzoLjzsBr0iHTGRBtQ54w) 0):
		{
			nimln_(86, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\eval.nim");
			if (!(((2 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_17), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
			result = evali__eval_24((*e)._k_3.uoperand);
		}
		break;
		case ((tyEnum_UnaryOP__UBzoLjzsBr0iHTGRBtQ54w) 1):
		{
			NI64 T137_;
			NI64 T138_;
			nimln_(88, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\eval.nim");
			if (!(((2 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_17), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
			T137_ = (NI64)0;
			T137_ = evali__eval_24((*e)._k_3.uoperand);
			T138_ = (NI64)0;
			T138_ = myopneg(((NU64) (T137_)));
			result = ((NI64) (T138_));
		}
		break;
		case ((tyEnum_UnaryOP__UBzoLjzsBr0iHTGRBtQ54w) 2):
		{
			NI64 T140_;
			nimln_(90, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\eval.nim");
			if (!(((2 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_17), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
			T140_ = (NI64)0;
			T140_ = evali__eval_24((*e)._k_3.uoperand);
			result = myopneg(T140_);
		}
		break;
		case ((tyEnum_UnaryOP__UBzoLjzsBr0iHTGRBtQ54w) 9):
		{
			NI64 T142_;
			nimln_(92, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\eval.nim");
			if (!(((2 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_17), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
			T142_ = (NI64)0;
			T142_ = evali__eval_24((*e)._k_3.uoperand);
			result = myopnot(T142_);
		}
		break;
		case ((tyEnum_UnaryOP__UBzoLjzsBr0iHTGRBtQ54w) 4):
		{
			NI64 T144_;
			nimln_(94, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\eval.nim");
			if (!(((2 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_17), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
			T144_ = (NI64)0;
			T144_ = evali__eval_24((*e)._k_3.uoperand);
			result = (NI64)((NU64) ~(T144_));
		}
		break;
		default:
		{
			NimStringDesc* T146_;
			NimStringDesc* T147_;
			nimln_(96, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\eval.nim");
			T146_ = NIM_NIL;
			T147_ = NIM_NIL;
			T147_ = dollar___ast_113(e);
			T146_ = rawNewString((T147_ ? T147_->Sup.len : 0) + 53);
appendString(T146_, ((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_18));
appendString(T146_, T147_);
			eval_error__eval_18(T146_);
			result = IL64(0);
		}
		break;
		}
	}
	break;
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 3):
	{
		if (!(((8 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 		{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_19), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
		result = ((NI64) ((*e)._k_5.ival));
	}
	break;
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 4):
	{
		nimln_(101, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\eval.nim");
		eval_error__eval_18(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_20));
		result = IL64(0);
	}
	break;
	case ((tyEnum_ExprKind__kR6KxRhax5CY59atptiseeQ) 7):
	{
		nimln_(104, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\eval.nim");
		{
			NI64 T153_;
			if (!(((128 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_21), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
			T153_ = (NI64)0;
			T153_ = evali__eval_24((*e)._k_10.cond);
			if (!!((T153_ == IL64(0)))) goto LA154_;
			if (!(((128 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_22), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
			result = evali__eval_24((*e)._k_10.cleft);
		}
		goto LA151_;
		LA154_: ;
		{
			if (!(((128 &((NU32)1<<((NU)((*e).k)&31U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_23), reprDiscriminant(((NI)(*e).k) + (NI)IL64(0), (&NTIexprkind__kR6KxRhax5CY59atptiseeQ_))); } 
			result = evali__eval_24((*e)._k_10.cright);
		}
		LA151_: ;
	}
	break;
	default:
	{
		NimStringDesc* T158_;
		NimStringDesc* T159_;
		nimln_(106, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\eval.nim");
		T158_ = NIM_NIL;
		T159_ = NIM_NIL;
		T159_ = dollar___ast_113(e);
		T158_ = rawNewString((T159_ ? T159_->Sup.len : 0) + 33);
appendString(T158_, ((NimStringDesc*) &TM__K5VqFIgwzZfjyHdregweGA_15));
appendString(T158_, T159_);
		eval_error__eval_18(T158_);
		result = IL64(0);
	}
	break;
	}
	popFrame();
	return result;
}
static N_INLINE(NI, pluspercent___system_696)(NI x, NI y) {
	NI result;
	nimfr_("+%", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\arithmetics.nim");
	result = (NI)0;
	nimln_(403, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\arithmetics.nim");
	nimln_(407, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\arithmetics.nim");
	result = ((NI) ((NU)((NU64)(((NU) (x))) + (NU64)(((NU) (y))))));
	popFrame();
	return result;
}
static N_INLINE(void, incRef__system_5392)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\gc.nim");
	nimln_(231, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\gc.nim");
	(*c).refcount = pluspercent___system_696((*c).refcount, ((NI) 8));
	popFrame();
}
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y) {
	NI result;
	nimfr_("-%", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\arithmetics.nim");
	result = (NI)0;
	nimln_(414, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\arithmetics.nim");
	nimln_(418, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\arithmetics.nim");
	result = ((NI) ((NU)((NU64)(((NU) (x))) - (NU64)(((NU) (y))))));
	popFrame();
	return result;
}
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__system_5354)(void* usr) {
	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* result;
	NI T1_;
	nimfr_("usrToCell", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\gc.nim");
	result = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(177, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\gc.nim");
	T1_ = (NI)0;
	T1_ = minuspercent___system_716(((NI) (ptrdiff_t) (usr)), ((NI) 16));
	result = ((tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*) (T1_));
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, ltpercent___system_1005)(NI x, NI y) {
	NIM_BOOL result;
	nimfr_("<%", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\comparisons.nim");
	result = (NIM_BOOL)0;
	nimln_(186, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\comparisons.nim");
	nimln_(188, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\comparisons.nim");
	result = ((NU64)(((NU) (x))) < (NU64)(((NU) (y))));
	popFrame();
	return result;
}
static N_INLINE(void, rtlAddZCT__system_5397)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\gc.nim");
	nimln_(243, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\gc.nim");
	addZCT__system_5348((&gch__system_5301.zct), c);
	popFrame();
}
static N_INLINE(void, decRef__system_5399)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\gc.nim");
	nimln_(248, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\gc.nim");
	(*c).refcount = minuspercent___system_716((*c).refcount, ((NI) 8));
	nimln_(249, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\gc.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = ltpercent___system_1005((*c).refcount, ((NI) 8));
		if (!T3_) goto LA4_;
		nimln_(250, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\gc.nim");
		rtlAddZCT__system_5397(c);
	}
	LA4_: ;
	popFrame();
}
static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\gc.nim");
	nimln_(286, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\gc.nim");
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell__system_5354(src);
		incRef__system_5392(T5_);
	}
	LA3_: ;
	nimln_(287, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\gc.nim");
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell__system_5354((*dest));
		decRef__system_5399(T10_);
	}
	LA8_: ;
	nimln_(288, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\gc.nim");
	(*dest) = src;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, setEval__eval_26)(void) {
	tyProc__Ss9bezNnzQaBhBwsIKf0qTg T1_;
	nimfr_("setEval", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\eval.nim");
	nimln_(22, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\Runner\\cc\\eval.nim");
	nimZeroMem((void*)(&T1_), sizeof(tyProc__Ss9bezNnzQaBhBwsIKf0qTg));
	T1_.ClP_0 = ((TM__K5VqFIgwzZfjyHdregweGA_24) (evali__eval_24)); T1_.ClE_0 = NIM_NIL;
	asgnRef((void**) (&app__core_82.eval_const_expression.ClE_0), T1_.ClE_0);
	app__core_82.eval_const_expression.ClP_0 = T1_.ClP_0;
	popFrame();
}
