/* Generated by Nim Compiler v1.6.6 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\Users\林仁傑\source\mingw64\bin\gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN -O3 -fno-strict-aliasing -fno-ident   -IC:\Users\林仁傑\source\nim-1.6.6\lib -IC:\Users\林仁傑\source\Runner\cc -o C:\Users\林仁傑\source\Runner\cc\foo\@mstream.nim.c.o C:\Users\林仁傑\source\Runner\cc\foo\@mstream.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include "stdio.h"
#include <stdio.h>
#include <setjmp.h>
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct tyObject_StreamcolonObjectType___ADoOUY5nj7w3cjSeMpeq9bg tyObject_StreamcolonObjectType___ADoOUY5nj7w3cjSeMpeq9bg;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct TSafePoint TSafePoint;
typedef struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack__7fytPA5bBsob6See21YMRA tyObject_GcStack__7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyTuple__ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;
typedef NU8 tyEnum_StreamType__TofVVp0EcIEQmjSy5V7iMQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_StreamcolonObjectType___ADoOUY5nj7w3cjSeMpeq9bg {
int lastc;
tyEnum_StreamType__TofVVp0EcIEQmjSy5V7iMQ k;
union{
struct {struct FILE* fd;
} _k_1;
struct {NimStringDesc* s;
NI i;
} _k_2;
};
};
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
NI align;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence__uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct TSafePoint {
TSafePoint* prev;
NI status;
jmp_buf context;
};
struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack__7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ* tyArray__SPr7N6UKfuF549bNPiUvSRw[256];
typedef NU32 tyArray__BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* tyArray__N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray__N1u1nqOgmuJN9cSZrnMHgOQ tyArray__B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw* tyArray__lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA {
tyArray__lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* tyArray__0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw {
tyArray__0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyArray__LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray__LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray__SPr7N6UKfuF549bNPiUvSRw freeSmallChunks;
NU32 flBitmap;
tyArray__BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray__B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack__7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
NI zctThreshold;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef__2AlBaOTpGzA9cZMzGezDKRg)(void* p, NI op);
N_LIB_PRIVATE N_NOINLINE(void*, newObj)(TNimType* typ, NI size);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorU)(NU64 i, NU64 a, NU64 b);
N_LIB_PRIVATE N_NOINLINE(void, raiseFieldError2)(NimStringDesc* f, NimStringDesc* discVal);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, reprDiscriminant)(NI e, TNimType* typ);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, write__systemZio_220)(FILE* f, NimStringDesc* s);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, readLine__systemZio_364)(FILE* f);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem__system_1727)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef__system_5358)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NI, pluspercent___system_696)(NI x, NI y);
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__system_5320)(void* usr);
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y);
static N_INLINE(void, decRef__system_5365)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NIM_BOOL, ltpercent___system_1005)(NI x, NI y);
static N_INLINE(void, rtlAddZCT__system_5363)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT__system_5314)(tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, popSafePoint)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isObj)(TNimType* obj, TNimType* subclass);
static N_INLINE(Exception*, nimBorrowCurrentException)(void);
static N_INLINE(void, popCurrentException)(void);
N_LIB_PRIVATE N_NIMCALL(void, reraiseException)(void);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_LIB_PRIVATE TNimType NTIstream58objecttype__ADoOUY5nj7w3cjSeMpeq9bg_;
extern TNimType NTIcint__nlCscttRCss70IBTyuBqnA_;
N_LIB_PRIVATE TNimType NTIstreamtype__TofVVp0EcIEQmjSy5V7iMQ_;
TNimNode* NimDT___ADoOUY5nj7w3cjSeMpeq9bg_k[4];
extern TNimType NTIpointer__vr5DoT1jILTGdRlYv1OYpw_;
extern TNimType NTIstring__77mFvmsOLKik79ci2hXkHEg_;
extern TNimType NTIint__rR5Bzr1D5krxoo1NcNyeMA_;
N_LIB_PRIVATE TNimType NTIstream__2AlBaOTpGzA9cZMzGezDKRg_;
STRING_LITERAL(TM__4ou51UrvM4uNm9bgQw3laTw_7, "field \'fd\' is not accessible for type \'Stream\' using \'k = ", 58);
STRING_LITERAL(TM__4ou51UrvM4uNm9bgQw3laTw_8, "field \'s\' is not accessible for type \'Stream\' using \'k = ", 57);
STRING_LITERAL(TM__4ou51UrvM4uNm9bgQw3laTw_9, "field \'i\' is not accessible for type \'Stream\' using \'k = ", 57);
STRING_LITERAL(TM__4ou51UrvM4uNm9bgQw3laTw_11, ">>> ", 4);
extern TNimType NTIioerror__iLZrPn9anoh9ad1MmO0RczFw_;
extern TSafePoint* excHandler__system_2567;
extern TSafePoint* excHandler__system_2567;
extern tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ gch__system_5267;
extern TSafePoint* excHandler__system_2567;
extern TSafePoint* excHandler__system_2567;
extern Exception* currException__system_2568;
extern Exception* currException__system_2568;
extern Exception* currException__system_2568;
static N_NIMCALL(void, Marker_tyRef__2AlBaOTpGzA9cZMzGezDKRg)(void* p, NI op) {
	tyObject_StreamcolonObjectType___ADoOUY5nj7w3cjSeMpeq9bg* a;
	a = (tyObject_StreamcolonObjectType___ADoOUY5nj7w3cjSeMpeq9bg*)p;
	switch ((*a).k) {
	case ((tyEnum_StreamType__TofVVp0EcIEQmjSy5V7iMQ) 0):
	break;
	case ((tyEnum_StreamType__TofVVp0EcIEQmjSy5V7iMQ) 1):
	case ((tyEnum_StreamType__TofVVp0EcIEQmjSy5V7iMQ) 2):
	nimGCvisit((void*)(*a)._k_2.s, op);
	break;
	} 
}
N_LIB_PRIVATE N_NIMCALL(tyObject_StreamcolonObjectType___ADoOUY5nj7w3cjSeMpeq9bg*, newStdinStream__stream_64)(void) {
	tyObject_StreamcolonObjectType___ADoOUY5nj7w3cjSeMpeq9bg* result;
	tyObject_StreamcolonObjectType___ADoOUY5nj7w3cjSeMpeq9bg* T1_;
	result = NIM_NIL;
	T1_ = NIM_NIL;
	T1_ = (tyObject_StreamcolonObjectType___ADoOUY5nj7w3cjSeMpeq9bg*) newObj((&NTIstream__2AlBaOTpGzA9cZMzGezDKRg_), sizeof(tyObject_StreamcolonObjectType___ADoOUY5nj7w3cjSeMpeq9bg));
	(*T1_).k = ((tyEnum_StreamType__TofVVp0EcIEQmjSy5V7iMQ) 2);
	(*T1_).lastc = ((int) 256);
	result = T1_;
	return result;
}
static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).prev = excHandler__system_2567;
	excHandler__system_2567 = s;
}
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}
static N_INLINE(void, copyMem__system_1727)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	{
		if (!!((src == ((NimStringDesc*) NIM_NIL)))) goto LA3_;
		copyMem__system_1727(((void*) ((&(*dest).data[(*dest).Sup.len]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
		(*dest).Sup.len += (*src).Sup.len;
	}
	LA3_: ;
}
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[(*dest).Sup.len] = c;
	(*dest).data[(NI)((*dest).Sup.len + ((NI) 1))] = 0;
	(*dest).Sup.len += ((NI) 1);
}
static N_INLINE(NI, pluspercent___system_696)(NI x, NI y) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU64)(((NU) (x))) + (NU64)(((NU) (y))))));
	return result;
}
static N_INLINE(void, incRef__system_5358)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = pluspercent___system_696((*c).refcount, ((NI) 8));
}
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU64)(((NU) (x))) - (NU64)(((NU) (y))))));
	return result;
}
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__system_5320)(void* usr) {
	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* result;
	NI T1_;
	result = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	T1_ = (NI)0;
	T1_ = minuspercent___system_716(((NI) (ptrdiff_t) (usr)), ((NI) 16));
	result = ((tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*) (T1_));
	return result;
}
static N_INLINE(NIM_BOOL, ltpercent___system_1005)(NI x, NI y) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = ((NU64)(((NU) (x))) < (NU64)(((NU) (y))));
	return result;
}
static N_INLINE(void, rtlAddZCT__system_5363)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	addZCT__system_5314((&gch__system_5267.zct), c);
}
static N_INLINE(void, decRef__system_5365)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = minuspercent___system_716((*c).refcount, ((NI) 8));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = ltpercent___system_1005((*c).refcount, ((NI) 8));
		if (!T3_) goto LA4_;
		rtlAddZCT__system_5363(c);
	}
	LA4_: ;
}
static N_INLINE(void, asgnRef)(void** dest, void* src) {
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell__system_5320(src);
		incRef__system_5358(T5_);
	}
	LA3_: ;
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell__system_5320((*dest));
		decRef__system_5365(T10_);
	}
	LA8_: ;
	(*dest) = src;
}
static N_INLINE(void, popSafePoint)(void) {
	excHandler__system_2567 = (*excHandler__system_2567).prev;
}
static N_INLINE(Exception*, nimBorrowCurrentException)(void) {
	Exception* result;
	result = NIM_NIL;
	result = currException__system_2568;
	return result;
}
static N_INLINE(void, popCurrentException)(void) {
	asgnRef((void**) (&currException__system_2568), (*currException__system_2568).up);
}
N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, readChar__stream_69)(tyObject_StreamcolonObjectType___ADoOUY5nj7w3cjSeMpeq9bg* s) {
	NIM_CHAR result;
{	result = (NIM_CHAR)0;
	{
		if (!((*s).lastc <= ((NI32) 255))) goto LA3_;
		if (((*s).lastc) < 0 || ((*s).lastc) > 255){ raiseRangeErrorU((*s).lastc, 0, 255); }
		result = ((NIM_CHAR) ((*s).lastc));
		(*s).lastc = ((int) 256);
		goto BeforeRet_;
	}
	LA3_: ;
	switch ((*s).k) {
	case ((tyEnum_StreamType__TofVVp0EcIEQmjSy5V7iMQ) 0):
	{
		int c;
		if (!(((1 &((NU8)1<<((NU)((*s).k)&7U)))!=0))) 		{ raiseFieldError2(((NimStringDesc*) &TM__4ou51UrvM4uNm9bgQw3laTw_7), reprDiscriminant(((NI)(*s).k) + (NI)IL64(0), (&NTIstreamtype__TofVVp0EcIEQmjSy5V7iMQ_))); } 
		c = fgetc((*s)._k_1.fd);
		{
			if (!(c == EOF)) goto LA8_;
			result = 0;
			goto BeforeRet_;
		}
		goto LA6_;
		LA8_: ;
		{
			if (((NI32)(c & ((NI32) 255))) < 0 || ((NI32)(c & ((NI32) 255))) > 255){ raiseRangeErrorU((NI32)(c & ((NI32) 255)), 0, 255); }
			result = ((NIM_CHAR) ((NI32)(c & ((NI32) 255))));
			goto BeforeRet_;
		}
		LA6_: ;
	}
	break;
	case ((tyEnum_StreamType__TofVVp0EcIEQmjSy5V7iMQ) 1):
	{
		NI TM__4ou51UrvM4uNm9bgQw3laTw_10;
		{
			if (!(((6 &((NU8)1<<((NU)((*s).k)&7U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__4ou51UrvM4uNm9bgQw3laTw_8), reprDiscriminant(((NI)(*s).k) + (NI)IL64(0), (&NTIstreamtype__TofVVp0EcIEQmjSy5V7iMQ_))); } 
			if (!(((6 &((NU8)1<<((NU)((*s).k)&7U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__4ou51UrvM4uNm9bgQw3laTw_9), reprDiscriminant(((NI)(*s).k) + (NI)IL64(0), (&NTIstreamtype__TofVVp0EcIEQmjSy5V7iMQ_))); } 
			if (!(((*s)._k_2.s ? (*s)._k_2.s->Sup.len : 0) <= (*s)._k_2.i)) goto LA14_;
			result = 0;
			goto BeforeRet_;
		}
		LA14_: ;
		if (!(((6 &((NU8)1<<((NU)((*s).k)&7U)))!=0))) 		{ raiseFieldError2(((NimStringDesc*) &TM__4ou51UrvM4uNm9bgQw3laTw_8), reprDiscriminant(((NI)(*s).k) + (NI)IL64(0), (&NTIstreamtype__TofVVp0EcIEQmjSy5V7iMQ_))); } 
		if (!(((6 &((NU8)1<<((NU)((*s).k)&7U)))!=0))) 		{ raiseFieldError2(((NimStringDesc*) &TM__4ou51UrvM4uNm9bgQw3laTw_9), reprDiscriminant(((NI)(*s).k) + (NI)IL64(0), (&NTIstreamtype__TofVVp0EcIEQmjSy5V7iMQ_))); } 
		if ((*s)._k_2.i < 0 || (*s)._k_2.i >= ((*s)._k_2.s ? (*s)._k_2.s->Sup.len : 0)){ raiseIndexError2((*s)._k_2.i,((*s)._k_2.s ? (*s)._k_2.s->Sup.len : 0)-1); }
		result = (*s)._k_2.s->data[(*s)._k_2.i];
		if (!(((6 &((NU8)1<<((NU)((*s).k)&7U)))!=0))) 		{ raiseFieldError2(((NimStringDesc*) &TM__4ou51UrvM4uNm9bgQw3laTw_9), reprDiscriminant(((NI)(*s).k) + (NI)IL64(0), (&NTIstreamtype__TofVVp0EcIEQmjSy5V7iMQ_))); } 
		if (nimAddInt((*s)._k_2.i, ((NI) 1), &TM__4ou51UrvM4uNm9bgQw3laTw_10)) { raiseOverflow(); };
		(*s)._k_2.i = (NI)(TM__4ou51UrvM4uNm9bgQw3laTw_10);
	}
	break;
	case ((tyEnum_StreamType__TofVVp0EcIEQmjSy5V7iMQ) 2):
	{
		NI TM__4ou51UrvM4uNm9bgQw3laTw_13;
		{
			TSafePoint TM__4ou51UrvM4uNm9bgQw3laTw_12;
			NimStringDesc* T21_;
			NimStringDesc* T22_;
			if (!(((6 &((NU8)1<<((NU)((*s).k)&7U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__4ou51UrvM4uNm9bgQw3laTw_8), reprDiscriminant(((NI)(*s).k) + (NI)IL64(0), (&NTIstreamtype__TofVVp0EcIEQmjSy5V7iMQ_))); } 
			if (!(((6 &((NU8)1<<((NU)((*s).k)&7U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__4ou51UrvM4uNm9bgQw3laTw_9), reprDiscriminant(((NI)(*s).k) + (NI)IL64(0), (&NTIstreamtype__TofVVp0EcIEQmjSy5V7iMQ_))); } 
			if (!(((*s)._k_2.s ? (*s)._k_2.s->Sup.len : 0) <= (*s)._k_2.i)) goto LA19_;
			write__systemZio_220(stderr, ((NimStringDesc*) &TM__4ou51UrvM4uNm9bgQw3laTw_11));
			pushSafePoint(&TM__4ou51UrvM4uNm9bgQw3laTw_12);
			TM__4ou51UrvM4uNm9bgQw3laTw_12.status = setjmp(TM__4ou51UrvM4uNm9bgQw3laTw_12.context);
			if (TM__4ou51UrvM4uNm9bgQw3laTw_12.status == 0) {
			if (!(((6 &((NU8)1<<((NU)((*s).k)&7U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__4ou51UrvM4uNm9bgQw3laTw_8), reprDiscriminant(((NI)(*s).k) + (NI)IL64(0), (&NTIstreamtype__TofVVp0EcIEQmjSy5V7iMQ_))); } 
			T21_ = NIM_NIL;
			T22_ = NIM_NIL;
			T22_ = readLine__systemZio_364(stdin);
			T21_ = rawNewString((T22_ ? T22_->Sup.len : 0) + 1);
appendString(T21_, T22_);
appendChar(T21_, 10);
			asgnRef((void**) (&(*s)._k_2.s), T21_);
			popSafePoint();
			}
			else {
				popSafePoint();
				if (isObj(nimBorrowCurrentException()->Sup.m_type, (&NTIioerror__iLZrPn9anoh9ad1MmO0RczFw_))) {
					TM__4ou51UrvM4uNm9bgQw3laTw_12.status = 0;
					result = 0;
					popCurrentException();
					goto BeforeRet_;
					popCurrentException();
				}
			}
			if (TM__4ou51UrvM4uNm9bgQw3laTw_12.status != 0) reraiseException();
			if (!(((6 &((NU8)1<<((NU)((*s).k)&7U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__4ou51UrvM4uNm9bgQw3laTw_9), reprDiscriminant(((NI)(*s).k) + (NI)IL64(0), (&NTIstreamtype__TofVVp0EcIEQmjSy5V7iMQ_))); } 
			(*s)._k_2.i = ((NI) 0);
		}
		LA19_: ;
		if (!(((6 &((NU8)1<<((NU)((*s).k)&7U)))!=0))) 		{ raiseFieldError2(((NimStringDesc*) &TM__4ou51UrvM4uNm9bgQw3laTw_8), reprDiscriminant(((NI)(*s).k) + (NI)IL64(0), (&NTIstreamtype__TofVVp0EcIEQmjSy5V7iMQ_))); } 
		if (!(((6 &((NU8)1<<((NU)((*s).k)&7U)))!=0))) 		{ raiseFieldError2(((NimStringDesc*) &TM__4ou51UrvM4uNm9bgQw3laTw_9), reprDiscriminant(((NI)(*s).k) + (NI)IL64(0), (&NTIstreamtype__TofVVp0EcIEQmjSy5V7iMQ_))); } 
		if ((*s)._k_2.i < 0 || (*s)._k_2.i >= ((*s)._k_2.s ? (*s)._k_2.s->Sup.len : 0)){ raiseIndexError2((*s)._k_2.i,((*s)._k_2.s ? (*s)._k_2.s->Sup.len : 0)-1); }
		result = (*s)._k_2.s->data[(*s)._k_2.i];
		if (!(((6 &((NU8)1<<((NU)((*s).k)&7U)))!=0))) 		{ raiseFieldError2(((NimStringDesc*) &TM__4ou51UrvM4uNm9bgQw3laTw_9), reprDiscriminant(((NI)(*s).k) + (NI)IL64(0), (&NTIstreamtype__TofVVp0EcIEQmjSy5V7iMQ_))); } 
		if (nimAddInt((*s)._k_2.i, ((NI) 1), &TM__4ou51UrvM4uNm9bgQw3laTw_13)) { raiseOverflow(); };
		(*s)._k_2.i = (NI)(TM__4ou51UrvM4uNm9bgQw3laTw_13);
	}
	break;
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, close__stream_81)(tyObject_StreamcolonObjectType___ADoOUY5nj7w3cjSeMpeq9bg* s) {
	switch ((*s).k) {
	case ((tyEnum_StreamType__TofVVp0EcIEQmjSy5V7iMQ) 0):
	{
		int T2_;
		if (!(((1 &((NU8)1<<((NU)((*s).k)&7U)))!=0))) 		{ raiseFieldError2(((NimStringDesc*) &TM__4ou51UrvM4uNm9bgQw3laTw_7), reprDiscriminant(((NI)(*s).k) + (NI)IL64(0), (&NTIstreamtype__TofVVp0EcIEQmjSy5V7iMQ_))); } 
		T2_ = (int)0;
		T2_ = fclose((*s)._k_1.fd);
		(void)(T2_);
	}
	break;
	case ((tyEnum_StreamType__TofVVp0EcIEQmjSy5V7iMQ) 1):
	case ((tyEnum_StreamType__TofVVp0EcIEQmjSy5V7iMQ) 2):
	{
	}
	break;
	}
}
N_LIB_PRIVATE N_NIMCALL(void, putc__stream_66)(tyObject_StreamcolonObjectType___ADoOUY5nj7w3cjSeMpeq9bg* s, int c) {
	(*s).lastc = c;
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s) {
	NCSTRING result;
	result = (NCSTRING)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (s == ((NimStringDesc*) NIM_NIL));
		if (T3_) goto LA4_;
		T3_ = ((*s).Sup.len == ((NI) 0));
		LA4_: ;
		if (!T3_) goto LA5_;
		result = "";
	}
	goto LA1_;
	LA5_: ;
	{
		result = ((NCSTRING) ((*s).data));
	}
	LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_StreamcolonObjectType___ADoOUY5nj7w3cjSeMpeq9bg*, newFileStream__stream_57)(NimStringDesc* path) {
	tyObject_StreamcolonObjectType___ADoOUY5nj7w3cjSeMpeq9bg* result;
	struct FILE* fd;
	tyObject_StreamcolonObjectType___ADoOUY5nj7w3cjSeMpeq9bg* T5_;
{	result = NIM_NIL;
	fd = fopen(nimToCStringConv(path), "rb");
	{
		if (!(fd == NIM_NIL)) goto LA3_;
		result = ((tyObject_StreamcolonObjectType___ADoOUY5nj7w3cjSeMpeq9bg*) NIM_NIL);
		goto BeforeRet_;
	}
	LA3_: ;
	T5_ = NIM_NIL;
	T5_ = (tyObject_StreamcolonObjectType___ADoOUY5nj7w3cjSeMpeq9bg*) newObj((&NTIstream__2AlBaOTpGzA9cZMzGezDKRg_), sizeof(tyObject_StreamcolonObjectType___ADoOUY5nj7w3cjSeMpeq9bg));
	(*T5_).k = ((tyEnum_StreamType__TofVVp0EcIEQmjSy5V7iMQ) 0);
	(*T5_)._k_1.fd = fd;
	(*T5_).lastc = ((int) 256);
	result = T5_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T1_;
	T1_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	T1_ = usrToCell__system_5320(p);
	decRef__system_5365(T1_);
}
N_LIB_PRIVATE N_NIMCALL(tyObject_StreamcolonObjectType___ADoOUY5nj7w3cjSeMpeq9bg*, newStringStream__stream_24)(NimStringDesc* s) {
	tyObject_StreamcolonObjectType___ADoOUY5nj7w3cjSeMpeq9bg* result;
	tyObject_StreamcolonObjectType___ADoOUY5nj7w3cjSeMpeq9bg* T1_;
	NimStringDesc* T2_;
	result = NIM_NIL;
	T1_ = NIM_NIL;
	T1_ = (tyObject_StreamcolonObjectType___ADoOUY5nj7w3cjSeMpeq9bg*) newObj((&NTIstream__2AlBaOTpGzA9cZMzGezDKRg_), sizeof(tyObject_StreamcolonObjectType___ADoOUY5nj7w3cjSeMpeq9bg));
	(*T1_).k = ((tyEnum_StreamType__TofVVp0EcIEQmjSy5V7iMQ) 1);
	T2_ = NIM_NIL;
	T2_ = (*T1_)._k_2.s; (*T1_)._k_2.s = copyStringRC1(s);
	if (T2_) nimGCunrefNoCycle(T2_);
	(*T1_)._k_2.i = ((NI) 0);
	(*T1_).lastc = ((int) 256);
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, unknown_streamDatInit000)(void) {
static TNimNode* TM__4ou51UrvM4uNm9bgQw3laTw_2_2[2];
static TNimNode* TM__4ou51UrvM4uNm9bgQw3laTw_3_3[3];
NI TM__4ou51UrvM4uNm9bgQw3laTw_5;
static char* NIM_CONST TM__4ou51UrvM4uNm9bgQw3laTw_4[3] = {
"FileStream", 
"StringStream", 
"StdinStream"};
static TNimNode* TM__4ou51UrvM4uNm9bgQw3laTw_6_2[2];
static TNimNode TM__4ou51UrvM4uNm9bgQw3laTw_0[11];
NTIstream58objecttype__ADoOUY5nj7w3cjSeMpeq9bg_.size = sizeof(tyObject_StreamcolonObjectType___ADoOUY5nj7w3cjSeMpeq9bg);
NTIstream58objecttype__ADoOUY5nj7w3cjSeMpeq9bg_.align = NIM_ALIGNOF(tyObject_StreamcolonObjectType___ADoOUY5nj7w3cjSeMpeq9bg);
NTIstream58objecttype__ADoOUY5nj7w3cjSeMpeq9bg_.kind = 18;
NTIstream58objecttype__ADoOUY5nj7w3cjSeMpeq9bg_.base = 0;
TM__4ou51UrvM4uNm9bgQw3laTw_2_2[0] = &TM__4ou51UrvM4uNm9bgQw3laTw_0[1];
TM__4ou51UrvM4uNm9bgQw3laTw_0[1].kind = 1;
TM__4ou51UrvM4uNm9bgQw3laTw_0[1].offset = offsetof(tyObject_StreamcolonObjectType___ADoOUY5nj7w3cjSeMpeq9bg, lastc);
TM__4ou51UrvM4uNm9bgQw3laTw_0[1].typ = (&NTIcint__nlCscttRCss70IBTyuBqnA_);
TM__4ou51UrvM4uNm9bgQw3laTw_0[1].name = "lastc";
TM__4ou51UrvM4uNm9bgQw3laTw_2_2[1] = &TM__4ou51UrvM4uNm9bgQw3laTw_0[2];
NTIstreamtype__TofVVp0EcIEQmjSy5V7iMQ_.size = sizeof(tyEnum_StreamType__TofVVp0EcIEQmjSy5V7iMQ);
NTIstreamtype__TofVVp0EcIEQmjSy5V7iMQ_.align = NIM_ALIGNOF(tyEnum_StreamType__TofVVp0EcIEQmjSy5V7iMQ);
NTIstreamtype__TofVVp0EcIEQmjSy5V7iMQ_.kind = 14;
NTIstreamtype__TofVVp0EcIEQmjSy5V7iMQ_.base = 0;
NTIstreamtype__TofVVp0EcIEQmjSy5V7iMQ_.flags = 3;
for (TM__4ou51UrvM4uNm9bgQw3laTw_5 = 0; TM__4ou51UrvM4uNm9bgQw3laTw_5 < 3; TM__4ou51UrvM4uNm9bgQw3laTw_5++) {
TM__4ou51UrvM4uNm9bgQw3laTw_0[TM__4ou51UrvM4uNm9bgQw3laTw_5+3].kind = 1;
TM__4ou51UrvM4uNm9bgQw3laTw_0[TM__4ou51UrvM4uNm9bgQw3laTw_5+3].offset = TM__4ou51UrvM4uNm9bgQw3laTw_5;
TM__4ou51UrvM4uNm9bgQw3laTw_0[TM__4ou51UrvM4uNm9bgQw3laTw_5+3].name = TM__4ou51UrvM4uNm9bgQw3laTw_4[TM__4ou51UrvM4uNm9bgQw3laTw_5];
TM__4ou51UrvM4uNm9bgQw3laTw_3_3[TM__4ou51UrvM4uNm9bgQw3laTw_5] = &TM__4ou51UrvM4uNm9bgQw3laTw_0[TM__4ou51UrvM4uNm9bgQw3laTw_5+3];
}
TM__4ou51UrvM4uNm9bgQw3laTw_0[6].len = 3; TM__4ou51UrvM4uNm9bgQw3laTw_0[6].kind = 2; TM__4ou51UrvM4uNm9bgQw3laTw_0[6].sons = &TM__4ou51UrvM4uNm9bgQw3laTw_3_3[0];
NTIstreamtype__TofVVp0EcIEQmjSy5V7iMQ_.node = &TM__4ou51UrvM4uNm9bgQw3laTw_0[6];
TM__4ou51UrvM4uNm9bgQw3laTw_0[2].kind = 3;
TM__4ou51UrvM4uNm9bgQw3laTw_0[2].offset = offsetof(tyObject_StreamcolonObjectType___ADoOUY5nj7w3cjSeMpeq9bg, k);
TM__4ou51UrvM4uNm9bgQw3laTw_0[2].typ = (&NTIstreamtype__TofVVp0EcIEQmjSy5V7iMQ_);
TM__4ou51UrvM4uNm9bgQw3laTw_0[2].name = "k";
TM__4ou51UrvM4uNm9bgQw3laTw_0[2].sons = &NimDT___ADoOUY5nj7w3cjSeMpeq9bg_k[0];
TM__4ou51UrvM4uNm9bgQw3laTw_0[2].len = 3;
TM__4ou51UrvM4uNm9bgQw3laTw_0[7].kind = 1;
TM__4ou51UrvM4uNm9bgQw3laTw_0[7].offset = offsetof(tyObject_StreamcolonObjectType___ADoOUY5nj7w3cjSeMpeq9bg, _k_1.fd);
TM__4ou51UrvM4uNm9bgQw3laTw_0[7].typ = (&NTIpointer__vr5DoT1jILTGdRlYv1OYpw_);
TM__4ou51UrvM4uNm9bgQw3laTw_0[7].name = "fd";
NimDT___ADoOUY5nj7w3cjSeMpeq9bg_k[0] = &TM__4ou51UrvM4uNm9bgQw3laTw_0[7];
TM__4ou51UrvM4uNm9bgQw3laTw_6_2[0] = &TM__4ou51UrvM4uNm9bgQw3laTw_0[9];
TM__4ou51UrvM4uNm9bgQw3laTw_0[9].kind = 1;
TM__4ou51UrvM4uNm9bgQw3laTw_0[9].offset = offsetof(tyObject_StreamcolonObjectType___ADoOUY5nj7w3cjSeMpeq9bg, _k_2.s);
TM__4ou51UrvM4uNm9bgQw3laTw_0[9].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__4ou51UrvM4uNm9bgQw3laTw_0[9].name = "s";
TM__4ou51UrvM4uNm9bgQw3laTw_6_2[1] = &TM__4ou51UrvM4uNm9bgQw3laTw_0[10];
TM__4ou51UrvM4uNm9bgQw3laTw_0[10].kind = 1;
TM__4ou51UrvM4uNm9bgQw3laTw_0[10].offset = offsetof(tyObject_StreamcolonObjectType___ADoOUY5nj7w3cjSeMpeq9bg, _k_2.i);
TM__4ou51UrvM4uNm9bgQw3laTw_0[10].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__4ou51UrvM4uNm9bgQw3laTw_0[10].name = "i";
TM__4ou51UrvM4uNm9bgQw3laTw_0[8].len = 2; TM__4ou51UrvM4uNm9bgQw3laTw_0[8].kind = 2; TM__4ou51UrvM4uNm9bgQw3laTw_0[8].sons = &TM__4ou51UrvM4uNm9bgQw3laTw_6_2[0];
NimDT___ADoOUY5nj7w3cjSeMpeq9bg_k[1] = &TM__4ou51UrvM4uNm9bgQw3laTw_0[8];
NimDT___ADoOUY5nj7w3cjSeMpeq9bg_k[2] = &TM__4ou51UrvM4uNm9bgQw3laTw_0[8];
TM__4ou51UrvM4uNm9bgQw3laTw_0[0].len = 2; TM__4ou51UrvM4uNm9bgQw3laTw_0[0].kind = 2; TM__4ou51UrvM4uNm9bgQw3laTw_0[0].sons = &TM__4ou51UrvM4uNm9bgQw3laTw_2_2[0];
NTIstream58objecttype__ADoOUY5nj7w3cjSeMpeq9bg_.node = &TM__4ou51UrvM4uNm9bgQw3laTw_0[0];
NTIstream__2AlBaOTpGzA9cZMzGezDKRg_.size = sizeof(tyObject_StreamcolonObjectType___ADoOUY5nj7w3cjSeMpeq9bg*);
NTIstream__2AlBaOTpGzA9cZMzGezDKRg_.align = NIM_ALIGNOF(tyObject_StreamcolonObjectType___ADoOUY5nj7w3cjSeMpeq9bg*);
NTIstream__2AlBaOTpGzA9cZMzGezDKRg_.kind = 22;
NTIstream__2AlBaOTpGzA9cZMzGezDKRg_.base = (&NTIstream58objecttype__ADoOUY5nj7w3cjSeMpeq9bg_);
NTIstream__2AlBaOTpGzA9cZMzGezDKRg_.marker = Marker_tyRef__2AlBaOTpGzA9cZMzGezDKRg;
}

