/* Generated by Nim Compiler v1.6.6 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\Users\林仁傑\source\mingw64\bin\gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN   -IC:\Users\林仁傑\source\nim-1.6.6\lib -IC:\Users\林仁傑\source\Runner\cc -o C:\Users\林仁傑\source\Runner\cc\foo\stdlib_sequtils.nim.c.o C:\Users\林仁傑\source\Runner\cc\foo\stdlib_sequtils.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  typedef NU16 tyEnum_Token__yacSdq7TgJW2WjbLts9buTg;
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_2999)(void);
static N_INLINE(void, popFrame)(void);
extern TFrame* framePtr__system_2566;
extern TFrame* framePtr__system_2566;
extern TFrame* framePtr__system_2566;
extern TFrame* framePtr__system_2566;
extern TFrame* framePtr__system_2566;
extern TFrame* framePtr__system_2566;
static N_INLINE(void, nimFrame)(TFrame* s) {
	{
		if (!(framePtr__system_2566 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s).calldepth = ((NI16) 0);
	}
	goto LA1_;
	LA3_: ;
	{
		(*s).calldepth = (NI16)((*framePtr__system_2566).calldepth + ((NI16) 1));
	}
	LA1_: ;
	(*s).prev = framePtr__system_2566;
	framePtr__system_2566 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;
		callDepthLimitReached__system_2999();
	}
	LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_2566 = (*framePtr__system_2566).prev;
}
N_LIB_PRIVATE N_NIMCALL(NI, count__parser_8574)(tyEnum_Token__yacSdq7TgJW2WjbLts9buTg* s, NI sLen_0, tyEnum_Token__yacSdq7TgJW2WjbLts9buTg x) {
	NI result;
	nimfr_("count", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\pure\\collections\\sequtils.nim");
	result = (NI)0;
	{
		tyEnum_Token__yacSdq7TgJW2WjbLts9buTg* itm;
		NI i;
		itm = (tyEnum_Token__yacSdq7TgJW2WjbLts9buTg*)0;
		nimln_(8, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\iterators.nim");
		i = ((NI) 0);
		{
			nimln_(9, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\iterators.nim");
			while (1) {
				NI TM__77ITQxrABVT9b2GcbWeV4SQ_3;
				if (!(i < sLen_0)) goto LA3;
				nimln_(150, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\pure\\collections\\sequtils.nim");
				if (i < 0 || i >= sLen_0){ raiseIndexError2(i,sLen_0-1); }
				itm = (&s[i]);
				{
					NI TM__77ITQxrABVT9b2GcbWeV4SQ_2;
					nimln_(151, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\pure\\collections\\sequtils.nim");
					if (!((*itm) == x)) goto LA6_;
					nimln_(152, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\pure\\collections\\sequtils.nim");
					if (nimAddInt(result, ((NI) 1), &TM__77ITQxrABVT9b2GcbWeV4SQ_2)) { raiseOverflow(); };
					result = (NI)(TM__77ITQxrABVT9b2GcbWeV4SQ_2);
				}
				LA6_: ;
				nimln_(11, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\system\\iterators.nim");
				if (nimAddInt(i, ((NI) 1), &TM__77ITQxrABVT9b2GcbWeV4SQ_3)) { raiseOverflow(); };
				i = (NI)(TM__77ITQxrABVT9b2GcbWeV4SQ_3);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}
