/* Generated by Nim Compiler v1.6.6 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\Users\林仁傑\source\mingw64\bin\gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN   -IC:\Users\林仁傑\source\nim-1.6.6\lib -IC:\Users\林仁傑\source\Runner\cc -o C:\Users\林仁傑\source\Runner\cc\foo\stdlib_exitprocs.nim.c.o C:\Users\林仁傑\source\Runner\cc\foo\stdlib_exitprocs.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <windows.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  typedef struct tySequence__jPly7LEWA9bR7s5RNk1UriQ tySequence__jPly7LEWA9bR7s5RNk1UriQ;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_Fun__8SmujJ2dv64FQZRj9avIvVw tyObject_Fun__8SmujJ2dv64FQZRj9avIvVw;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
struct TGenericSeq {
NI len;
NI reserved;
};
typedef NU8 tyEnum_FunKind__ThaC3LIrCpK9cJoqLuqYlBA;
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc__HzVCwACFYM9cx9aV62PdjtuA;
typedef N_NOCONV_PTR(void, tyProc__vhjNbzH0Mvv2fTvoe1717Q) (void);
struct tyObject_Fun__8SmujJ2dv64FQZRj9avIvVw {
tyEnum_FunKind__ThaC3LIrCpK9cJoqLuqYlBA kind;
union{
tyProc__HzVCwACFYM9cx9aV62PdjtuA fun1;
tyProc__vhjNbzH0Mvv2fTvoe1717Q fun2;
};
};
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
NI align;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct tySequence__jPly7LEWA9bR7s5RNk1UriQ {
  TGenericSeq Sup;
  tyObject_Fun__8SmujJ2dv64FQZRj9avIvVw data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tySequence__jPly7LEWA9bR7s5RNk1UriQ)(void* p, NI op);
static N_NIMCALL(void, TM__JXL39bfraktrl3ZkJ5EQGjw_5)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
static N_INLINE(void, initLock__coreZlocks_47)(CRITICAL_SECTION* lock);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_2999)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE TNimType NTIfun__8SmujJ2dv64FQZRj9avIvVw_;
N_LIB_PRIVATE TNimType NTIfunkind__ThaC3LIrCpK9cJoqLuqYlBA_;
TNimNode* NimDT___8SmujJ2dv64FQZRj9avIvVw_kind[3];
extern TNimType NTIprocLTLOclosureOT__HzVCwACFYM9cx9aV62PdjtuA_;
N_LIB_PRIVATE TNimType NTIprocLTLOnoconvOT__vhjNbzH0Mvv2fTvoe1717Q_;
N_LIB_PRIVATE TNimType NTIseqLfunT__jPly7LEWA9bR7s5RNk1UriQ_;
N_LIB_PRIVATE CRITICAL_SECTION gFunsLock__stdZexitprocs_14;
N_LIB_PRIVATE tySequence__jPly7LEWA9bR7s5RNk1UriQ* gFuns__stdZexitprocs_15;
extern NI nim_program_result;
extern TFrame* framePtr__system_2566;
extern TFrame* framePtr__system_2566;
extern TFrame* framePtr__system_2566;
extern TFrame* framePtr__system_2566;
extern TFrame* framePtr__system_2566;
extern TFrame* framePtr__system_2566;
static N_NIMCALL(void, Marker_tySequence__jPly7LEWA9bR7s5RNk1UriQ)(void* p, NI op) {
	tySequence__jPly7LEWA9bR7s5RNk1UriQ* a;
	NI T1_;
	a = (tySequence__jPly7LEWA9bR7s5RNk1UriQ*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < (a ? a->Sup.len : 0); T1_++) {
	switch (a->data[T1_].kind) {
	case ((tyEnum_FunKind__ThaC3LIrCpK9cJoqLuqYlBA) 0):
	nimGCvisit((void*)a->data[T1_].fun1.ClE_0, op);
	break;
	case ((tyEnum_FunKind__ThaC3LIrCpK9cJoqLuqYlBA) 1):
	break;
	} 
	}
}
static N_NIMCALL(void, TM__JXL39bfraktrl3ZkJ5EQGjw_5)(void) {
	nimGCvisit((void*)gFuns__stdZexitprocs_15, 0);
}
static N_INLINE(void, initLock__coreZlocks_47)(CRITICAL_SECTION* lock) {
	InitializeCriticalSection(lock);
}
static N_INLINE(void, nimFrame)(TFrame* s) {
	{
		if (!(framePtr__system_2566 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s).calldepth = ((NI16) 0);
	}
	goto LA1_;
	LA3_: ;
	{
		(*s).calldepth = (NI16)((*framePtr__system_2566).calldepth + ((NI16) 1));
	}
	LA1_: ;
	(*s).prev = framePtr__system_2566;
	framePtr__system_2566 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;
		callDepthLimitReached__system_2999();
	}
	LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_2566 = (*framePtr__system_2566).prev;
}
N_LIB_PRIVATE N_NIMCALL(void, setProgramResult__stdZexitprocs_115)(NI a) {
	nimfr_("setProgramResult", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\std\\exitprocs.nim");
	nimln_(85, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\std\\exitprocs.nim");
	nim_program_result = a;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, stdlib_exitprocsInit000)(void) {
{
	TFrame FR_; FR_.len = 0;

	nimRegisterGlobalMarker(TM__JXL39bfraktrl3ZkJ5EQGjw_5);

}/* preInitProc end */
{
	nimfr_("exitprocs", "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\std\\exitprocs.nim");
	nimln_(23, "C:\\Users\\\346\236\227\344\273\201\345\202\221\\source\\nim-1.6.6\\lib\\std\\exitprocs.nim");
	initLock__coreZlocks_47((&gFunsLock__stdZexitprocs_14));
	popFrame();
}
}

N_LIB_PRIVATE N_NIMCALL(void, stdlib_exitprocsDatInit000)(void) {
static TNimNode* TM__JXL39bfraktrl3ZkJ5EQGjw_2_2[2];
NI TM__JXL39bfraktrl3ZkJ5EQGjw_4;
static char* NIM_CONST TM__JXL39bfraktrl3ZkJ5EQGjw_3[2] = {
"kClosure", 
"kNoconv"};
static TNimNode TM__JXL39bfraktrl3ZkJ5EQGjw_0[6];
NTIfun__8SmujJ2dv64FQZRj9avIvVw_.size = sizeof(tyObject_Fun__8SmujJ2dv64FQZRj9avIvVw);
NTIfun__8SmujJ2dv64FQZRj9avIvVw_.align = NIM_ALIGNOF(tyObject_Fun__8SmujJ2dv64FQZRj9avIvVw);
NTIfun__8SmujJ2dv64FQZRj9avIvVw_.kind = 18;
NTIfun__8SmujJ2dv64FQZRj9avIvVw_.base = 0;
NTIfunkind__ThaC3LIrCpK9cJoqLuqYlBA_.size = sizeof(tyEnum_FunKind__ThaC3LIrCpK9cJoqLuqYlBA);
NTIfunkind__ThaC3LIrCpK9cJoqLuqYlBA_.align = NIM_ALIGNOF(tyEnum_FunKind__ThaC3LIrCpK9cJoqLuqYlBA);
NTIfunkind__ThaC3LIrCpK9cJoqLuqYlBA_.kind = 14;
NTIfunkind__ThaC3LIrCpK9cJoqLuqYlBA_.base = 0;
NTIfunkind__ThaC3LIrCpK9cJoqLuqYlBA_.flags = 3;
for (TM__JXL39bfraktrl3ZkJ5EQGjw_4 = 0; TM__JXL39bfraktrl3ZkJ5EQGjw_4 < 2; TM__JXL39bfraktrl3ZkJ5EQGjw_4++) {
TM__JXL39bfraktrl3ZkJ5EQGjw_0[TM__JXL39bfraktrl3ZkJ5EQGjw_4+1].kind = 1;
TM__JXL39bfraktrl3ZkJ5EQGjw_0[TM__JXL39bfraktrl3ZkJ5EQGjw_4+1].offset = TM__JXL39bfraktrl3ZkJ5EQGjw_4;
TM__JXL39bfraktrl3ZkJ5EQGjw_0[TM__JXL39bfraktrl3ZkJ5EQGjw_4+1].name = TM__JXL39bfraktrl3ZkJ5EQGjw_3[TM__JXL39bfraktrl3ZkJ5EQGjw_4];
TM__JXL39bfraktrl3ZkJ5EQGjw_2_2[TM__JXL39bfraktrl3ZkJ5EQGjw_4] = &TM__JXL39bfraktrl3ZkJ5EQGjw_0[TM__JXL39bfraktrl3ZkJ5EQGjw_4+1];
}
TM__JXL39bfraktrl3ZkJ5EQGjw_0[3].len = 2; TM__JXL39bfraktrl3ZkJ5EQGjw_0[3].kind = 2; TM__JXL39bfraktrl3ZkJ5EQGjw_0[3].sons = &TM__JXL39bfraktrl3ZkJ5EQGjw_2_2[0];
NTIfunkind__ThaC3LIrCpK9cJoqLuqYlBA_.node = &TM__JXL39bfraktrl3ZkJ5EQGjw_0[3];
TM__JXL39bfraktrl3ZkJ5EQGjw_0[0].kind = 3;
TM__JXL39bfraktrl3ZkJ5EQGjw_0[0].offset = offsetof(tyObject_Fun__8SmujJ2dv64FQZRj9avIvVw, kind);
TM__JXL39bfraktrl3ZkJ5EQGjw_0[0].typ = (&NTIfunkind__ThaC3LIrCpK9cJoqLuqYlBA_);
TM__JXL39bfraktrl3ZkJ5EQGjw_0[0].name = "kind";
TM__JXL39bfraktrl3ZkJ5EQGjw_0[0].sons = &NimDT___8SmujJ2dv64FQZRj9avIvVw_kind[0];
TM__JXL39bfraktrl3ZkJ5EQGjw_0[0].len = 2;
TM__JXL39bfraktrl3ZkJ5EQGjw_0[4].kind = 1;
TM__JXL39bfraktrl3ZkJ5EQGjw_0[4].offset = offsetof(tyObject_Fun__8SmujJ2dv64FQZRj9avIvVw, fun1);
TM__JXL39bfraktrl3ZkJ5EQGjw_0[4].typ = (&NTIprocLTLOclosureOT__HzVCwACFYM9cx9aV62PdjtuA_);
TM__JXL39bfraktrl3ZkJ5EQGjw_0[4].name = "fun1";
NimDT___8SmujJ2dv64FQZRj9avIvVw_kind[0] = &TM__JXL39bfraktrl3ZkJ5EQGjw_0[4];
NTIprocLTLOnoconvOT__vhjNbzH0Mvv2fTvoe1717Q_.size = sizeof(tyProc__vhjNbzH0Mvv2fTvoe1717Q);
NTIprocLTLOnoconvOT__vhjNbzH0Mvv2fTvoe1717Q_.align = NIM_ALIGNOF(tyProc__vhjNbzH0Mvv2fTvoe1717Q);
NTIprocLTLOnoconvOT__vhjNbzH0Mvv2fTvoe1717Q_.kind = 25;
NTIprocLTLOnoconvOT__vhjNbzH0Mvv2fTvoe1717Q_.base = 0;
NTIprocLTLOnoconvOT__vhjNbzH0Mvv2fTvoe1717Q_.flags = 3;
TM__JXL39bfraktrl3ZkJ5EQGjw_0[5].kind = 1;
TM__JXL39bfraktrl3ZkJ5EQGjw_0[5].offset = offsetof(tyObject_Fun__8SmujJ2dv64FQZRj9avIvVw, fun2);
TM__JXL39bfraktrl3ZkJ5EQGjw_0[5].typ = (&NTIprocLTLOnoconvOT__vhjNbzH0Mvv2fTvoe1717Q_);
TM__JXL39bfraktrl3ZkJ5EQGjw_0[5].name = "fun2";
NimDT___8SmujJ2dv64FQZRj9avIvVw_kind[1] = &TM__JXL39bfraktrl3ZkJ5EQGjw_0[5];
NTIfun__8SmujJ2dv64FQZRj9avIvVw_.node = &TM__JXL39bfraktrl3ZkJ5EQGjw_0[0];
NTIseqLfunT__jPly7LEWA9bR7s5RNk1UriQ_.size = sizeof(tySequence__jPly7LEWA9bR7s5RNk1UriQ*);
NTIseqLfunT__jPly7LEWA9bR7s5RNk1UriQ_.align = NIM_ALIGNOF(tySequence__jPly7LEWA9bR7s5RNk1UriQ*);
NTIseqLfunT__jPly7LEWA9bR7s5RNk1UriQ_.kind = 24;
NTIseqLfunT__jPly7LEWA9bR7s5RNk1UriQ_.base = (&NTIfun__8SmujJ2dv64FQZRj9avIvVw_);
NTIseqLfunT__jPly7LEWA9bR7s5RNk1UriQ_.marker = Marker_tySequence__jPly7LEWA9bR7s5RNk1UriQ;
}

