/* Generated by Nim Compiler v1.6.6 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\Users\林仁傑\source\mingw64\bin\gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN -O3 -fno-strict-aliasing -fno-ident   -IC:\Users\林仁傑\source\nim-1.6.6\lib -IC:\Users\林仁傑\source\Runner\cc -o C:\Users\林仁傑\source\Runner\cc\foo\stdlib_unicode.nim.c.o C:\Users\林仁傑\source\Runner\cc\foo\stdlib_unicode.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
static N_INLINE(NIM_BOOL, lteqpercent___system_997)(NI32 x, NI32 y);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newLen);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
static N_INLINE(NIM_BOOL, lteqpercent___system_997)(NI32 x, NI32 y) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = ((NU32)(((NU32) (x))) <= (NU32)(((NU32) (y))));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nuctoUTF8)(NI32 c) {
	NimStringDesc* result;
	NI32 iX60gensym49_;
	result = NIM_NIL;
	result = ((NimStringDesc*) NIM_NIL);
	iX60gensym49_ = c;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = lteqpercent___system_997(iX60gensym49_, ((NI32) 127));
		if (!T3_) goto LA4_;
		result = setLengthStr(result, ((NI) 1));
		if (((NI) 0) < 0 || ((NI) 0) >= (result ? result->Sup.len : 0)){ raiseIndexError2(((NI) 0),(result ? result->Sup.len : 0)-1); }
		if ((iX60gensym49_) < ((NI) 0) || (iX60gensym49_) > ((NI) 255)){ raiseRangeErrorI(iX60gensym49_, ((NI) 0), ((NI) 255)); }
		result->data[((NI) 0)] = ((NIM_CHAR) (((NI) (iX60gensym49_))));
	}
	goto LA1_;
	LA4_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = lteqpercent___system_997(iX60gensym49_, ((NI32) 2047));
		if (!T7_) goto LA8_;
		result = setLengthStr(result, ((NI) 2));
		if (((NI) 0) < 0 || ((NI) 0) >= (result ? result->Sup.len : 0)){ raiseIndexError2(((NI) 0),(result ? result->Sup.len : 0)-1); }
		if (((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 6))) | ((NI32) 192))) < ((NI) 0) || ((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 6))) | ((NI32) 192))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 6))) | ((NI32) 192)), ((NI) 0), ((NI) 255)); }
		result->data[((NI) 0)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 6))) | ((NI32) 192))))));
		if (((NI) 1) < 0 || ((NI) 1) >= (result ? result->Sup.len : 0)){ raiseIndexError2(((NI) 1),(result ? result->Sup.len : 0)-1); }
		if (((NI32)((NI32)(iX60gensym49_ & ((NI32) 63)) | ((NI32) 128))) < ((NI) 0) || ((NI32)((NI32)(iX60gensym49_ & ((NI32) 63)) | ((NI32) 128))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)(iX60gensym49_ & ((NI32) 63)) | ((NI32) 128)), ((NI) 0), ((NI) 255)); }
		result->data[((NI) 1)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)(iX60gensym49_ & ((NI32) 63)) | ((NI32) 128))))));
	}
	goto LA1_;
	LA8_: ;
	{
		NIM_BOOL T11_;
		T11_ = (NIM_BOOL)0;
		T11_ = lteqpercent___system_997(iX60gensym49_, ((NI32) 65535));
		if (!T11_) goto LA12_;
		result = setLengthStr(result, ((NI) 3));
		if (((NI) 0) < 0 || ((NI) 0) >= (result ? result->Sup.len : 0)){ raiseIndexError2(((NI) 0),(result ? result->Sup.len : 0)-1); }
		if (((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 12))) | ((NI32) 224))) < ((NI) 0) || ((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 12))) | ((NI32) 224))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 12))) | ((NI32) 224)), ((NI) 0), ((NI) 255)); }
		result->data[((NI) 0)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 12))) | ((NI32) 224))))));
		if (((NI) 1) < 0 || ((NI) 1) >= (result ? result->Sup.len : 0)){ raiseIndexError2(((NI) 1),(result ? result->Sup.len : 0)-1); }
		if (((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 6))) & ((NI32) 63)) | ((NI32) 128))) < ((NI) 0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 6))) & ((NI32) 63)) | ((NI32) 128))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 6))) & ((NI32) 63)) | ((NI32) 128)), ((NI) 0), ((NI) 255)); }
		result->data[((NI) 1)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 6))) & ((NI32) 63)) | ((NI32) 128))))));
		if (((NI) 2) < 0 || ((NI) 2) >= (result ? result->Sup.len : 0)){ raiseIndexError2(((NI) 2),(result ? result->Sup.len : 0)-1); }
		if (((NI32)((NI32)(iX60gensym49_ & ((NI32) 63)) | ((NI32) 128))) < ((NI) 0) || ((NI32)((NI32)(iX60gensym49_ & ((NI32) 63)) | ((NI32) 128))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)(iX60gensym49_ & ((NI32) 63)) | ((NI32) 128)), ((NI) 0), ((NI) 255)); }
		result->data[((NI) 2)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)(iX60gensym49_ & ((NI32) 63)) | ((NI32) 128))))));
	}
	goto LA1_;
	LA12_: ;
	{
		NIM_BOOL T15_;
		T15_ = (NIM_BOOL)0;
		T15_ = lteqpercent___system_997(iX60gensym49_, ((NI32) 2097151));
		if (!T15_) goto LA16_;
		result = setLengthStr(result, ((NI) 4));
		if (((NI) 0) < 0 || ((NI) 0) >= (result ? result->Sup.len : 0)){ raiseIndexError2(((NI) 0),(result ? result->Sup.len : 0)-1); }
		if (((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 18))) | ((NI32) 240))) < ((NI) 0) || ((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 18))) | ((NI32) 240))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 18))) | ((NI32) 240)), ((NI) 0), ((NI) 255)); }
		result->data[((NI) 0)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 18))) | ((NI32) 240))))));
		if (((NI) 1) < 0 || ((NI) 1) >= (result ? result->Sup.len : 0)){ raiseIndexError2(((NI) 1),(result ? result->Sup.len : 0)-1); }
		if (((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 12))) & ((NI32) 63)) | ((NI32) 128))) < ((NI) 0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 12))) & ((NI32) 63)) | ((NI32) 128))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 12))) & ((NI32) 63)) | ((NI32) 128)), ((NI) 0), ((NI) 255)); }
		result->data[((NI) 1)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 12))) & ((NI32) 63)) | ((NI32) 128))))));
		if (((NI) 2) < 0 || ((NI) 2) >= (result ? result->Sup.len : 0)){ raiseIndexError2(((NI) 2),(result ? result->Sup.len : 0)-1); }
		if (((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 6))) & ((NI32) 63)) | ((NI32) 128))) < ((NI) 0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 6))) & ((NI32) 63)) | ((NI32) 128))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 6))) & ((NI32) 63)) | ((NI32) 128)), ((NI) 0), ((NI) 255)); }
		result->data[((NI) 2)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 6))) & ((NI32) 63)) | ((NI32) 128))))));
		if (((NI) 3) < 0 || ((NI) 3) >= (result ? result->Sup.len : 0)){ raiseIndexError2(((NI) 3),(result ? result->Sup.len : 0)-1); }
		if (((NI32)((NI32)(iX60gensym49_ & ((NI32) 63)) | ((NI32) 128))) < ((NI) 0) || ((NI32)((NI32)(iX60gensym49_ & ((NI32) 63)) | ((NI32) 128))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)(iX60gensym49_ & ((NI32) 63)) | ((NI32) 128)), ((NI) 0), ((NI) 255)); }
		result->data[((NI) 3)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)(iX60gensym49_ & ((NI32) 63)) | ((NI32) 128))))));
	}
	goto LA1_;
	LA16_: ;
	{
		NIM_BOOL T19_;
		T19_ = (NIM_BOOL)0;
		T19_ = lteqpercent___system_997(iX60gensym49_, ((NI32) 67108863));
		if (!T19_) goto LA20_;
		result = setLengthStr(result, ((NI) 5));
		if (((NI) 0) < 0 || ((NI) 0) >= (result ? result->Sup.len : 0)){ raiseIndexError2(((NI) 0),(result ? result->Sup.len : 0)-1); }
		if (((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 24))) | ((NI32) 248))) < ((NI) 0) || ((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 24))) | ((NI32) 248))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 24))) | ((NI32) 248)), ((NI) 0), ((NI) 255)); }
		result->data[((NI) 0)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 24))) | ((NI32) 248))))));
		if (((NI) 1) < 0 || ((NI) 1) >= (result ? result->Sup.len : 0)){ raiseIndexError2(((NI) 1),(result ? result->Sup.len : 0)-1); }
		if (((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 18))) & ((NI32) 63)) | ((NI32) 128))) < ((NI) 0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 18))) & ((NI32) 63)) | ((NI32) 128))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 18))) & ((NI32) 63)) | ((NI32) 128)), ((NI) 0), ((NI) 255)); }
		result->data[((NI) 1)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 18))) & ((NI32) 63)) | ((NI32) 128))))));
		if (((NI) 2) < 0 || ((NI) 2) >= (result ? result->Sup.len : 0)){ raiseIndexError2(((NI) 2),(result ? result->Sup.len : 0)-1); }
		if (((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 12))) & ((NI32) 63)) | ((NI32) 128))) < ((NI) 0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 12))) & ((NI32) 63)) | ((NI32) 128))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 12))) & ((NI32) 63)) | ((NI32) 128)), ((NI) 0), ((NI) 255)); }
		result->data[((NI) 2)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 12))) & ((NI32) 63)) | ((NI32) 128))))));
		if (((NI) 3) < 0 || ((NI) 3) >= (result ? result->Sup.len : 0)){ raiseIndexError2(((NI) 3),(result ? result->Sup.len : 0)-1); }
		if (((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 6))) & ((NI32) 63)) | ((NI32) 128))) < ((NI) 0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 6))) & ((NI32) 63)) | ((NI32) 128))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 6))) & ((NI32) 63)) | ((NI32) 128)), ((NI) 0), ((NI) 255)); }
		result->data[((NI) 3)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 6))) & ((NI32) 63)) | ((NI32) 128))))));
		if (((NI) 4) < 0 || ((NI) 4) >= (result ? result->Sup.len : 0)){ raiseIndexError2(((NI) 4),(result ? result->Sup.len : 0)-1); }
		if (((NI32)((NI32)(iX60gensym49_ & ((NI32) 63)) | ((NI32) 128))) < ((NI) 0) || ((NI32)((NI32)(iX60gensym49_ & ((NI32) 63)) | ((NI32) 128))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)(iX60gensym49_ & ((NI32) 63)) | ((NI32) 128)), ((NI) 0), ((NI) 255)); }
		result->data[((NI) 4)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)(iX60gensym49_ & ((NI32) 63)) | ((NI32) 128))))));
	}
	goto LA1_;
	LA20_: ;
	{
		NIM_BOOL T23_;
		T23_ = (NIM_BOOL)0;
		T23_ = lteqpercent___system_997(iX60gensym49_, ((NI32) 2147483647));
		if (!T23_) goto LA24_;
		result = setLengthStr(result, ((NI) 6));
		if (((NI) 0) < 0 || ((NI) 0) >= (result ? result->Sup.len : 0)){ raiseIndexError2(((NI) 0),(result ? result->Sup.len : 0)-1); }
		if (((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 30))) | ((NI32) 252))) < ((NI) 0) || ((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 30))) | ((NI32) 252))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 30))) | ((NI32) 252)), ((NI) 0), ((NI) 255)); }
		result->data[((NI) 0)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 30))) | ((NI32) 252))))));
		if (((NI) 1) < 0 || ((NI) 1) >= (result ? result->Sup.len : 0)){ raiseIndexError2(((NI) 1),(result ? result->Sup.len : 0)-1); }
		if (((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 24))) & ((NI32) 63)) | ((NI32) 128))) < ((NI) 0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 24))) & ((NI32) 63)) | ((NI32) 128))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 24))) & ((NI32) 63)) | ((NI32) 128)), ((NI) 0), ((NI) 255)); }
		result->data[((NI) 1)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 24))) & ((NI32) 63)) | ((NI32) 128))))));
		if (((NI) 2) < 0 || ((NI) 2) >= (result ? result->Sup.len : 0)){ raiseIndexError2(((NI) 2),(result ? result->Sup.len : 0)-1); }
		if (((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 18))) & ((NI32) 63)) | ((NI32) 128))) < ((NI) 0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 18))) & ((NI32) 63)) | ((NI32) 128))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 18))) & ((NI32) 63)) | ((NI32) 128)), ((NI) 0), ((NI) 255)); }
		result->data[((NI) 2)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 18))) & ((NI32) 63)) | ((NI32) 128))))));
		if (((NI) 3) < 0 || ((NI) 3) >= (result ? result->Sup.len : 0)){ raiseIndexError2(((NI) 3),(result ? result->Sup.len : 0)-1); }
		if (((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 12))) & ((NI32) 63)) | ((NI32) 128))) < ((NI) 0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 12))) & ((NI32) 63)) | ((NI32) 128))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 12))) & ((NI32) 63)) | ((NI32) 128)), ((NI) 0), ((NI) 255)); }
		result->data[((NI) 3)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 12))) & ((NI32) 63)) | ((NI32) 128))))));
		if (((NI) 4) < 0 || ((NI) 4) >= (result ? result->Sup.len : 0)){ raiseIndexError2(((NI) 4),(result ? result->Sup.len : 0)-1); }
		if (((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 6))) & ((NI32) 63)) | ((NI32) 128))) < ((NI) 0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 6))) & ((NI32) 63)) | ((NI32) 128))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 6))) & ((NI32) 63)) | ((NI32) 128)), ((NI) 0), ((NI) 255)); }
		result->data[((NI) 4)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym49_) >> (NU64)(((NI) 6))) & ((NI32) 63)) | ((NI32) 128))))));
		if (((NI) 5) < 0 || ((NI) 5) >= (result ? result->Sup.len : 0)){ raiseIndexError2(((NI) 5),(result ? result->Sup.len : 0)-1); }
		if (((NI32)((NI32)(iX60gensym49_ & ((NI32) 63)) | ((NI32) 128))) < ((NI) 0) || ((NI32)((NI32)(iX60gensym49_ & ((NI32) 63)) | ((NI32) 128))) > ((NI) 255)){ raiseRangeErrorI((NI32)((NI32)(iX60gensym49_ & ((NI32) 63)) | ((NI32) 128)), ((NI) 0), ((NI) 255)); }
		result->data[((NI) 5)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)(iX60gensym49_ & ((NI32) 63)) | ((NI32) 128))))));
	}
	goto LA1_;
	LA24_: ;
	{
	}
	LA1_: ;
	return result;
}
